### ISSUE TITLE
标题不给加粗加黑吗

### ISSUE THREAD

**Issue by wuqiren** [Tencent/cherry-markdown#10]
![image](https://user-images.githubusercontent.com/54806027/139778367-0a3b7d72-6f2f-4420-bd27-d21e2fb84d5d.png)

###### 六级标题语法显示的文字比正文还小，而且不加黑加粗

**Comment by humyfred** [comment]
你好，如果觉得六级标题比较小且细，可以通过样式去处理的。后续我们会继续改善 cherry 样式

**Comment by sunsonliu** [comment]
搞搞搞，我们改下六级标题的模式样式

**Comment by sunsonliu** [comment]
已经参考了github-markdown的样式进行了修改，修改后H5、H6还是会比正文小，不过会加粗加黑。后面我们实现主题切换功能后会考虑增加一些能够突出所有标题的主题，敬请期待~
