### ISSUE TITLE
[Bug report] safari下输入内容报错

### ISSUE THREAD

**Issue by yangrunkang** [Tencent/cherry-markdown#100]
**Describe the bug**
见截图

**Screenshots**
![image](https://user-images.githubusercontent.com/46257933/148674598-efb03782-a2d5-47cc-a2b7-e209bbb84c5f.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 15.2 (17612.3.6.1.6)

**Comment by lyngai** [comment]
可能是个已知问题，可以先尝试一下使用 dev 分支的版本构建看看是否已修复。

**Comment by yangrunkang** [comment]
> 可能是个已知问题，可以先尝试一下使用 dev 分支的版本构建看看是否已修复。

使用dev分支构建后,问题已修复

**Comment by lyngai** [comment]
已发布 0.6.2 版本，包含了该 bugfix
