### ISSUE TITLE
[Feature Request] AI-chat场景，支持实现“输入光标”效果

### ISSUE THREAD

**Issue by alexhu** [Tencent/cherry-markdown#1006]
如题，希望在AI-chat场景下（flowSessionContext为true），支持输出的内容最后追加自定义html标签，实现“输入光标”效果，类似:
![录屏2024-12-18 20 06 33](https://github.com/user-attachments/assets/a31e4cd8-2e0c-4a89-9e43-1b57a53bd1e6)

**Comment by sunsonliu** [comment]
![局部截取_20241222_222920](https://github.com/user-attachments/assets/1664c392-4d6b-4e71-8b06-13b09b7c21cc)
已增加对应的配置，当配置为`flowSessionCursor: 'default‘`时，会在输出位置的末尾增加一个虚拟光标dom，可以通过调用`cherryObj.clearFlowSessionCursor()`主动去掉该虚拟光标dom，如果不主动清空该虚拟光标，cherry将在一小段时间后（大约2.5s）清空该虚拟光标

**Comment by sunsonliu** [comment]
https://tencent.github.io/cherry-markdown/examples/ai_chat.html
可以在这里体验哈，对应demo的源码在这里：https://github.com/Tencent/cherry-markdown/blob/main/examples/ai_chat.html
