### ISSUE TITLE
容器宽度发生动态变化时，光标会定位异常

### ISSUE THREAD

**Issue by 123GaoLin** [Tencent/cherry-markdown#1009]
### Prerequisites

- [ ] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://github.com/Tencent/cherry-markdown/tree/main/examples) of the bug, ([Why create a Minimal](https://stackoverflow.com/help/minimal-reproducible-example)).

- [ ] For [Q&A](https://github.com/Tencent/cherry-markdown/discussions/categories/q-a), please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Version

0.8.56

### Describe the Bug

当容器的宽度发生动态变化，光标定位会有异常，影响到了后续的编辑操作
PS: 这里的动态变化必须是业务方操作的变化，拖拽浏览器则不会复现

<img width="1407" alt="image" src="https://github.com/user-attachments/assets/6a638301-7b4a-436d-af5b-f651d45fa199" />

### Contributing

None

**Comment by jiakuan** [comment]
我也遇到同样的问题

**Comment by sunsonliu** [comment]
> 我也遇到同样的问题

收到，我们会安排修复哈，临时解决方案可以手动调用`cherry.editor.editor.refresh()`来强制刷新编辑器的状态
