### ISSUE TITLE
[Bug report] 工具栏小屏设备渲染问题

### ISSUE THREAD

**Issue by yangrunkang** [Tencent/cherry-markdown#101]
**Describe the bug**
移动端渲染问题

**To Reproduce**
1. Chrome浏览器F12
2. 点击 Toggle device toolbar按钮
3. 选择Pixel5等小屏设备

**Expected behavior**
小屏渲染正常

**Screenshots**
![image](https://user-images.githubusercontent.com/46257933/148681431-c71574c3-c9f8-4a62-a2ab-60d7bbb034bd.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version 版本 97.0.4692.71（正式版本） (x86_64)

**Additional context**
无

**Comment by sunsonliu** [comment]
收到，样式问题，在修复前，建议这么小的屏幕改成 **编辑/预览 切换模式** （参考：https://tencent.github.io/cherry-markdown/examples/h5.html ）如果已经是编辑预览切换模式了。。。那就当我没说

另外还有种临时解决方案，通过减少工具栏里的操作项来避免出现样式问题，比如把斜体、中划线、分隔符、列表干掉，如下图：
![image](https://user-images.githubusercontent.com/998441/153766907-4fabcca7-f6b3-41d2-b2ea-8734aeb6389a.png)

**Comment by yangrunkang** [comment]
👌🏻

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/commit/53b5340155007f2f26785aa0261c7d3546d41388 
已修复并提交到dev
