### ISSUE TITLE
[Bug report]页面快速跳转时，Cherry不按预期的渲染

### ISSUE THREAD

**Issue by Morris-G** [Tencent/cherry-markdown#103]
**Describe the bug**
在快速切换页面时，Cherry依然延迟渲染并附加在根节点内，影响了正常的使用。

**To Reproduce**
可参考[codepen](https://codepen.io/morris-g/pen/OJxwjPE)

**Expected behavior**
希望页面跳转后Cherry不再继续渲染

**Screenshots**
![image](https://user-images.githubusercontent.com/33714914/148727681-c7c2fc14-33de-41f8-aaa1-2a7cdd3c3866.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 0.5.14

**Additional context**
查看源码发现[这里](https://github.com/Tencent/cherry-markdown/blob/006d737a0259c81da7905f3c257c5e4eb25a2560/src/Cherry.js#L88)做了给定ID的dom节点是否存在的校验，如果不存在会创建此节点并插入根节点，因此会造成页面跳转后cherry才渲染出来的结果，希望能提供选项来决定没有指定dom的时候是否继续渲染，或者提供destory方法来阻止继续未完成的渲染...

**Comment by sunsonliu** [comment]
有道理，我们先提供个参数来判断是否继续渲染吧，destory方法一直在排期中（会比较漫长），还是实现个参数靠谱些。。。

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/releases/tag/v0.6.6
