### ISSUE TITLE
[Bug report]粘贴内容是提示按钮样式异常

### ISSUE THREAD

**Issue by Morris-G** [Tencent/cherry-markdown#104]
**Describe the bug**
从外部复制内容粘贴至Cherry时，提示粘贴格式的按钮样式有问题

**To Reproduce**
未设置全局`box-sizing:content-box`即可复现

**Expected behavior**
显示正常

**Screenshots**
![image](https://user-images.githubusercontent.com/33714914/148729059-edf89424-6132-4761-ad29-61a87ddf4c30.png)

![image](https://user-images.githubusercontent.com/33714914/148729050-e2efae60-88c7-41b4-b39b-8543087d20d0.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 0.5.14

**Additional context**
Cherry没有单独给`.cherry-switch-paste .cherry-toolbar-button`设置`box-sizing:content-box`，如果父级元素设置的是`border-box`时，按钮渲染就会有问题，另外如果设置之后父元素`.cherry-switch-paste`应该不用定宽了吧，个人拙见

**Comment by sunsonliu** [comment]
别拙见了，欢迎直接提PR ：）

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/releases/tag/v0.6.6
