### ISSUE TITLE
[Feature request] support color and bold together with no space 

### ISSUE THREAD

**Issue by mmaggie-ie** [Tencent/cherry-markdown#105]
Hi, I've been using md for a while in TAPD, and some usage were not same with current cherry-markdown

Can you give this a compatible support ?

```
!!#ff0000**some text**!!
```

<img width="641" alt="2ee38293-727b-4d12-b949-80f44a5fc9e9" src="https://user-images.githubusercontent.com/86417949/148731504-2a6f7569-1188-4722-bee8-0cb4887b54e8.png">

and here is TAPD preview
![2](https://user-images.githubusercontent.com/86417949/148731606-6707771e-fbc3-4e1a-9237-df0c93c520e0.png)

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/148950221-68da63e4-ab15-41ce-86d4-4061dd48a1a4.png)

TAPD基于CherryMarkdown做了扩展，其中一个扩展便是修改了字体颜色等语法的语法规则，这种扩展可以提高书写**便携度**，但会降低**准确度**，所以Cherry在github上的版本里并**没有包含**这些插件。如果你是腾讯内部的同事，你可以访问CherryMarkdown腾讯内源版本来使用TAPD贡献的相关插件能力；如果你是腾讯外部的朋友，我们欢迎你以TAPD这种方式扩展字体颜色、大小的相关语法（用自定义语法覆盖cherry的默认语法）

**Comment by mmaggie-ie** [comment]
我已收到您的邮件，会及时查收并回复，谢谢！-------------------------------------------------------

马沈骐
Ma Shenqi
东南大学 信息科学与工程学院
School of Information Science and Engineering
Southeast University
