### ISSUE TITLE
latex代码和代码块冲突

### ISSUE THREAD

**Issue by kagurakana** [Tencent/cherry-markdown#12]
![demo](https://user-images.githubusercontent.com/37036280/140034548-436087bd-4ada-4d95-b4f1-d6cc4410eef8.png)

虽然图中的 markdown 语法不正确，但是当我复制代码块中的 latex 代码粘贴后，这个问题就会出现。

![6VnhJNnXOc](https://user-images.githubusercontent.com/37036280/140035265-f0a11a9e-d478-44e6-8683-d3b4d2894a11.gif)

> 局部渲染和局部更新相对于 Bytemd 来说在长文本处理时性能确实提升了不少。相对于typora这种所见即所得的编辑器，我还是更喜欢 markdown 代码和渲染分开，感觉能看见 markdown 源代码会有安全感。另外 katex 貌似比 mathjax 在初次渲染时效果会好。另外我在[文档](https://github.com/Tencent/cherry-markdown/blob/main/docs/extensions.CN.md)中看到某些功能pro 版本可用，请问后续是会收费吗？后面的话我还是挺想用这个替换我博客里用的bytemd的😺

**Comment by sunsonliu** [comment]
## 关于复制粘贴
![image](https://user-images.githubusercontent.com/998441/140048326-71771a1c-f9ef-44ab-886a-7cfff9268022.png)

可以点**TEXT**哈，复制粘贴Html的时候，CherryMarkdown会自动尝试把Html转成Markdown源码，截图中，楼主是从html里复制的代码块，所以粘贴进来后会变成代码块语法。可以通过点击“TEXT”来切换成纯文本哈。

## 关于Katex
我们是支持配置Katex和Mathjax的，配置参考下图：
![image](https://user-images.githubusercontent.com/998441/140048854-0c3c0ffe-4f61-40cb-80f2-abdde2a1317a.png)

## 关于pro版
的确会有个pro版，pro版会提供表格图表（根据表格内容画图表，目前支持柱状图和折线图，见下图）、简单表格+单元格合并（另外一套表格语法，见下图）等功能。pro版本的开源协议会是GPL 2.0，目前并没有收费计划哈，只是开源协议不同而已。

- 表格图表
![image](https://user-images.githubusercontent.com/998441/140049316-bec2d41c-6517-4f06-95d8-6a5ed29829e1.png)
- 简单表格+单元格合并
![image](https://user-images.githubusercontent.com/998441/140049569-9338269c-426f-4f62-9129-ad265879a4f4.png)

**Comment by sunsonliu** [comment]
对了，关于公式语法里有代码块语法就悲剧的问题，是个已知bug哈，不过由于正常情况下不会出现这种组合，所以一直没有搞他

**Comment by kagurakana** [comment]
感谢十分详细的回答，感觉这个编辑器十分强悍，会持续关注这个项目的😻

**Comment by honglvagan** [comment]
请问下怎么用公式功能和draw.io?该调整哪里?这是我的html,目前无法用公式和draw.io,请问我该怎么写?
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <link rel="stylesheet" href="./cherry-markdown.css">
    <script src="./cherry-markdown.js"></script>


    <div id="markdown-container"></div>
    <script>
        new Cherry({
            id: 'markdown-container',
            value: '# 到此一游!',
            toolbars: {
                // 定义顶部工具栏
                toolbar: [
                    'undo', 'redo', '|',
                    // 把字体样式类按钮都放在加粗按钮下面
                    { bold: ['bold', 'italic', 'underline', 'strikethrough', 'sub', 'sup', 'ruby'] },
                    'color', 'size', '|', 'header', 'list', 'panel', '|',
                    // 把插入类按钮都放在插入按钮下面
                    { insert: ['image', 'audio', 'video', 'link', 'hr', 'br', 'code', 'formula', 'toc', 'table', 'drawIo'] },
                    'graph'
                ],
                // 定义侧边栏，默认为空
                sidebar: ['theme', 'mobilePreview', 'copy'],
                // 定义顶部右侧工具栏，默认为空
                // user_cola,2024年4月12日21:47:12,需要使用导出功能时,必须有两行字,才可以导出,我想了想,可能是因为
                toolbarRight: ['fullScreen', 'export'],
                // 定义选中文字时弹出的“悬浮工具栏”，默认为 ['bold', 'italic', 'underline', 'strikethrough', 'sub', 'sup', 'quote', '|', 'size', 'color']
                bubble: ['bold', 'italic', 'underline', 'strikethrough', 'sub', 'sup', 'ruby', '|', 'color', 'size',],
                // 定义光标出现在行首位置时出现的“提示工具栏”，默认为 ['h1', 'h2', 'h3', '|', 'checklist', 'quote', 'table', 'code']
                float: ['table', 'code', 'graph'],
            },
        });
    </script>
</body>

</html>
