### ISSUE TITLE
[Bug report]希望可以支持根据表格信息生成图表

### ISSUE THREAD

**Issue by hanruto** [Tencent/cherry-markdown#124]
文档的[ Syntax Feature 里的 Feature2 ](https://github.com/Tencent/cherry-markdown/blob/main/docs/features.md#feature-2classic-break-regular-break)有提到可以支持如下这种特殊的语法，但是我们在使用该feature的时候，并不能正常渲染出图表。

![wecom-temp-7bde142a3279c2b1012ac33aef98b355](https://user-images.githubusercontent.com/23400461/151538937-f20256e9-e564-46f1-b71d-8f76604cd469.png)

**Comment by hanye9895** [comment]
Amazing feature, did the official team support that?

**Comment by hanye9895** [comment]
If not, maybe I can help with it.

**Comment by lyngai** [comment]
目前的该语法功能未开源，在我们后续的版本计划中会开放该功能。
