### ISSUE TITLE
[Feature request]支持简单表格

### ISSUE THREAD

**Issue by hanruto** [Tencent/cherry-markdown#125]
希望可以支持双竖线这种语法，可以提高markdown表格的书写效率。
![image](https://user-images.githubusercontent.com/23400461/151540774-f44b234d-016f-481b-b7a4-78c123cbe98a.png)

**Comment by hanye9895** [comment]
It seems a none [gfm](https://github.github.com/gfm/) standard md Spec, but a really convenience usage.
Interesting~
I'll look into it.

**Comment by lyngai** [comment]
目前该语法功能未开源，在我们后续的版本计划中会开放该功能。
