### ISSUE TITLE
[Bug report]设置编辑器高度后,下拉框超出部分被遮挡

### ISSUE THREAD

**Issue by yangrunkang** [Tencent/cherry-markdown#128]
**Describe the bug**
设置编辑器高度后,下拉框超出部分被遮挡

**Screenshots**
![image](https://user-images.githubusercontent.com/46257933/152752633-0c805ce0-a5b9-433d-be2f-4d1ce65477fe.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 98.0.4758.80（正式版本） (x86_64)

**Comment by sunsonliu** [comment]
已修复~
