### ISSUE TITLE
Can't open demo in Safari

### ISSUE THREAD

**Issue by hanye9895** [Tencent/cherry-markdown#13]
Awesome markdown tool~ but when I open the demo page
<https://tencent.github.io/cherry-markdown/examples/index.html>
it comes blank page, with no error in console
Any idea deal with it?

**Comment by sunsonliu** [comment]
try it in the Chrome browser(it's ok in chrome for now), we will debug it tomorrow.

**Comment by lyngai** [comment]
Fixed in #17
