### ISSUE TITLE
[Feature request] 希望标题支持用户选择使用锚点/序号/纯标题

### ISSUE THREAD

**Issue by jrainlau** [Tencent/cherry-markdown#134]
目前对于 `# title` 的解析，默认会带一个锚点的 `<a>` 标签，虽然可以通过 CSS 的方式把它隐藏，但毕竟不够优雅。希望可以提供一个配置项，让用户决定是否需要锚点标签，或者标题序号等。

可以扩展成anchorStyle，提供三个选项 default autonumber none

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/releases/tag/v0.6.6
