### ISSUE TITLE
DEMO在edge浏览器下，源码和预览两边对不齐

### ISSUE THREAD

**Issue by nickeyfff** [Tencent/cherry-markdown#14]
![image](https://user-images.githubusercontent.com/1441999/140246277-46adb340-4675-4391-973d-283a06ff2fa9.png)

对不齐哦。

**Comment by sunsonliu** [comment]
收到，可能跟浏览器无关，我们定位下

**Comment by sunsonliu** [comment]
破案，是有些语法的行号计算逻辑有问题，最近有点忙，我先通过修改demo内容来规避这个bug吧（这个修改会在这周安排）。。行号计算逻辑的定位和修复会需要一个比较长的周期，请理解哈

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/tree/fix/fix-lineCount
还在修复。。计划是彻底修复这里的行号计算逻辑，还需要一些工作量
