### ISSUE TITLE
vue组件多次创建Cherry实例怎么办？

### ISSUE THREAD

**Issue by sunsonliu** [Tencent/cherry-markdown#140]
vue组件多次创建Cherry实例怎么办？
Cherry没有destroy()方法

_Originally posted by @power721 in https://github.com/Tencent/cherry-markdown/issues/70#issuecomment-1022870117_

**Comment by ufec** [comment]
我测试好像并没有，有代码实例吗？

**Comment by sunsonliu** [comment]
已提供destroy api
