### ISSUE TITLE
[Bug report]解析符合CommonMark规范，但是换行呈现的不对。

### ISSUE THREAD

**Issue by pengqian089** [Tencent/cherry-markdown#144]
**Describe the bug**

**To Reproduce**
1. 尝试在编辑器内换行，输入:
``` markdown
这是第一行\
这是第二行\
这是第三行
```
2. 查看预览，实际结果
``` html
这是第一行&lt;br&gt;
这是第二行&lt;br&gt;
这是第三行
```

**Expected behavior**
换行不应该是 `&lt;`br`&gt;`

**Screenshots**
![CherryEditorNewline](https://user-images.githubusercontent.com/13491546/154960852-02a0b375-559a-4965-9307-4ffb38dd0b2d.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 98.0

**Additional context**

**Comment by sunsonliu** [comment]
阿西吧，是转义符带来的bug，我们修复下哈

**Comment by sunsonliu** [comment]
特殊处理了下，已提交到dev
