### ISSUE TITLE
[Bug report] 上传图片后地址变为cherry-inner:开头

### ISSUE THREAD

**Issue by yangrunkang** [Tencent/cherry-markdown#147]
**Describe the bug**
编辑状态时,图片链接都正常;**但是**获取内容保存后进行展示的时候图片链接就变为cherry-inner:开头的了，导致图片显示不正常

**Screenshots**
![image](https://user-images.githubusercontent.com/46257933/155754113-e1b54257-cd66-430c-80c6-e6512d51f628.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Comment by lyngai** [comment]
方便提供最小能复现的文本吗

**Comment by yangrunkang** [comment]
new Cherry({
        id: 'vcr_editor',
        value: '',
        editor: {
            theme: 'default',
            defaultModel: _defaultModel,
            height: _height,
        },
        toolbars:{
            theme: 'light', // light or dark
            toolbar : ['bold', 'italic', 'strikethrough','color', 'header','size', 'list', 'quote',{
                insert: [
                    'image',
                    'link',
                    'hr',
                    'br',
                    'code',
                    'formula',
                    // 'toc',
                    'table',
                    // 'line-table',
                    // 'bar-table',
                    // 'pdf',
                    // 'word',
                ],
            }, 'graph', 'switchModel'],
            bubble : ['bold', 'italic', 'strikethrough', 'sub', 'sup',  'size'], // array or false
            float : ['h1', 'h2', 'h3',  'checklist', 'quote', 'quickTable', 'code'], // array or false
            customMenu: {
            },
        },
        fileUpload(file, callback) {

            let formData = new FormData();
            formData.append('file', file);
            $.ajax('/pic/uploadFile/editor', {
                method: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                xhr: function () {
                    myXhr = $.ajaxSettings.xhr();
                    if (myXhr.upload) { // check if upload property exists
                        $(".upload-progress-bar-div").show();
                        myXhr.upload.addEventListener('progress', function (e) {
                            let loaded = e.loaded;//已经上传大小情况
                            let tot = e.total;//附件总大小
                            let per = ((loaded / tot) * 100).toFixed(2);
                            $(".upload-progress-bar").attr('style', 'width:' + per + '%');
                        }, false); // for handling the progress of the upload
                    }
                    return myXhr;
                },
                success: function (res) {
                   if(respCodeOk(res)){
                       callback(res.data.data);
                       $(".upload-progress-bar").attr('style', 'width:0%');
                       $(".upload-progress-bar-div").hide();
                   }else{
                       uploadFailed()
                   }
                },

                error: function (e) {
                    uploadFailed()
                }
            });
        },
        callback: {
            /** 编辑器内容改变并完成渲染后触发 */
            afterChange: function(){
                // console.log("内容变更")
            },
            /** 编辑器完成初次渲染后触发 */
            afterInit: function(){
                $("#comment_btn_group").show();
                $("#comment_loading").hide();
            },
        }
    });


> https://github.com/yangrunkang/upupor/blob/main/upupor-web/src/main/resources/static/js/cv.js

**Comment by lyngai** [comment]
问题会在 #151 中修复

**Comment by yangrunkang** [comment]
好的,辛苦了
