### ISSUE TITLE
bash的代码块反斜杠会自动变成两个

### ISSUE THREAD

**Issue by Apeng7364** [Tencent/cherry-markdown#15]
如图
![image](https://user-images.githubusercontent.com/31104239/140251799-5c2f2a0f-02af-4dd1-b160-e226641b7e49.png)

**Comment by sunsonliu** [comment]
收到，麻烦 @jiawei686  帮忙定位下哈

**Comment by jiawei686** [comment]
感谢反馈！经过定位发现prism在渲染代码块时，部分语法中如bash、shell、vb...斜杠\被当作关键字进行渲染，从而\的计算中间产物\\不能正常通过dom转回\，我们已在 #16 中对其进行修复。
