### ISSUE TITLE
[Bug report]选中多行文本后选择有序列表,序号未递增,都是1

### ISSUE THREAD

**Issue by yangrunkang** [Tencent/cherry-markdown#160]
**Describe the bug**
选中多行文本后选择有序列表,序号未递增,都是1，

**To Reproduce**
1. 在编辑器选中多行文本
2. 点击列表按钮，选中有序列表
3. 查看结果

**Expected behavior**
期望是多行选中后，插入有序列表，序号是递增的，这样就不用人为调整

**Screenshots**
![image](https://user-images.githubusercontent.com/46257933/156781433-fedb5288-b827-4053-9c21-a5aafb52358b.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 版本 98.0.4758.109（正式版本） (x86_64)

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/157030426-7694fb71-5596-4f20-828f-102fbf5dd52e.png)

收到，这里我们优化下，不过即便都是1，也不影响正常渲染哈

**Comment by yangrunkang** [comment]
嗯嗯，感谢，辛苦了 ❤️

**Comment by sunsonliu** [comment]
已提交到dev
