### ISSUE TITLE
[Bug report] 在某些场景下不能正确识别 --- 语法

### ISSUE THREAD

**Issue by hanruto** [Tencent/cherry-markdown#166]
使用如下语法的时候不能正确识别 --- 语法

```
111

---

    code

```
![wecom-temp-2849c758339420d041731ad5f51cea70](https://user-images.githubusercontent.com/23400461/158591717-79de5de6-797d-4d18-b4cc-637106294fd3.png)

并且在下边这么写的时候会识别出一些奇怪的东西
```
    111

---

    code
```
![wecom-temp-e60ee6cda8177ffb2c5b85cf6436c5cd](https://user-images.githubusercontent.com/23400461/158591685-e6068b8d-e0ec-41b9-9a92-ff0e3bd7849a.png)

**Comment by joriewong** [comment]
![image](https://user-images.githubusercontent.com/11408040/165743936-348e38ff-bb92-48fe-8497-060dacbca23e.png)

**Comment by joriewong** [comment]
![image](https://user-images.githubusercontent.com/11408040/165744083-6a898e16-f773-4f7d-9760-1e6ffde5ec60.png)
