### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by Young6118** [Tencent/cherry-markdown#169]
**quote inner list**

When I insert a quote into a list, the quote will break the whole list and change the subsequent items of the list into the contents of the quote block.
![mmexport1647583227329.png](https://user-images.githubusercontent.com/16507306/158946578-7b813060-5020-4578-9e9c-ac1960bff893.png)

This is not what I want.

** I want this feature to be like this **
This is the source code:
```
+ 111
    + 22
		  > 22 quote
    + 33
```

This is the preview effect:
![mmexport1647583229709.png](https://user-images.githubusercontent.com/16507306/158947165-e441248b-1285-4670-9bc6-c75cf76cbbc8.png)

Handle quote in the list just as GitHub's markdown editor does.

**Comment by lyngai** [comment]
Duplicate #165
