### ISSUE TITLE
[Bug report]很难选中一段文字

### ISSUE THREAD

**Issue by Ya-chunJen** [Tencent/cherry-markdown#174]
很难选中一段编辑状态的文字，选择一段文字闪一下就会取消选中。

**Comment by lyngai** [comment]
麻烦提供更详细一些的信息，包括使用的组件版本、浏览器版本、系统版本、操作截图等信息。

**Comment by sunsonliu** [comment]
因为一直没有提供更详细信息，我们也没有重现出来，故关闭该issue
