### ISSUE TITLE
[Bug report]Tab和空格在保存时都丢失

### ISSUE THREAD

**Issue by yangrunkang** [Tencent/cherry-markdown#177]
**Describe the bug**
Tab和空格在保存时都丢失

**Screenshots**
![image](https://user-images.githubusercontent.com/46257933/160293118-7b5f13d6-af86-4fb3-abf2-8949f6f44ff2.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Comment by lyngai** [comment]
是通过哪个 API 操作的呢？通过 `cherry.getValue()` 取到的值是正常的，没有丢失 `\t` 和 空格。

**Comment by yangrunkang** [comment]
把cherry赋值到wIndow的editor属性上
```
window.editor = new Cherry(...)
```


这个是获取数据
```
/**
 * 获取编辑器数据
 */
function getEditorData() {
    return window.editor.engine.makeHtml(window.editor.getMarkdown())
}

/**
 * 获取编辑器数据
 */
function getEditorDataMd() {
    return window.editor.getMarkdown();
}
```


> 源码地址: https://github.com/yangrunkang/upupor/blob/93303435efa5349ae14e57ac760f375d12aa4ab5/upupor-web/src/main/resources/static/js/cv.js#L224

**Comment by lyngai** [comment]
在 https://tencent.github.io/cherry-markdown/examples/index.html 上调试没有复现这个问题

<img width="662" alt="image" src="https://user-images.githubusercontent.com/22373754/160523723-c7e780a7-4788-43c6-9ab6-c9dffcb0bcd5.png">

**Comment by yangrunkang** [comment]
见图
![image](https://user-images.githubusercontent.com/46257933/160533652-c9011300-bc1d-4d6f-93a0-0137177c51e8.png)

**Comment by lyngai** [comment]
渲染的结果保留了 `\t` 和 空格，如有样式的需求可以自行设置样式为 `white-space: pre` 解决。空白字符没展示出来跟浏览器 `p` 标签的默认样式 `white-space: normal` 相关。

---

另，根据 commonmark 规范，行首的空白字符理应被忽略。

FYI: <https://spec.commonmark.org/0.30/#example-221>
<img width="868" alt="image" src="https://user-images.githubusercontent.com/22373754/160538103-14ce3733-0f6f-48cb-bd7d-2f563110520a.png">

**Comment by yangrunkang** [comment]
👌🏻 ，感谢普及相关commonmark规范，谢谢~
