### ISSUE TITLE
撤销问题

### ISSUE THREAD

**Issue by Gestorz** [Tencent/cherry-markdown#181]
使用setValue替换设置值后，撤销都会滚动到顶部，能支持回到上一个光标节点吗

**Comment by sunsonliu** [comment]
应该可以搞，我们跟进下

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/167985138-1e0e9340-eb11-4437-9df4-b71661c6a776.png)
https://tencent.github.io/cherry-markdown/examples/api.html

setValue传入第二个参数（true）时，会强制保持光标，这时候undo、redo就能保证自动滚动到光标处了
自动滚动到光标处的代码已提交到dev
