### ISSUE TITLE
[Feature request]希望调整文本颜色和加粗的时候，没有空格也能正常识别

### ISSUE THREAD

**Issue by hanruto** [Tencent/cherry-markdown#182]
如下所示，对文本添加颜色的时候，需要在颜色后边加个空格才能生效
```
please use HTTP!!#f5222d S!! 
please use HTTP!!#f5222dS!!
```
![wecom-temp-225bf2d4eecd2a160ef436776f4c8051](https://user-images.githubusercontent.com/23400461/160856117-452489a4-6498-4c61-8cb9-6bd39db702cf.png)

对文本进行加粗的时候，也需要在标识符前边加一个空格
```
please use HTTP __S__
please use HTTP__S__
```
![wecom-temp-8f78c5b47e5d274340de890e37976821](https://user-images.githubusercontent.com/23400461/160856407-28e6dad9-6b32-4b37-82ac-e91d909c39e1.png)

这些额外的空格会导致书写的时候有些别扭，不那么自然，希望可以进行优化，在没有空格的时候也能正常识别

**Comment by sunsonliu** [comment]
- ![image](https://user-images.githubusercontent.com/998441/161733669-34ba487f-5247-4f90-b8c9-37d11b503a53.png)
这里强制空格主要是为了防止**误触发**

- ![image](https://user-images.githubusercontent.com/998441/161732819-04d97ee3-f2bf-45fd-8b72-36279e71d1ca.png)
关于用下横线加粗/斜体需要空格的问题，强制空格主要是为了防止**误触发**，建议使用星号（*）来规避空格问题。

目前来看这两个语法的空格不会考虑去掉哈，请理解~
