### ISSUE TITLE
[Bug report]在表格中插入的超链接描述如果有|，会被解析成新列

### ISSUE THREAD

**Issue by yangrunkang** [Tencent/cherry-markdown#183]
**Describe the bug**
在表格中插入的超链接描述如果有|，会被解析成新列

**To Reproduce**
见截图

**Expected behavior**
期望在表格中插入的超链接描述中如果有|,不会被解析成新列

**Screenshots**
![image](https://user-images.githubusercontent.com/46257933/160899511-08f0db88-b6d2-4d28-a9d6-06beeec1264f.png)
![image](https://user-images.githubusercontent.com/46257933/160899576-e870bf3f-1eed-48dd-a158-0a1c1d6f7600.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by lyngai** [comment]
对比了一下 GitHub 的 markdown 也存在这个问题。。可以用 `\|` 去转义链接中的 `|` 规避哈。

----

```markdown
| LeftAlignedCol | CenterAlignedCol | RightAlignedCol |
| :--- | :---: | ---: |
| [sample|Text](http://www.google.com) | sampleText | sampleText |
| **left**Text | centered Text | *right*Text |
```

| LeftAlignedCol | CenterAlignedCol | RightAlignedCol |
| :--- | :---: | ---: |
| [sample|Text](http://www.google.com) | sampleText | sampleText |
| **left**Text | centered Text | *right*Text |

---

```markdown
| LeftAlignedCol | CenterAlignedCol | RightAlignedCol |
| :--- | :---: | ---: |
| [sample\|Text](http://www.google.com) | sampleText | sampleText |
| **left**Text | centered Text | *right*Text |
```

| LeftAlignedCol | CenterAlignedCol | RightAlignedCol |
| :--- | :---: | ---: |
| [sample\|Text](http://www.google.com) | sampleText | sampleText |
| **left**Text | centered Text | *right*Text |

**Comment by lyngai** [comment]
> 对比了一下 GitHub 的 markdown 也存在这个问题。。可以用 `\|` 去转义链接中的 `|` 规避哈。

表格语法是在 github flavored markdown 中定义的，文档中有说明单元格中出现的管道字符 `|` 需要通过 `\|` 去转义。

https://github.github.com/gfm/#example-200

<img width="861" alt="image" src="https://user-images.githubusercontent.com/22373754/160961547-0c6669fd-e358-4c63-8f37-86344f01110c.png">

**Comment by yangrunkang** [comment]
好的，明白了，下次我先用Github的编辑器试试再提issue
