### ISSUE TITLE
[Feature request]希望支持图片点击弹出浮层放大显示的功能。

### ISSUE THREAD

**Issue by ysbcc** [Tencent/cherry-markdown#199]
一些复杂图片在文章内部无法看清楚，需要点击放大查看。很多富文本类场景都有这种交互。
另外，考虑到可能存在一些小图，比如小的头像、icon之类的。这种图片也许不需要点击放大，可以在协议中预留开关能力，用户手动关闭点击放大功能。或者考虑根据图片的大小来自动添加点击放大事件。

**Comment by sunsonliu** [comment]
## 1
似乎不能这么简单实现，一般弹出浮层的图片是图片的原始尺寸地址，而在文章里的图片是压缩后的图片地址，否则强行放大图片会出现图片模糊的情况。

## 2
同时在双栏编辑模式下点击查看原图和[点击编辑图片尺寸](https://tencent.github.io/cherry-markdown/examples/img.html)的交互是冲突的。

## 综上
我们可能需要实现在[**只读模式**](https://tencent.github.io/cherry-markdown/examples/preview_only.html)下的点击图片的回调机制，由业务侧实现相关后续功能。

**Comment by meystack** [comment]
> ## 1
> 似乎不能这么简单实现，一般弹出浮层的图片是图片的原始尺寸地址，而在文章里的图片是压缩后的图片地址，否则强行放大图片会出现图片模糊的情况。
> 
> ## 2
> 同时在双栏编辑模式下点击查看原图和[点击编辑图片尺寸](https://tencent.github.io/cherry-markdown/examples/img.html)的交互是冲突的。
> 
> ## 综上
> 我们可能需要实现在[**只读模式**](https://tencent.github.io/cherry-markdown/examples/preview_only.html)下的点击图片的回调机制，由业务侧实现相关后续功能。

当前的toolbar的功能，比如上传图片，不支持直接写在toolbar上显示，只能在inster里面显示！
为什么一开始不支持上传图片在最外层显示呢？这样做的考虑是啥！ 期望可以支持下！！

**Comment by sunsonliu** [comment]
哦哦，倒是可以放到toolbar上，我回来弄下。

没有放在toolbar的原因主要有两点：
1. Cherry提供了拖拽上传文件的能力，而且支持批量拖拽纯文本、图片、其他类型文件的功能，相比一张张上传，这个拖拽功能更方便一些
2. Cherry同时也提供了Ctrl+V 粘贴上传图片的能力，截图-->Ctrl+V粘贴到编辑器里也是比较方便的

------

不过从组件层面来看，insert里的所有工具都应该可以放到toolbar上，同理toolbar上所有的工具都应该可以放在insert里（当然除了insert），是时候改造下这里的机制了

**Comment by meystack** [comment]
好的，改造完，我直接换个新版用，拖拽和粘贴上传，爆赞！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月12日(星期四) 晚上6:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/cherry-markdown] [Feature request]希望支持图片点击弹出浮层放大显示的功能。 (Issue #199)





 
哦哦，倒是可以放到toolbar上，我回来弄下。
 
没有放在toolbar的原因主要有两点：
  
Cherry提供了拖拽上传文件的能力，而且支持批量拖拽纯文本、图片、其他类型文件的功能，相比一张张上传，这个拖拽功能更方便一些
 
Cherry同时也提供了Ctrl+V 粘贴上传图片的能力，截图--&gt;Ctrl+V粘贴到编辑器里也是比较方便的
  
 
不过从组件层面来看，insert里的所有工具都应该可以放到toolbar上，同理toolbar上所有的工具都应该可以放在insert里（当然除了insert），是时候改造下这里的机制了

**Comment by yangrunkang** [comment]
> 一些复杂图片在文章内部无法看清楚，需要点击放大查看。很多富文本类场景都有这种交互。 另外，考虑到可能存在一些小图，比如小的头像、icon之类的。这种图片也许不需要点击放大，可以在协议中预留开关能力，用户手动关闭点击放大功能。或者考虑根据图片的大小来自动添加点击放大事件。

可以集成https://github.com/fengyuanchen/viewerjs

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/pull/255

**Comment by sunsonliu** [comment]
> 好的，改造完，我直接换个新版用，拖拽和粘贴上传，爆赞！


https://github.com/Tencent/cherry-markdown/commit/95a3e09b36dee371067e9ab89298f0cd47a464cd
先把insert里面的二级菜单放出来了（目前在dev分支），insert可以把任意菜单放进二级菜单的功能还没实现，后面有空再搞吧
