### ISSUE TITLE
自定义工具栏用不了

### ISSUE THREAD

**Issue by fanggeyishui** [Tencent/cherry-markdown#202]
跟着例程想自定义工具栏，发现没用。有没有可以用的示例给一个

**Comment by humyfred** [comment]
你好，自定义工具栏文档github欠缺，稍后补上

**Comment by KingOneYan** [comment]
> 

请问大概多久出呢

**Comment by humyfred** [comment]
另外还有默认配置作为示例，可以自定义工具栏：https://github.com/Tencent/cherry-markdown#default-configuration
