### ISSUE TITLE
[Feature request]直接使用el初始化编辑器

### ISSUE THREAD

**Issue by j4587698** [Tencent/cherry-markdown#203]
**Is your feature request related to a problem? Please describe.**
在动态生成的div中加载markdown编辑器。不太好固定设置一个id，可以拿到节点的其他选择器。

** What does the proposed API look like**
```
new Cherry({
      el: document.querySelector('#markdown-container'), //类似的选择器或者其他`ref`
      value: '# welcome to cherry editor!',
    });
```

**Additional context**

**Comment by sunsonliu** [comment]
done~
