### ISSUE TITLE
[Feature request]添加事件

### ISSUE THREAD

**Issue by j4587698** [Tencent/cherry-markdown#204]
**Is your feature request related to a problem? Please describe.**
需要一些常用事件进行处理，比如change,blur,load等。

** What does the proposed API look like**
cherryInstance.on('change', function(){})

**Additional context**

**Comment by sunsonliu** [comment]
## change 和init（load）是有事件的哈
![image](https://user-images.githubusercontent.com/998441/167610088-d64aa066-bc82-4e56-9625-753df308380a.png)
![image](https://user-images.githubusercontent.com/998441/167610251-b788fd95-952e-40d7-ac8c-08d3f5dc41ac.png)


## blur等还没有暴露事件，可以先用codemirror的事件：
```
cherry.getCodeMirror().on('blur', function(){console.log('blur')})
```
