### ISSUE TITLE
[Bug report] 不同列表累加了，无序和有序冲突，不应该同时出现

### ISSUE THREAD

**Issue by yangrunkang** [Tencent/cherry-markdown#206]
**Describe the bug**
不同列表累加了，无序和有序冲突，不应该同时出现. Github的编辑器没有这个问题

**Screenshots**
![image](https://user-images.githubusercontent.com/46257933/166087111-854ac0ad-f5aa-4839-a6e9-4d30eebe0863.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Browser Chrome 版本 100.0.4896.127（正式版本） (x86_64)

**Comment by sunsonliu** [comment]
已经提交到dev分支
