### ISSUE TITLE
[Bug report]指定编辑器高度后,预览内容时部分内容被遮挡(指定了400px的高度)

### ISSUE THREAD

**Issue by yangrunkang** [Tencent/cherry-markdown#207]
**Describe the bug**
指定编辑器高度后,预览内容时部分内容被遮挡(指定了400px的高度)

**Screenshots**
![image](https://user-images.githubusercontent.com/46257933/166106872-e812344d-ee50-4b84-8c5d-ce0ded11dffb.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Comment by sunsonliu** [comment]
收到，我们看下为啥高度有毛病

**Comment by sunsonliu** [comment]
已提交到dev
