### ISSUE TITLE
[Bug report] node 适配错误

### ISSUE THREAD

**Issue by lxzlx624** [Tencent/cherry-markdown#209]
0.5.x版本node下可用，0.6.x、0.7 node下都报错
<img width="793" alt="1652174285881" src="https://user-images.githubusercontent.com/23074885/167594817-6a8f4b21-7793-488f-86f7-cc83f2cadd99.png">

**Comment by lyngai** [comment]
`0.6` `0.7` 版本请使用 后缀为 `common.js` 的产物
