### ISSUE TITLE
高度有问题，设置高度后父元素是配置了高度，但是无效

### ISSUE THREAD

**Issue by meystack** [Tencent/cherry-markdown#210]
高度有问题，设置高度后父元素是配置了高度，但是无效

**Comment by meystack** [comment]
采用回调的方式解决了，另外在初始化完成后，会自动定位到编辑器本身，比如打开一篇文章
自动滚动到编辑器的位置，没必要，很不友好。。虽然改代码解决了，但是我还以为是我自己的代码干扰的，
导致我找了半个小时的BUG。。。

**Comment by meystack** [comment]
还有一个问题，默认渲染后，需要点击编辑框的固定的位置才可以键入内容，
应该是在只有编辑模式下，点击任何的区域，可以直接键入内容，如果是双侧的话，
点击左侧的再去把焦点设置上就行了！！！

**Comment by lyngai** [comment]
> 采用回调的方式解决了，另外在初始化完成后，会自动定位到编辑器本身，比如打开一篇文章 自动滚动到编辑器的位置，没必要，很不友好。。虽然改代码解决了，但是我还以为是我自己的代码干扰的， 导致我找了半个小时的BUG。。。

autofocus 的问题我们最近也收到了不少类似的反馈，会评估一下是否在后面的版本默认置为 false。

**Comment by lyngai** [comment]
> 还有一个问题，默认渲染后，需要点击编辑框的固定的位置才可以键入内容， 应该是在只有编辑模式下，点击任何的区域，可以直接键入内容，如果是双侧的话， 点击左侧的再去把焦点设置上就行了！！！

看描述应该是设置高度的时候内部的 codemirror 没刷新高度导致的，可以对照一下样例看看问题。

demo: <https://tencent.github.io/cherry-markdown/examples/multiple.html>
源码: <https://github.com/Tencent/cherry-markdown/blob/main/examples/scripts/multiple-demo.js>

**Comment by meystack** [comment]
> > 采用回调的方式解决了，另外在初始化完成后，会自动定位到编辑器本身，比如打开一篇文章 自动滚动到编辑器的位置，没必要，很不友好。。虽然改代码解决了，但是我还以为是我自己的代码干扰的， 导致我找了半个小时的BUG。。。
> 
> autofocus 的问题我们最近也收到了不少类似的反馈，会评估一下是否在后面的版本默认置为 false。

好的感谢，我再查看下我的配置是否有误！

**Comment by sunsonliu** [comment]
## 可以用下面的方式设置`autofocus`哈：
<img width="433" alt="16520825349836" src="https://user-images.githubusercontent.com/998441/167623014-03c5acdf-674f-4512-ae9e-9f34bb6982b6.png">

**Comment by meystack** [comment]
解决焦点的问题了；
原因是我设置高度的时候，没有改变这里的
            editor: {
                height: height, # 这句话原先没写，
               ## 是因为写了高度没效果，是因为CSS有个min-height 400
                defaultModel: 'editOnly',
            },
所以我就回调解决；
                afterInit: function(){
                    /**
                     * 初始化回调
                     * 这里写了回调，上面的去掉了，就。。。。
                     */
                    $('#'+_id).find('.cherry').css('min-height', height);
                },
感谢各位大佬的解答！

**Comment by lyngai** [comment]
> 解决焦点的问题了； 原因是我设置高度的时候，没有改变这里的 editor: { height: height, # 这句话原先没写， ## 是因为写了高度没效果，是因为CSS有个min-height 400 defaultModel: 'editOnly', }, 所以我就回调解决； afterInit: function(){ /** * 初始化回调 * 这里写了回调，上面的去掉了，就。。。。 */ $('#'+_id).find('.cherry').css('min-height', height); }, 感谢各位大佬的解答！

在您的场景下，最小高度设置为了多少呢？ `400` 是我们默认比较推荐的高度，所以才会有这个样式限制。

**Comment by meystack** [comment]
我的评论默认是200高度，后端写文档就无所谓了，现在是直接查询渲染那个元素的设置data-height就行；
但是这个最小高度，没太大必要把，如果要用在评论框上就太高了，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月10日(星期二) 晚上8:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/cherry-markdown] 高度有问题，设置高度后父元素是配置了高度，但是无效 (Issue #210)





  
解决焦点的问题了； 原因是我设置高度的时候，没有改变这里的 editor: { height: height, # 这句话原先没写， ## 是因为写了高度没效果，是因为CSS有个min-height 400 defaultModel: 'editOnly', }, 所以我就回调解决； afterInit: function(){ /** * 初始化回调 * 这里写了回调，上面的去掉了，就。。。。 */ $('#'+_id).find('.cherry').css('min-height', height); }, 感谢各位大佬的解答！
  
在您的场景下，最小高度设置为了多少呢？ 400 是我们默认比较推荐的高度，所以才会有这个样式限制。

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/commit/58a090b390106d0d16f9155b1cd31aac00ac45b3

我已经把最小高度改成100px了 @lyngai @meystack

**Comment by meystack** [comment]
还有一个问题，插入的
                    {
                        insert: ['image','code',  'table','link', 'hr'],
                    },
这里的配置不支持直接放在toolbar上，只能在 insert里，对于插入图片来说，直接放在toolbar上还是比较方便的，
