### ISSUE TITLE
[Feature request]Mac 有一款软件叫做SnippetsLab 在cherry的客户端版是不是有望支持他的代码碎片管理功能

### ISSUE THREAD

**Issue by jialong473649383** [Tencent/cherry-markdown#214]
Mac 有一款软件叫做SnippetsLab 在cherry的客户端版是不是有望支持他的代码碎片管理功能

**Comment by sunsonliu** [comment]
是希望在SnippetsLab 里支持Cherry编辑器，还是在Cherry客户端里接入SnippetsLab工具？
前者可能需要SnippetsLab 团队来实现，如果楼主了解这个团队，欢迎牵线。后者我们在进一步实现客户端版时会进行考虑，不过从“性价比”来看，优先实现vscode插件可能收益会更大一些~
