### ISSUE TITLE
`<details>` render weird when with no space in a new line

### ISSUE THREAD

**Issue by hanye9895** [Tencent/cherry-markdown#23]
```
<details>
	detail11
	<summary>
		summ1
	</summary>
	detail22

	detail33
</details>
```
<img width="751" alt="Screen Shot 2021-11-15 at 9 44 35 PM" src="https://user-images.githubusercontent.com/68373171/141792223-298d8080-d6cb-493a-9e48-4b1c316c4c7b.png">

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/141884333-0a3c3bc9-e405-4fc8-afdf-147062778cdd.png)

This is caused by a feature witch transform paragraph(with new line) to '<p></p>'. We plan to develop a plugin(use a exclusive grammar) to support '<details>'

**Comment by hanye9895** [comment]
Thanks, plugin would be awesome, great job~

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/223070729-7903bd79-3f7c-4008-88a7-cd5efe1d0995.png)
we have publish this plugin~
