### ISSUE TITLE
希望支持注音符号语法

### ISSUE THREAD

**Issue by sunsonliu** [Tencent/cherry-markdown#241]
![image](https://user-images.githubusercontent.com/998441/172085893-7fff8c7b-59e1-48d7-97c1-2e2a19cc663d.png)

```
Markdown Nice 这么好用，简直是{喜大普奔|hē hē hē hē}呀！
```

在https://markdown.com.cn/editor/ 里看到一个好玩的语法，希望能支持

**Comment by Mantyke** [comment]
同希望，这个在记录语言学习笔记时非常有用

**Comment by object-kaz** [comment]
这个应该要加个Hook

**Comment by sunsonliu** [comment]
> 这个应该要加个Hook
![pinyin](https://user-images.githubusercontent.com/998441/179348670-83abad5b-c299-4bf4-97f0-753288b9b3cd.gif)

哈哈，在你的基础上补上了toolbar https://github.com/Tencent/cherry-markdown/pull/272
