### ISSUE TITLE
[Bug report]previewOnly模式下宽度没有占满父容器

### ISSUE THREAD

**Issue by lshunran** [Tencent/cherry-markdown#246]
**Describe the bug**
在使用defaultModel: 'previewOnly'时，看到源码里固定了一个内联样式width: 50%，导致preview区域宽度恒为父容器的一半

**To Reproduce**
直接访问demo即可复现：https://tencent.github.io/cherry-markdown/examples/preview_only.html
![image](https://user-images.githubusercontent.com/12935577/172338017-915b842e-dd86-4b13-8370-1b18692738bd.png)

**Expected behavior**
preview区域的宽度应于父容器宽度保持一致

**Screenshots**
[image](https://user-images.githubusercontent.com/12935577/172338017-915b842e-dd86-4b13-8370-1b18692738bd.png)

**Environment (please complete the following information):**
 - Version 0.7.3

**Comment by humyfred** [comment]
收到，这两天会更新问题

**Comment by sunsonliu** [comment]
已修复，是 9f227e1058b9a5c5447abf3d17ca8678ea56a900 这个提交引入的问题，已回滚
