### ISSUE TITLE
[Bug report] 构建报错

### ISSUE THREAD

**Issue by yangrunkang** [Tencent/cherry-markdown#247]
![image](https://user-images.githubusercontent.com/46257933/172473292-c8808f58-0a8b-439d-8556-420a8cddff64.png)

**Comment by lyngai** [comment]
工作区代码风格问题，编辑器配置 eslint `autoFixOnSave` 或命令行执行 `yarn lint:fix`

**Comment by yangrunkang** [comment]
yarn lint:fix

**Comment by yangrunkang** [comment]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/46257933/172527534-0d8cf565-d3b3-4e0c-a6bc-d273eec17cfd.png">
为什么一直停在这里停着? 我是直接在命令行里面构建的

**Comment by lyngai** [comment]
等待一段时间。全量 eslint 会慢。

**Comment by yangrunkang** [comment]
> 工作区代码风格问题，编辑器配置 eslint `autoFixOnSave` 或命令行执行 `yarn lint:fix`

我没有使用编辑器构建.....我是在命令行里构建的，这个在哪里设置呢

**Comment by lyngai** [comment]
安装依赖使用的是 yarn 还是 npm 呢？致命的问题是 echarts 依赖的类型检测报错。

**Comment by yangrunkang** [comment]
npm

**Comment by yangrunkang** [comment]
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/46257933/172786199-998e62c1-d564-482c-85fe-142c71c640c7.png">

```
rm -rf node_modules/
yarn install
yarn build
```
使用yarn还是有问题

**Comment by lyngai** [comment]
尝试一下 `yarn upgrade @types/echarts@4.6.0 -E` 再运行 build 呢。

**Comment by yangrunkang** [comment]
处理了，还是不行呢

**Comment by lyngai** [comment]
https://github.com/upupor/cherry-markdown/blame/main/yarn.lock#L1720-L1723 看起来没有处理成功哈。建议将官方仓库的yarn.lock 重新拷贝一份，重建。

**Comment by yangrunkang** [comment]
已经可以了,merge最新的版本,构建成功了,感谢
