### ISSUE TITLE
some straight line with space code seems not that straight

### ISSUE THREAD

**Issue by hanye9895** [Tencent/cherry-markdown#26]
```
      ┏---r1----┓                ┏--------r3---------┓     ┏---r5----┓   
      ┃         ┃  ┏--------r2---┃-----┓      ┏---r4----┓  ┃         ┃   
▶─────╋──w██████┃██┃███x─────────╋─y███┃██████┃███z──╋──╋──╋─────────╋──◀
      ┃         ┃  ┃             ┃     ┃      ┃      ┃  ┃  ┃         ┃   
      A---------B  ┃             E------------┃------F  ┃  I---------J   
                   C-------------------D      G---------H                

```
<img width="1664" alt="Screen Shot 2021-11-16 at 8 03 20 PM" src="https://user-images.githubusercontent.com/68373171/141982456-45ed50fa-7a2e-4d48-aa36-2b9c4de62499.png">
<img width="869" alt="Screen Shot 2021-11-16 at 8 03 39 PM" src="https://user-images.githubusercontent.com/68373171/141982463-26622960-694d-4de3-81fa-339fff679a4f.png">

Maybe word-spacing issue?

**Comment by sunsonliu** [comment]
emm...Looks like a font problem，It will be ok after we offer 'change theme' function.

**Comment by hanye9895** [comment]
Seems override font style will bypass the issue,  so I close this.
