### ISSUE TITLE
希望加粗功能可以改进

### ISSUE THREAD

**Issue by stillcalm** [Tencent/cherry-markdown#261]
在没有选中任何内容的情况下
加粗能匹配到附近文字
而不是这样
![image](https://user-images.githubusercontent.com/77736086/177235206-58fa7dce-ccef-4877-9df4-99535b9fff52.png)

**Comment by lyngai** [comment]
感谢建议，匹配到**附近**，这个概念非常模糊。**附近**指的是光标前面还是后面呢？这个是无法预测的。

----

目前可以优化的点是触发加粗后，选中默认的占位文本。

**Comment by stillcalm** [comment]
好的，谢谢解答。

**Comment by sunsonliu** [comment]
已提交到dev分支，做了以下优化：
在`没有选中内容`的情况下
- 点击加粗、斜体、上下标、字号、颜色等按钮时，会尝试选中光标所在位置附近的单词
- 点击标题、列表、引用按钮时，会选中光标所在行

标题切换优化：
有选中内容时点击标题按钮，如果所选内容里包含标题语法，则判断当前标题级别是否符合目标标题级别，如果符合，则清除标题语法，否则将当前标题级别改成目标级别。
