### ISSUE TITLE
希望能支持给图片添加边框

### ISSUE THREAD

**Issue by dmzl** [Tencent/cherry-markdown#262]

**Comment by sunsonliu** [comment]
收到，打算增加两个属性：
- 边框 ![img #border](url)
- 阴影 ![img #shadow](url)

**Comment by object-kaz** [comment]
新增的两个属性和 center|right|left|float-right|float-left 这些属性是互斥（只能填一个）还是可以共存 `![img #border#left](url)`

**Comment by sunsonliu** [comment]
> 新增的两个属性和 center|right|left|float-right|float-left 这些属性是互斥（只能填一个）还是可以共存 `![img #border#left](url)`

共存的，
- `![img #100px#200px#right#border#shadow#radius](url)`  
- `![img #100px#right#border#200px#shadow#radius](url)` 
- `![img #30%#right#border#auto#shadow#radius](url)`

**Comment by sunsonliu** [comment]
已合到dev分支，语法+效果如下图：
![image](https://user-images.githubusercontent.com/998441/178137950-f26a8fa0-3c1b-4cc4-a1df-f2f40040d339.png)
