### ISSUE TITLE
[Feature request] Focus after inserting new syntax

### ISSUE THREAD

**Issue by StLeoX** [Tencent/cherry-markdown#268]
## 插入新语法后的聚焦
例如插入 `bold`, `image`, `link` 等 syntax 后, 编辑器应当聚焦于\* \*, \[ \] 内的内容信息, 而不是将光标置于行尾.

**Comment by sunsonliu** [comment]
有道理，可以优化成：当点击按钮前有选中内容时，插入后的内容依然处于选中状态；当点击按钮前没有选中内容时，插入后光标处在插入内容的后边

**Comment by StLeoX** [comment]
我觉得最好是\[  \]内的内容处于选中状态, 比如以上的 "超链接", 再比如插入图片后的 "enter image description here", 然后就可以直接编辑内容了. 

> 还有就是为什么这个体验版和 Tencent iWiki 里面的cherry markdown的行为不一样, 是版本不同吗?

**Comment by sunsonliu** [comment]
![选中效果](https://user-images.githubusercontent.com/998441/178423148-aa3197b7-2676-4b46-a72c-d01b9850067c.gif)

大概明白你的意思啦，不过目前有些语法会选中整个语法部门，是因为想实现快速切换的效果（比如加粗、斜体、有序无序列表、标题等）。。。

不过像插入超链接、插入图片这类切换不频繁语法的选中效果的确可以再优化下~

cherry今天早上刚发了个新版，iwiki应该还没有那么快更新，不过放心，他们会更新的，有个给图片加边框效果的新特性就是iwiki的某个用户提的

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/issues/280
解决这个Issue的时候一起解决了，在dev分支可体验，下图是效果：
![toolbar优化后效果](https://user-images.githubusercontent.com/998441/184784668-390a81d3-327b-4ae8-bb78-c4cdb0d9f874.gif)
