### ISSUE TITLE
preview could not match source code when contains long checklist

### ISSUE THREAD

**Issue by Young6118** [Tencent/cherry-markdown#27]
![wecom-temp-0c55dd7aa9364f3968684b5a94e3d9b8](https://user-images.githubusercontent.com/16507306/141985438-6f0d6978-66d6-4d5a-a8bb-225f72a95da1.png)

source code: https://github.com/lexrus/LeetCode.swift/blob/swift4/README.md

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/tree/fix/fix-lineCount
we are working on it ~
