### ISSUE TITLE
<details> 标签渲染问题

### ISSUE THREAD

**Issue by lycoris-xmin** [Tencent/cherry-markdown#273]
编辑器中的代码如下
![image](https://user-images.githubusercontent.com/43264181/179439122-2cf6abba-e326-47be-ad99-b674a60a2bde.png)

而渲染后的代码如下
![image](https://user-images.githubusercontent.com/43264181/179439266-18adf29a-7d42-46ce-8fb6-5b34df4d4deb.png)

我不知道这个是渲染问题，还是这个编辑器不允许这么做，editormd插件是支持的，但是他渲染的时候会被渲染成行内代码，而不是代码块，目前只有typecho上的md插件是渲染正常的， 不知道这个是否能解决，因为我是后端，刚好只是想写一个自己的博客系统，所以用到了这个插件，前端代码拔的不太行，目前暂时解决不了，不知道有没有大神教教我

**Comment by lyngai** [comment]
看起来是 BUG 我们定位一下问题。

**Comment by lycoris-xmin** [comment]
@lyngai  另外我咨询一下，我把渲染后的html转成html文件，但是似乎复制的按钮不生效，是需要做些什么配置吗？
css和js文件都有引入

**Comment by lyngai** [comment]
> @lyngai 另外我咨询一下，我把渲染后的html转成html文件，但是似乎复制的按钮不生效，是需要做些什么配置吗？ css和js文件都有引入

cc @sunsonliu

**Comment by sunsonliu** [comment]
如果是自己实现的html查看页面，那代码块右上角的复制按钮的确是无法使用的，需要自己实现一下（监听`.cherry-copy-code-block`的click事件）
建议不要后台直出html，改成后台返回md源码，前端调用cherry的纯预览模式（可以参考[这里](https://tencent.github.io/cherry-markdown/examples/preview_only.html)）

**Comment by lycoris-xmin** [comment]
@sunsonliu 好的，谢谢

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/223889745-a417bf7a-a620-48a8-9bfe-db38e77a3fac.png)
@lycoris-xmin 最新版的cherry已经支持了details语法，可以尝试下哈
