### ISSUE TITLE
关于快捷键唤出代码块等时的一些使用优化建议

### ISSUE THREAD

**Issue by msdest565** [Tencent/cherry-markdown#280]
在用快捷键直接写一个代码块时，光标是覆盖整个代码块的，要敲代码还得重新将光标移到```中去```，操作有点繁琐，反而有一种不够快捷的感觉。
![动画](https://user-images.githubusercontent.com/74718981/181691632-060de0ba-2dd3-491c-b1b1-89c2482ad2c0.gif)
如果能够在使用快捷键时直接将光标定位到两个````中间的code...上会更加方便。

**Comment by sunsonliu** [comment]
有道理，插入代码块时的选中逻辑应该优化下

**Comment by msdest565** [comment]
除了代码块之外，其他的快捷键也都有类似的问题。

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/pull/307

成了，加粗、斜体、上下标、删除线、下划线、插入代码块、标题、引用、字体颜色 这些功能都优化了选区。（但字体大小我好想漏了，回来补上），已经合并到dev分支了

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/commit/cacadefff8852dec2ca72b6999b2f0629bcf7f7f

字号的也补上了

**Comment by sunsonliu** [comment]
## 下图是效果

![toolbar优化后效果](https://user-images.githubusercontent.com/998441/184784597-0521f098-0b6e-4fd2-9ca9-e71f58e05612.gif)
