### ISSUE TITLE
工具栏【预览】功能优化

### ISSUE THREAD

**Issue by Morris-G** [Tencent/cherry-markdown#282]
目前顶部操作栏中的【预览】按钮只能切换成纯编辑模式和纯预览模式，如果切换之前是纯编辑模式感觉没问题，但是如果是双栏编辑模式行为就很怪异，第一次点击【预览】会先切换成纯编辑模式，再次点击才会是预览模式。希望这个功能可以早日提上优化日程:)

**Comment by sunsonliu** [comment]
目前有两个跟模式有关的按钮，分别是“关闭/开启预览”、“切换预览/编辑模式”。

这两个按钮其实是为不同的场景设计的。“关闭/开启预览”是给web端且有较大编辑区域的双栏编辑场景使用的。后者是给H5或有较小编辑区域的场景使用的。

所以理论上不建议在双栏编辑场景使用“切换预览/编辑模式”的按钮，正因为这种思想在“作祟”，所以这个bug一直存在但我们并没有去优化。

后续有精力了会对这块再进行优化（最近主要在优化点击工具栏后插入的内容的选中区域#280、新增联想#277）
