### ISSUE TITLE
纯预览状态下使表格不可编辑

### ISSUE THREAD

**Issue by Morris-G** [Tencent/cherry-markdown#284]
现在`enablePreviewerBubble`默认是`true`，在纯预览模式下表格和图片是可以操作的，虽然可以自行判断设值，但是感觉编辑器本身可以设置一下“纯预览模式下表格不支持编辑”的逻辑

**0.7.6**
在最新的在线环境试了一下，发现纯预览模式下确实不可以编辑了，不过在双栏模式下，点击表格内容，控制台会报错0.0
<img width="589" alt="image" src="https://user-images.githubusercontent.com/33714914/182127853-99a702b2-d4a4-4926-95d1-c34d1dab6082.png">

**Comment by sunsonliu** [comment]
是的，纯预览模式下是不允许在预览区域编辑的，不过后面会改成可配置的，这样未来就有机会提供类typora的编辑体验了。

报错是找不到表格对应的语法导致的（目前只支持了标准的md表格语法），还需要进一步的优化这里的逻辑~
