### ISSUE TITLE
[Bug report] Event.Events.toolbarHide / Event.Events.toolbarShow 无法正确响应

### ISSUE THREAD

**Issue by ufec** [Tencent/cherry-markdown#293]
**Describe the bug**
`Event.emit(toolbarInstanceId, Event.Events.toolbarHide)` 和 `Event.emit(toolbarInstanceId, Event.Events.toolbarShow)` 均无法正确响应修改 `cherry.status.toolbar` 的状态值

**Comment by sunsonliu** [comment]
统一优化了下，现在全局的instanceId都可以通过`this.$cherry.instanceId`获取
