### ISSUE TITLE
[Bug report] Cannot read properties of undefined (reading 'line-table')

### ISSUE THREAD

**Issue by ufec** [Tencent/cherry-markdown#301]
**Describe the bug**
实例化`cherry`对象时，不传入 `toolbars` 配置，或者传入 `{toolbars: toolbar[{insert: ['line-table']}]}`
前者由于不传入配置则加载默认配置，而默认配置中含有 ``{toolbars: toolbar[{insert: ['line-table']}]}``
后者则是显示传入

**Comment by sunsonliu** [comment]
已被 @ufec 修复，并合并到dev分支
