### ISSUE TITLE
[Bug report] Cannot read properties of undefined (reading 'createBtn')

### ISSUE THREAD

**Issue by ufec** [Tencent/cherry-markdown#303]
**Describe the bug**
原仓库 [Toolbar.js#L109](https://github.com/Tencent/cherry-markdown/blob/dev/src/toolbars/Toolbar.js#L109)
此处 `subMenu` 可能还未实现，即为 `undefined`，需要做检测

**Comment by sunsonliu** [comment]
已被 @ufec 修复并合并到dev分支
