### ISSUE TITLE
[Bug report] There is a bug when I set the 'shortcutKeys' in the function 'createMenuHook'

### ISSUE THREAD

**Issue by Jhon-19** [Tencent/cherry-markdown#305]
**Describe the bug**
The shortcut key will work well, but there will be an exception at Doc.splitLines (cherry-markdown.js:11914:15). I find the reason is that the engine will split the line when I use the shortcut key.

**Comment by Jhon-19** [comment]
I find the method to solve this bug. When you override the 'onClick' function, you should have a "return '';" order.

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/184785587-f3515025-2d0b-4556-81bd-a9b43067bbe8.png)
