### ISSUE TITLE
你好，使用 export('pdf')只是导出第一页，有多页的情况下怎么使用？[Bug report] 

### ISSUE THREAD

**Issue by pangchao21** [Tencent/cherry-markdown#311]
init.cherryInstance.export('pdf');
只是导出第一页，有多页的情况下怎么使用？

**Comment by sunsonliu** [comment]
在 https://tencent.github.io/cherry-markdown/examples/index.html 这里试了下，执行`cherry.export('pdf')` 是能够打印所有页面内容的，可以提供更多的信息（如浏览器版本、预览区布局是否有特殊的处理）

**Comment by pangchao21** [comment]
![image](https://user-images.githubusercontent.com/25843968/186297814-4f8c0214-4959-4c7a-8316-2c582b0449bd.png)

谷歌浏览器版本： 103.0.5060.134

**Comment by pangchao21** [comment]
<img width="811" alt="image" src="https://user-images.githubusercontent.com/25843968/186299272-368d93cd-4a6d-4365-b579-6b562ee24312.png">

**Comment by jiawei686** [comment]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/12953093/186830300-f81dfdcb-4d3f-4b46-a82c-a227ac4f2e92.png">

`init.cherryInstance.export('pdf');`方法是调用浏览器API将生成的HTML内容作为pdf导出，仅提供给操作栏导出按钮内部使用，不支持外部调用。看楼主已经拿到了HTML结构，有自己点击下载业务逻辑，则需要自行实现下载方法。如果一定要外部调用export方法的话需要确保body没有限制高度，且没有`overflow: hidden!important`等强制css写法。
