### ISSUE TITLE
[Bug report]  setValue(content); content含有\n换行引起的bug 

### ISSUE THREAD

**Issue by pangchao21** [Tencent/cherry-markdown#312]
<img width="834" alt="image" src="https://user-images.githubusercontent.com/25843968/186603419-dad6806b-f191-4d02-95f6-e3129545b6e5.png">

再次点击编辑框输入，会报错
<img width="757" alt="image" src="https://user-images.githubusercontent.com/25843968/186603612-60382fc8-1899-4d1f-b720-8ec659fc3bfa.png">

**Comment by sunsonliu** [comment]
并没有重现出来。。请问可以在 https://tencent.github.io/cherry-markdown/examples/api.html 这里重现么？

**Comment by sunsonliu** [comment]
并没有重现，先关闭了，如果还能重现欢迎再跟我们反馈哈
