### ISSUE TITLE
自定义工具栏子菜单报错t16 is not a function

### ISSUE THREAD

**Issue by chun222** [Tencent/cherry-markdown#315]
使用版本为0.7.9 !
按照介绍自定义菜单，一级没问题，二级就报错！
![image](https://user-images.githubusercontent.com/57406062/188106725-90c14e94-697c-485b-b176-c00a9f0ebf5b.png)
配置如下：
```ts
const AddPrefixTemplate = Cherry.createMenuHook("AddPrefixTemplate", {
    name: "插入告示",
    // onClick(selection: string) {
    //     console.log(selection);
    //     return 'Prefix-' + selection;
    // },
    shortcutKeys: [], //快捷键集合, 用于注册键盘函数，当匹配的快捷键组合命中时，也会调用click函数
    //子菜单 
    subMenuConfig: [{
        name: "菜单1",
        noIcon: true,
        onClick(selection:string) {
            console.log(selection);
            return 'Prefix-' + selection;
          },
        
    }],
});
```

![image](https://user-images.githubusercontent.com/57406062/188106825-c6403d91-2993-4390-acb5-0f230a3e494b.png)

**Comment by chun222** [comment]
在float和bubble配置自定义菜单也是无效的  无法显示； 在sidebar配置是可以正常显示的

**Comment by sunsonliu** [comment]
Hello，我们刚发了0.8版，0.8版我们对toolbar这块进行了大量的重构，目测可以解决咱们的问题哈，欢迎试试~

**Comment by chun222** [comment]
@sunsonliu  0.8.0版本自定义的自定义一级toolbar都不能使用了，点击后就报错：
![image](https://user-images.githubusercontent.com/57406062/188340973-00a05aa1-7634-4c91-9815-37286d135f06.png)

这是我的代码：
```js
const AddPrefixTemplate = Cherry.createMenuHook("AddPrefix", {
    iconName: " fa fa-save",
    name: "插入告示",
    onClick(selection: string) {
        console.log(selection);
        return 'Prefix-' + selection;
    },
    ///shortcutKeys: [], //快捷键集合, 用于注册键盘函数，当匹配的快捷键组合命中时，也会调用click函数
    //子菜单 
    // subMenuConfig: [{
    //     name: "菜单1",
    //     noIcon: true,
    //     onClick(selection:string) {
    //         console.log(selection);
    //         return 'Prefix-' + selection;
    //       },
        
    // }],
});

//
  toolbars: {
                toolbar: [
                   "addPrefix",
]
}
..
   customMenu: {
                    // 注入编辑器的菜单中
                    // 对象 key 可以作为菜单项的名字（需要保证唯一），在上方的配置中使用
                    addPrefix: AddPrefixTemplate,
                },
```

**Comment by sunsonliu** [comment]
收到收到。。我们定位下哈~~

**Comment by humyfred** [comment]
你好，是文档书写有误，这里子菜单的onclick不是驼峰：
![image](https://user-images.githubusercontent.com/15084352/188821007-63ddca78-0f9c-4475-bd4c-db8f589e89d0.png)
文档已经纠正，感谢反馈！

**Comment by chun222** [comment]
@humyfred   现在升级的版本0.8.1和0.8.0不是子菜单问题，配置的一级toolbar都会报错呢！
```
Uncaught TypeError: Cannot read properties of undefined (reading 'editor')
``` 

![image](https://user-images.githubusercontent.com/57406062/188851091-9d2c072c-f06c-4c64-b4e0-fd01a9d7af85.png)

**Comment by humyfred** [comment]
0.7.9 会报错吗？如果没有报错先用0.7.9，我们定位下0.8.X得问题

**Comment by sunsonliu** [comment]
已修复哈，目前在dev分支。是重构菜单的逻辑时引入的。
自定义菜单的例子可以参考这里：https://github.com/Tencent/cherry-markdown/blob/dev/examples/scripts/index-demo.js
列了三个例子：
1. 独立菜单，支持选区空置（customMenuA）
2. 空壳菜单，用来做结构梳理（customMenuB）
3. 自带子菜单（customMenuC）
