### ISSUE TITLE
[Bug report]自定义工具栏使用不了

### ISSUE THREAD

**Issue by YJ-L-2017** [Tencent/cherry-markdown#317]
按照文档中的配置，在examples/index.html示例的基础上修改，自定义工具栏配置之后不显示

![image](https://user-images.githubusercontent.com/32069254/189029368-e1f82e39-3e01-43f2-a113-aa2b13931eea.png)

点击添加的按钮会报错：
MenuBase.js:173 Uncaught TypeError: Cannot read properties of undefined (reading 'editor')
    at CustomMenu.fire (MenuBase.js:173:38)
    at Toolbar.onClick (Toolbar.js:140:12)
    at HTMLSpanElement.<anonymous> (Toolbar.js:86:16)

**Comment by sunsonliu** [comment]
已修复哈，目前在dev分支。
自定义菜单的例子可以参考这里：https://github.com/Tencent/cherry-markdown/blob/dev/examples/scripts/index-demo.js
