### ISSUE TITLE
[Feature request] 请问是否有方法能 清空编辑记录 (避免 Ctrl+Z 复原

### ISSUE THREAD

**Issue by hbl917070** [Tencent/cherry-markdown#318]
**Is your feature request related to a problem? Please describe.**
我将cherry-markdown用于开发成文件阅读器，网页会在不重新整理的情况下载入新的档案，
我使用 `cherryObj.setMarkdown(str);` 来更新内容，
但 Ctrl+Z 的快速键能使cherry-markdown返回到上一份文件的内容，我不希望这件事情发生，
请问是否有方式可以 清空编辑记录？

**What does the proposed API look like**
希望能有个方法，能 清空编辑记录(Ctrl+Z的历史资料)。

**Additional context**
使用的 cherry-markdown 版本：v0.8.0
使用的系统：Windows 10
使用的浏览器：Edge  105.0.1343.27
![GIF 2022-9-9 上午 06-55-46](https://user-images.githubusercontent.com/12185698/189240779-4e3442c7-c2fc-41df-addb-5a80a5b44254.gif)

**Comment by sunsonliu** [comment]
目前还没有直接暴露清理历史的接口，可以使用`cherry.editor.editor.clearHistory()`来清理编辑历史，调用后会清空undo栈

**Comment by gspgsp** [comment]
清空编辑记录，还原到原始状态，这个挺好的，如果预览之后，感觉不好，可以恢复到原始状态，再重新编辑
