### ISSUE TITLE
[Feature request] 快速键 shift + tab 无作用

### ISSUE THREAD

**Issue by hbl917070** [Tencent/cherry-markdown#319]
**Is your feature request related to a problem? Please describe.**
大多数的MD编辑器都可以使用 `tab` 与 `shift + tab` 来对文字进行进缩编辑，
但cherry-markdown只能使用 `tab` ，选取超过2个字以上时，`shift + tab` 完全无作用，
不确定这是BUG，还是cherry-markdown尚未支援 `shift + tab` 的功能。

**Additional context**
我使用的 cherry-markdown 版本：v0.8.0
系统：Windows 10
浏览器：Chrome  105.0.5195.102

下图为 ByteMD 的使用情况
![GIF 2022-9-9 上午 07-23-25](https://user-images.githubusercontent.com/12185698/189243835-86ddd2ba-9f06-4eea-b3e3-131e99ac835e.gif)
https://bytemd.js.org/playground/

**Comment by sunsonliu** [comment]
加上了（已提交到dev分支），快捷键跟sublime Text编辑器的快捷键尽量对齐了（使用了[codemirror的sublime快捷键机制](https://codemirror.net/5/demo/sublime.html)）。
