### ISSUE TITLE
紧接着上一音频再插入音频时，会导致音频样式有误

### ISSUE THREAD

**Issue by zhongyangynag** [Tencent/cherry-markdown#32]
![image](https://user-images.githubusercontent.com/44021190/142556358-ab366a79-3a2c-47b9-bc24-02a076bdeb49.png)

**Comment by sunsonliu** [comment]
感谢反馈，目测是连续两个音频语法（估计图片、视频语法也有类似问题）的bug，我们定位修复下哈
