### ISSUE TITLE
[Bug report] 设定 bubble:false 后，工具列的浮动选单功能异常

### ISSUE THREAD

**Issue by hbl917070** [Tencent/cherry-markdown#321]
**Describe the bug**
设定 bubble:false 后，工具列的浮动选单功能异常

**Expected behavior**
正常情况下，展开工具列的浮动选单，点击其他地方后，浮动选单就会消失
![GIF 2022-9-13 上午 06-25-54](https://user-images.githubusercontent.com/12185698/189770033-40ba41d8-4b4a-4bb5-abb6-e18c6a8e4124.gif)

**To Reproduce**
使用 bubble:false 的话，工具列的浮动选单将不会正常消失
![GIF 2022-9-13 上午 06-27-09](https://user-images.githubusercontent.com/12185698/189770374-8cfaad12-e26f-499d-8d41-31593fed3d96.gif)

```html
<style>
    html,
    body {
        margin: 0;
        height: 100%;
        overflow: hidden;
    }
</style>

<div id="markdown-container"></div>

<script src="./cherry-markdown.min.js"></script>
<link rel="stylesheet" href="./cherry-markdown.min.css">

<script>
    const cherryObj = new Cherry({
        id: 'markdown-container',
        value: '# welcome to cherry editor!',
        toolbars: {
            bubble: false, // 选中文字弹出工具列
        }
    });
</script>
```

**Environment:**
 - OS: WIndows 10
 - Browser Edge 105.0.1343.33
 - Version v0.8.0

**Comment by sunsonliu** [comment]
已合到dev分支
