### ISSUE TITLE
[Bug report] 字体大小功能隔行显示异常

### ISSUE THREAD

**Issue by salutonly** [Tencent/cherry-markdown#325]
<img width="777" alt="fontsizeBug" src="https://user-images.githubusercontent.com/68188941/192131542-a20ad8f4-eb1f-4b2e-bf5b-fc9054fcf813.png">

**Comment by sunsonliu** [comment]
抱歉国庆嗨去了现在才看到，我们尽快修复

**Comment by sunsonliu** [comment]
已修复并提交到dev分支
