### ISSUE TITLE
[Bug report] 配置 anchorStyle:'none' 后 [[toc]] 无效

### ISSUE THREAD

**Issue by lxzlx624** [Tencent/cherry-markdown#326]
![image](https://user-images.githubusercontent.com/23074885/192731550-4aa1f78a-8b41-4bd9-88b4-abf07f253343.png)
![image](https://user-images.githubusercontent.com/23074885/192731759-c7028533-6b4d-4467-b4ea-afa920a692bf.png)
图一是anchorStyle:'none'，图二是 anchorStyle:'default'（锚点样式修改了下）

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/commit/8308b5c1541197fc5dc76c215b13f7e7deea490f
已修复并提交到dev分支
