### ISSUE TITLE
[Feature request] 可以在html中直接引入使用吗？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [Tencent/cherry-markdown#327]
可以使用cdn或者本地直接引入到html中使用吗？

**Comment by lyngai** [comment]
可以使用 [jsDelivr](https://www.jsdelivr.com/) 提供的 npm cdn 服务。

e.g.

https://cdn.jsdelivr.net/npm/cherry-markdown/dist/cherry-markdown.min.js
https://cdn.jsdelivr.net/npm/cherry-markdown/dist/cherry-markdown.min.css

---

如果需要指定版本可以参考 jsDelivr 的使用文档。

**Comment by Yakumo-Yukari** [comment]
> 可以使用 [jsDelivr](https://www.jsdelivr.com/) 提供的 npm cdn 服务。
> 
> e.g.
> 
> https://cdn.jsdelivr.net/npm/cherry-markdown/dist/cherry-markdown.min.js https://cdn.jsdelivr.net/npm/cherry-markdown/dist/cherry-markdown.min.css
> 
> 如果需要指定版本可以参考 jsDelivr 的使用文档。

谢谢了！
