### ISSUE TITLE
[Feature request]限制上传文件的格式

### ISSUE THREAD

**Issue by ColynYu** [Tencent/cherry-markdown#328]
上传媒体文件功能，目前所有类型文件都能选中，希望能限制一下对应的格式，比如图片就只有image/*
或者说，提供钩子函数，自定义处理。

**Comment by sunsonliu** [comment]
有道理，正好最近要扩展上传文件的回调函数（支持上传视频的时候设置封面），到时候一起改下

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/blob/dev/src/Cherry.config.js#LC244
已增加配置项（已提交到dev分支）
