### ISSUE TITLE
怎么开箱即用示例效果呢?

### ISSUE THREAD

**Issue by yuandonghua** [Tencent/cherry-markdown#331]
[这个演示例子非常好https://tencent.github.io/cherry-markdown/examples/index.html](https://tencent.github.io/cherry-markdown/examples/index.html)

怎么开箱即用这个例子呢?

代码下载下来无法使用这个例子,很需要把这个演示例子在自己本地跑通,用来学习,求大神支个招

**Comment by sunsonliu** [comment]
1. 下载代码
```
git clone https://github.com/Tencent/cherry-markdown.git cherry
cd cherry
```
1. 安装依赖
```
yarn install
```
3. 开发模式本地运行
```
npm run dev
```


大概这三步就可以搭建一个本地的开发环境哈，一切顺利的话运行`npm run dev`后，会用默认浏览器自动打开examples/index.html 页面。如果遇到问题欢迎继续沟通哈~~
