### ISSUE TITLE
缺一个详细的使用教程,我想写一个

### ISSUE THREAD

**Issue by yuandonghua** [Tencent/cherry-markdown#332]
缺少一个vite-ts-vue3-cherry的使用教程,我想写一个

是特别详细的那种,包括每一个可定制细节,然后出一个详细的使用文档,非常想写一个,这是我遇到的最满意的编辑器,被折服了

**Comment by sunsonliu** [comment]
十分欢迎~ 期待你的PR~~
每个可定制的细节大概都写在了 https://github.com/Tencent/cherry-markdown/blob/main/src/Cherry.config.js 这个文件里，可以参考下哈~~

**Comment by mrsai** [comment]
没有看到插件系统，支持用户自定义插件吗？

**Comment by lyngai** [comment]
> 没有看到插件系统，支持用户自定义插件吗？

支持自定义语法和菜单项。参考文档实现。https://github.com/Tencent/cherry-markdown#extension

**Comment by sunsonliu** [comment]
> 没有看到插件系统，支持用户自定义插件吗？

自定义工具栏的例子可以看这里：https://github.com/Tencent/cherry-markdown/issues/317

**Comment by RSS1102** [comment]
是的，我也认为应该做一个文档，不仅仅是放在每个md文档下，可以使用md文档通过列如[vitepress](https://github.com/vuejs/vitepress)等静态站点生成一份doc，一方面方便**使用者快速查阅需要功能**，另一方面完善的文档更容易推进使用者的入手搭建速度。

**Comment by q2316367743** [comment]
一年过去了

**Comment by RSS1102** [comment]
> 一年过去了

你好，
1. 现在详细文档已经在编辑中，最近再更新一下文档，如果你想投入到文档建设中，可以关注一下：https://github.com/Tencent/cherry-markdown/tree/main/docs
2. 关于 vue3、react的示例项目已经在编辑中，最近会放到文档内预览。
