### ISSUE TITLE
注入的js 代码，好像不会执行

### ISSUE THREAD

**Issue by zhaoxianfang** [Tencent/cherry-markdown#333]
注入的js 代码，好像不会执行,该如何处理
```
<script type="text/javascript" >
console.log('hello')
</script>
```

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/196077811-f8f4725f-3031-4197-937e-56e19ff01bb6.png)

https://tencent.github.io/cherry-markdown/examples/xss.html
试了下，应该是OK的哈~可以在上面的链接里试试

**Comment by sunsonliu** [comment]
先关闭了，如果还是有问题欢迎再反馈哈
