### ISSUE TITLE
编辑区和预览区有大纲点击跳转功能吗?

### ISSUE THREAD

**Issue by yuandonghua** [Tencent/cherry-markdown#334]
<h1 data-lines="1" data-sign="cdcb3735afd7fcd590598d095c509e00" id="%E8%87%AA%E5%AE%9A%E4%B9%89toolbar%E6%8C%89%E9%92%AE"><a href="#%E8%87%AA%E5%AE%9A%E4%B9%89toolbar%E6%8C%89%E9%92%AE" class="anchor"></a>自定义toolbar按钮</h1>

目前cherry有大纲功能吗?大致看了下部分原码没找到

我目前的实现思路:

1. 遍历出h元素,找到对应的id,封装成大纲
2. 展示大纲,1级,2级,3级等
3. 点击大纲,找到元素id,让对应的元素滚动到指定位置

**Comment by lyngai** [comment]
支持的，`[TOC]` 语法。

**Comment by yuandonghua** [comment]
![image](https://user-images.githubusercontent.com/5047031/197335292-9b96162e-9cb2-4504-9ef2-4ae6171de5d4.png)

![image](https://user-images.githubusercontent.com/5047031/197335331-88698798-407b-43ff-8b33-15faeed8fc5a.png)

已实现大纲

**Comment by sunsonliu** [comment]
悬浮大纲或大纲相关的更多操作，我们建议在业务侧来实现，组件不太适合做太多预览之外的功能
