### ISSUE TITLE
企业微信复制的文本粘贴到编辑器中直接报错

### ISSUE THREAD

**Issue by dsssc** [Tencent/cherry-markdown#336]
企业微信中拷贝出来的文字：
<html>\r\n<body>\r\n\x3C!--StartFragment-->整个迭代过程也要管好，从需求、开发实现设计、代码审查、测试，各个环节都很重要\x3C!--EndFragment-->\r\n</body>\r\n</html>
![image](https://user-images.githubusercontent.com/10488309/197433980-7873f241-2075-431b-ab22-57b5269c80c5.png)
，此处没有做兼容处理

**Comment by sunsonliu** [comment]
并没有复现，可以提供一些更详细的复现路径不，包括系统、浏览器（及版本）、复制企微中的什么内容，以及是否可以在https://tencent.github.io/cherry-markdown/examples/index.html 这里复现？

**Comment by dsssc** [comment]
`var CustomVideo = Cherry.createMenuHook('上传视频', {
        iconName: 'video',
        onClick: function () {
          return '<img src="http:///UpFiles/0909/2022/10/10/88ed731e-59ff-4df2-9337-7862d8f74ac0.png" data-video-url="请在此处输入video地址">\n'
        }
      })
      this.cherryObj = new Cherry({
        id: 'markdown',
        engine: {
          syntax: {
            mathBlock: {
              engine: 'MathJax'
            },
            inlineMath: {
              engine: 'MathJax' // katex或MathJax
            }
          }
        },
        value: content,
        editor: {
          height: '635px',
          defaultModel: mode == 3 ? 'previewOnly' : 'edit&preview'
        },
        toolbars: {
          theme: 'light',
          toolbar: [
            'bold',
            'italic',
            'strikethrough',
            '|',
            'color',
            'header',
            '|',
            'list',
            {
              insert: ['image', 'link', 'hr', 'br', 'code', 'formula', 'table', 'line-table', 'bar-table']
            },
            'graph',
            'export',
            'togglePreview',
            'fullScreen',
            'CustomVideo'
          ],
          sidebar: ['mobilePreview'],
          customMenu: { CustomVideo: CustomVideo }
        },
        fileUpload: function (file, callback) {
          var formData = new FormData()
          formData.append('file', file)
          axios({
            method: 'post',
            url: '/api/FileManager/Upload',
            headers: { 'Content-Type': 'multipart/form-data' },
            data: formData
          }).then(function (res) {
            if (res.data.success) {
              callback(res.data.result.Location)
            }
          })
        },
        previewer: {
          enablePreviewerBubble: false
        }
      })`
本地引用cherry-markdown版本 0.8.2
![image](https://user-images.githubusercontent.com/10488309/197661876-4d2fc778-d620-4a0c-9f9f-423254e537d9.png)
复制内容：企业微信任何拷贝的文字
系统：windows 10
浏览器版本：EDGE  106.0.1370.52
无法在https://tencent.github.io/cherry-markdown/examples/index.html 进行复现，怀疑是不是引用的dist文件,clone  example项目到本地，修改index-demo.js的配置为上述配置，粘贴企业微信任意内容就会出现错误

**Comment by lyngai** [comment]
报的是什么错误呢？给一下详细信息？

**Comment by dsssc** [comment]
![image](https://user-images.githubusercontent.com/10488309/197678877-eed48d22-fb60-484d-b647-ddf7d8391222.png)
![image](https://user-images.githubusercontent.com/10488309/197678960-3d6136cc-0a9c-428f-9153-58138c134ab7.png)

**Comment by lyngai** [comment]
get 我们具体看看。

**Comment by sunsonliu** [comment]
已提交到dev分支，有个判断忘记判空了
