### ISSUE TITLE
[Bug report] cherryMarkdownConf.previewer.enablePreviewerBubble = false下 代码块无法进行复制操作

### ISSUE THREAD

**Issue by danny00lo** [Tencent/cherry-markdown#337]
**Describe the bug**
cherryMarkdownConf.previewer.enablePreviewerBubble = false 下 代码块无法进行复制操作

**Environment (please complete the following information):**
 - OS: all
 - Browser all
 - Version 8.2

**Comment by sunsonliu** [comment]
收到，让我们纠结一下（如果代码快永远可复制，会不会让一些禁止复制代码块的场景尴尬）。。

**Comment by sunsonliu** [comment]
已提交到dev分支，增加了`engine.codeBlock.copyCode` 配置项，如果不希望有复制代码块功能，可以`engine.codeBlock.copyCode = false` 来关闭
