### ISSUE TITLE
[Bug report] 拖拽上传图片的时候，图片会插入到光标所在位置

### ISSUE THREAD

**Issue by miaobuao** [Tencent/cherry-markdown#338]
拖拽上传图片的时候，图片会插入到光标所在位置，而不是实际拖拽到的位置

**Comment by sunsonliu** [comment]
好有道理。。当时实现的时候没有注意到拖拽的时候还有个光标，我们修复下。
ps. 我们也支持批量拖拽哈，并且还支持批量拖拽不同格式的文件（图片、视频、纯文本、非纯文本）

**Comment by miaobuao** [comment]
> 好有道理。。当时实现的时候没有注意到拖拽的时候还有个光标，我们修复下。 ps. 我们也支持批量拖拽哈，并且还支持批量拖拽不同格式的文件（图片、视频、纯文本、非纯文本）

嗯嗯，感谢！非常喜欢这个编辑器

**Comment by sunsonliu** [comment]
已提交到dev分支
