### ISSUE TITLE
[Feature request] 工具栏希望可以换行&增加对齐方式

### ISSUE THREAD

**Issue by miaobuao** [Tencent/cherry-markdown#340]
1. 比如setting可以选择居右显示
2. 在屏幕比较小的情况下可以分行显示工具栏

**Comment by sunsonliu** [comment]
收到，请问这里的居右显示是指的左边编辑区域还是右边预览区域的内容？

**Comment by miaobuao** [comment]
> 收到，请问这里的居右显示是指的左边编辑区域还是右边预览区域的内容？

预览区域应该是要有的（）
编辑区域的话，我不太好确定显示还是不显示的效果好~

**Comment by sunsonliu** [comment]
我周末试了下。。。发现预览区域右对齐简直没法看。。。
可能是我想象力匮乏，请问有没有类似右对齐的例子我们参考下？

**Comment by sunsonliu** [comment]
![WeCom截圖_c3bc584f-3d5d-425f-936d-635fcfdc4441](https://user-images.githubusercontent.com/998441/198965622-723937aa-5d4b-4cc7-a70a-a501bfa744eb.png)
哦哦哦哦。你说的是顶部工具栏右对齐么？

**Comment by sunsonliu** [comment]
明白啦，我们搞搞~

**Comment by object-kaz** [comment]
要不 `toolbars.toolbar` 这块加个空字符串 `''` 就代表一段空白区域 😂

**Comment by sunsonliu** [comment]
> 要不 `toolbars.toolbar` 这块加个空字符串 `''` 就代表一段空白区域 😂

感觉有点晦涩，我打算增加个toolbars.rightToolbar 的配置项。。但还没想好咋实现。。。

**Comment by miaobuao** [comment]
> > 要不 `toolbars.toolbar` 这块加个空字符串 `''` 就代表一段空白区域 joy
> 
> 感觉有点晦涩，我打算增加个toolbars.rightToolbar 的配置项。。但还没想好咋实现。。。

我觉得增加一个自适应宽度的空白区域挺好的（望采纳

用flex布局，flex-grow

**Comment by miaobuao** [comment]
然后是不是顺便把自定义样式给做了哈哈哈哈哈哈 加油！

**Comment by RSS1102** [comment]
> 1. 比如setting可以选择居右显示
> 2. 在屏幕比较小的情况下可以分行显示工具栏

1. 考虑直接使用`Scroll`进行滚动
2. 或者使用`Overflow adaptation`，对于超出的长度进行收集到一个下坠菜单上
