### ISSUE TITLE
[Feature request]图片希望增加点击大图预览功能

### ISSUE THREAD

**Issue by meihaomingtian23** [Tencent/cherry-markdown#342]
在编辑情况下拥有超酷的修改图片尺寸的功能
![image](https://user-images.githubusercontent.com/49868468/198550137-4d1c4e39-3b31-44dd-a11b-43f30a281ed4.png)
但是在预览情况下，图片只能干巴巴的显示

希望增加点击图片可以全屏大图预览的功能
以便于在一些显示区域小的地方使用cherry的时候，也能查看清晰的图片。
例如mavon editor：
在编辑情况下的显示：
![image](https://user-images.githubusercontent.com/49868468/198551582-5b85e332-72d1-4132-a91b-2996fb42053a.png)

在编辑预览区点击图片后：
![image](https://user-images.githubusercontent.com/49868468/198551525-b2e4a3ed-a5d2-4440-9b12-f98e0e4e7323.png)
这里由于图片过大，可以看到是缩小了以后才看到整幅图的（体验不好）

另外如果能有以下基于上述功能的优化就更好了
比如：
1.可以在预览界面增加对图片的控制，比如翻转，放大缩小等，类似我们本地的图片阅览器上面带的功能，添加预览情况下操作工具栏
2.可以通过一些配置项，选择对上述控制的显示与否（是否可全屏大图预览，是否显示预览情况下操作工具栏）
3.可以通过一些配置项，选择切换图片预览模式（默认最大显示，默认实际显示等）

**Comment by sunsonliu** [comment]
这个需要业务方自行实现哈，可以参考这个例子：https://tencent.github.io/cherry-markdown/examples/preview_only.html ， 这个例子用了https://fengyuanchen.github.io/viewerjs/js/viewer.js 这个组件

为什么需要第三方自己来实现可以看这个issue哈：#199
