### ISSUE TITLE
[Bug report] codeblock 里面 ‘$’ 转成了 ~1D

### ISSUE THREAD

**Issue by happy848** [Tencent/cherry-markdown#350]
**Describe the bug**

codeblock 里面 ‘$’ 转成了 ~1D

**To Reproduce**

```
code 
[$][0]
```

转成了：

code 
[~1D][0]

**Expected behavior**
保留$

**Screenshots**
![image](https://user-images.githubusercontent.com/117877467/200981820-b59ed30c-a5c6-4fc6-ac1a-3ce8f1d1087c.png)

**Comment by sunsonliu** [comment]
早已修复
