### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by disyli** [Tencent/cherry-markdown#353]
**Describe the bug**
最新0.8.8版本，node內new CherryEngine()直接报错。

**Environment (please complete the following information):**
 - OS: [macOS]
 - Version [e.g. 0.8.8]

**Comment by lyngai** [comment]
报错信息提供一下？

**Comment by disyli** [comment]
ReferenceError: localStorage is not defined
    at pd (/test/node_modules/cherry-markdown/dist/cherry-markdown.engine.core.common.js:1:196857)
...

**Comment by sunsonliu** [comment]
已经修复并提交到dev分支了
