### ISSUE TITLE
[Bug report] 浮动工具栏和semantic ui 下拉菜单冲突

### ISSUE THREAD

**Issue by yangrunkang** [Tencent/cherry-markdown#357]
**Screenshots**
![image](https://user-images.githubusercontent.com/46257933/202848106-ced023fd-0527-42a3-8d69-73d3ee4010a5.png)

**Comment by yangrunkang** [comment]
![image](https://user-images.githubusercontent.com/46257933/202848219-f7f7c776-3877-4760-8618-886aeeb9787b.png)

z-index:100 ..

**Comment by sunsonliu** [comment]
z-index全部缩小了，已提交到dev分支
