### ISSUE TITLE
[Bug report] 当上传文档不传第2个参数时，会读取不了原文件的name

### ISSUE THREAD

**Issue by danny00lo** [Tencent/cherry-markdown#358]
**Describe the bug**
上传组件不传第2参数时，会报错

**To Reproduce**
1. 拖图片上传
2. 不传第2个参数params，报错

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows/macOS]
 - Browser [e.g. Chrome, Safari]
 - Version [e.g. 0.5.14]

**Additional context**

**Comment by humyfred** [comment]
源码里确实有个params参数判断不是很严谨

**Comment by sunsonliu** [comment]
已修复并提交到dev分支
