### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by hyx-bjq** [Tencent/cherry-markdown#367]
1、不能随意设置空行，虽然文字之间能空一行就够了，但是有的时候真的我需要多空几行来达到醒目的效果；
2、一些奇怪的符号会产生bug显示不出来__proto__这个代码如果加粗它的下划线就会被吞掉，我不知是否是和内置语法冲突；
![image](https://user-images.githubusercontent.com/39325061/206654787-9847a3f0-c9d3-4b3e-a99b-0e821cab8e57.png)

**Comment by lyngai** [comment]
1. 手动插入多个空行请使用 `<br>` 标签，多个连续空行会自动合并为一行。[^1]
2. `__text__` 下划线对应加粗语法。[^2]

**FYI:**

[^1]: https://spec.commonmark.org/0.30/#example-221
[^2]: https://spec.commonmark.org/0.30/#example-381
