### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by hyx-bjq** [Tencent/cherry-markdown#368]
1、字体不能快速设置成彩色；
2、表格类型实在单一，好歹能让我换个背景颜色，边框颜色样式粗细；
3、这个估计就很难优化了，代码块里面代码的颜色我希望能够像VScode的皮肤一样自定义更换或者多来几套颜色模板；

**Comment by lyngai** [comment]
1、3 都已经支持。

<video src="https://user-images.githubusercontent.com/22373754/206658190-9c2b0809-db83-46ca-8f12-f0ace160905e.mov" />

2 更像是富文本编辑的需求，markdown 文档的原则就是尽可能简单，不必纠结于文档样式。如果业务有需求可以通过定制 css 实现。
