### ISSUE TITLE
[Bug report] 点击语法的最后一行，右边的预览会异常跳到最顶端

### ISSUE THREAD

**Issue by hbl917070** [Tencent/cherry-markdown#374]
**Describe the bug**
当左边语法区块最后一行是空白行(\n)时，
用滑鼠点击空白行，右边的「预览」就会异常跳到最顶端

**To Reproduce**
我用的是github上的demo 
[https://tencent.github.io/cherry-markdown/examples/index.html](https://tencent.github.io/cherry-markdown/examples/index.html)
测试语法如下
```
這是頂端 here is the top
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

123
456
789
end


```

**Screenshots**
![GIF 2023-1-2 下午 11-16-36](https://user-images.githubusercontent.com/12185698/210251354-14324d72-2a14-49c9-85d2-ed5b277c5bcc.gif)

**Environment:**
 - OS:  Windows 10
 - Browser Chrome 108.0.5359.125
 - Version 我不清楚 cherry-markdown 的版本为何，是否有方法可以从 DevTools 获取版本资讯？

**Comment by sunsonliu** [comment]
已经修复并提交到dev分支
