### ISSUE TITLE
[Feature request]搜索替换功能

### ISSUE THREAD

**Issue by zimolab** [Tencent/cherry-markdown#379]
能否开启codemirror自带的搜索替换功能？

**Comment by sunsonliu** [comment]
是可以的，只是一直没有时间研究codemirror的搜索组件，所以一直没安排上。。。

**Comment by sunsonliu** [comment]
哈哈，求那个第三方组件的地址，我们瞅瞅~~~

**Comment by zimolab** [comment]
应该是这个仓库：https://github.com/L-Focus/cm-search-replace
不过很奇怪的是，作者没有把源码上传到github上，npmjs上倒是有源码，搜索cm-search-replace就行，MIT协议的，用起来应该没啥问题。我看了一下，实现也不是很复杂，如果要正式添加到cherry-markdown里，最好还是要统一一下外观风格，界面上显示的字符串也要做一下国际化处理。

**Comment by sunsonliu** [comment]
收到~感谢推荐，我们去瞅瞅~~

**Comment by sunsonliu** [comment]
感谢推荐，已经接入了，在dev分支。
因为是第三方的组件，不太好修改，所以并没有实现国际化（现在是纯英文）。关于样式简单的处理了下感觉就挺好的。

如果有任何建议欢迎再给我们提issue哈，期待你的更多反馈~~
