### ISSUE TITLE
[Bug report]<details>渲染异常

### ISSUE THREAD

**Issue by dreamncn** [Tencent/cherry-markdown#385]
**Describe the bug**
`<details>`渲染异常

**To Reproduce**
我尝试在markdown中加入details块来隐藏部分内容，在隐藏部分为文本的时候没什么问题，但是如果是代码块或者标题就会出现溢出的情况
```` html
<details >
<summary>fffffff</summary>
	<p>
		```javascript
function xxxx() {
    
}
```
	</p>
</details>
```` 

**Expected behavior**
代码块出现在Details中，而不是顺移到下面来

**Screenshots**
<img width="764" alt="image" src="https://user-images.githubusercontent.com/37787014/215261682-de6bb2b6-e405-41ff-b190-67c4307a88c5.png">
<img width="768" alt="image" src="https://user-images.githubusercontent.com/37787014/215261701-bf23cbe1-1451-451e-9e9e-9854e82dcbfb.png">
<img width="822" alt="image" src="https://user-images.githubusercontent.com/37787014/215261782-7fafc0e9-da8e-4ecf-9f38-0ead5e5bece3.png">

**Environment (please complete the following information):**
 - OS: macOS
 - Browser Chrome,
 - Version 0.8.9

**Additional context**
无

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/227933901-079a8b0c-30d7-42df-8e78-388ba2f991b3.png)

已增加`<details>`标签对应的语法，欢迎尝试哈
