### ISSUE TITLE
[Bug report] getHtml(true)保存的HTML依旧不带样式

### ISSUE THREAD

**Issue by stonexwx** [Tencent/cherry-markdown#386]
**Describe the bug**
getHtml(true)保存的HTML依旧不带样式
![image](https://user-images.githubusercontent.com/59043142/215270695-6be70d63-6269-4adc-948f-22e726ce0ff4.png)
应该不是我理解错意思吧

**Environment (please complete the following information):**
 - OS: [ Windows]
 - Browser [webview2]
 - Version [0.8.12]

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/215371893-7e47934f-62be-4636-a2ba-1375bac6a4e4.png)

这里是控制知否带上主题信息（但只有行内代码和代码块的主题信息，整体的主题信息还没搞），如果需要预览区域的样式，可以直接引用我们的css文件即可哈，看这种方案能否满足咱们的需求哈

**Comment by stonexwx** [comment]
昂，明白了，谢谢

**Comment by jh244212647** [comment]
请问还有计划支持导出html附带所有主题信息么，实现预览的效果和导出html之后效果一样
