### ISSUE TITLE
[Bug report]在vue+ts使用CherryEngine报错，ts无法获取对象下的属性

### ISSUE THREAD

**Issue by catHealer** [Tencent/cherry-markdown#387]
在vue+ts中使用0.8.9版本
场景为在新建文章时将markdown内容转为html保存，编辑时需要转回markdown展示
---
import CherryEngine from 'cherry-markdown/dist/cherry-markdown.engine.core'
const cherryEngineInstance = new CherryEngine({})
const content = cherryEngineInstance.makeMarkdown('xxxxx') // ts报错：类型“CherryEngine”上不存在属性“makeMarkdown”。

ts会报错，但方法是能够调用的，是否为CherryEngine的声明文件不完整？
![image](https://user-images.githubusercontent.com/50936990/216018405-f1116a04-4936-49e0-b853-c0839b0a1af8.png)

**Comment by stonexwx** [comment]
可以尝试下引入
import CherryObj from "cherry-markdown"
这个包

**Comment by catHealer** [comment]
类型“typeof Cherry”上不存在属性“engine”。

**Comment by stonexwx** [comment]
这个确实

**Comment by ufec** [comment]
@sunsonliu 这个地方Cherry应该要提供一个`getEngine`的方法吧？`makeMarkdown` 是 `Engine` 上的方法，`CherryEngine` 在构造函数返回了实例后的engine感觉有点儿不合适，或者把这个engine挂在 `CherryEngine` 上？
