### ISSUE TITLE
[Bug report]markdown内有图片时转html后再转回markdown，图片名称丢失

### ISSUE THREAD

**Issue by catHealer** [Tencent/cherry-markdown#388]
使用0.8.9的版本
---
markdown内容：
![xxx.png](http://xxxx.png)
调用转html方法：
const htmlContent = cherryObj.getHtml()
再转markdown：
const mdContent = new CherryEngine({}).makeMarkdown(htmlContent )
console.log(mdContent ) // ![undefined](http:xxx.png)

经过测试还发现如文字上添加了颜色，但经过转换后颜色也会丢失

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/216219464-b20ae550-8c12-4a6f-9dd8-f8ce217b85d8.png)

试了下图片是可以转的，请问在 https://tencent.github.io/cherry-markdown/examples/index.html 这里可以重现么？

文字颜色在转换的过程中是特意去掉的，主要原因是大部分页面里的文字都不是纯黑色（#000），这就导致如果要保留颜色就会产生非常多的颜色语法出来，导致生成的markdown内容不可读

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/216223034-c97392a5-7ab7-484c-8575-9cc039764f65.png)

如果确实需要字体颜色、字体大小、字体背景色，可以修改代码（https://github.com/Tencent/cherry-markdown/blob/main/src/utils/htmlparser.js#L314），去掉315-320行的注释就好了

**Comment by catHealer** [comment]
![image](https://user-images.githubusercontent.com/50936990/216258751-f2873331-aaac-4c53-8d3a-d80c40ea947b.png)
![image](https://user-images.githubusercontent.com/50936990/216258839-57bbf586-ec37-4e03-8cab-e1c868b8a638.png)
原本插入markdown中的图片是有名称的，但是在转换后名称变为undefined了

**Comment by sunsonliu** [comment]
感谢反馈，的确在粘贴图片解析alt属性的时候发生了低级的bug，已经修复并提交到dev分支了哈
