### ISSUE TITLE
global export api

### ISSUE THREAD

**Issue by joriewong** [Tencent/cherry-markdown#39]
- `export('pdf')`
- `export('screenShot')`

> for `preview` mode

**Comment by sunsonliu** [comment]
get~

**Comment by sunsonliu** [comment]
e21895b096c564be03b4450fd27bc5fc44cad3d3
已实现，在cherry、previewer上都支持该方法了

**Comment by pangchao21** [comment]
> * export('pdf')

你好，使用 export('pdf')只是导出第一页，有多页的情况下怎么使用？
