### ISSUE TITLE
cherry-markdown for vscode plugin has published~!

### ISSUE THREAD

**Issue by sunsonliu** [Tencent/cherry-markdown#392]
## view
https://marketplace.visualstudio.com/items?itemName=cherryMarkdownPublisher.cherry-markdown
## install
<img width="828" alt="1" src="https://user-images.githubusercontent.com/998441/217518829-230bbf18-9c81-4841-ad9c-b7d7b7f69f80.png">

## use
<img width="1521" alt="2" src="https://user-images.githubusercontent.com/998441/217518832-efde9754-b915-44b9-844f-5b4c4d691ff6.png">
<img width="1169" alt="3" src="https://user-images.githubusercontent.com/998441/217518837-4dc04711-3501-4f10-9a43-4665cf528643.png">
<img width="1091" alt="4" src="https://user-images.githubusercontent.com/998441/217518839-424c1b00-6a7d-4646-809c-eef6e1d23444.png">
<img width="1514" alt="5" src="https://user-images.githubusercontent.com/998441/217518816-516b83ad-f731-4c86-996c-d8a61564b442.png">

**Comment by YuehuiWu** [comment]
安装了cherry-markedown，但是并没有渲染出来。是否需要安装别的插件呢？还是和哪些插件有冲突呢？
![image](https://github.com/Tencent/cherry-markdown/assets/101700294/18aba40b-1bdf-42d0-9663-2a47bbe5142b)

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/985db9fb-fe4b-472a-b01b-397242ebd229)

额。刚试了下是ok的，或者可以换一个内容少一些的md文件试试么，如果内容少一些的md可以的话，那可能是内容太多导致的性能卡死，这时方便提供下这个model.md的原文么

**Comment by YuehuiWu** [comment]
刚试了，  内容少的也打不开，以下这个就是内容少的。原文见附件。
我用vscode比较少，不太清楚是不是需要什么特殊的设置或依赖。


还有就是


| |
武岳辉
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/24/2023 16:55 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Tencent/cherry-markdown] cherry-markdown for vscode plugin has published~! (Issue #392) |

额。刚试了下是ok的，或者可以换一个内容少一些的md文件试试么，如果内容少一些的md可以的话，那可能是内容太多导致的性能卡死，这时方便提供下这个model.md的原文么

**Comment by sunsonliu** [comment]
好神奇，安装本插件不需要依赖安装其他东西。方便提供下vscode的版本么，以及cherry插件的版本是`0.0.11`么

**Comment by YuehuiWu** [comment]
由于之前的版本打不开，vsCode刚更新到最新，还是不行，之前是1.7...





| |
武岳辉
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/24/2023 17:06 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Tencent/cherry-markdown] cherry-markdown for vscode plugin has published~! (Issue #392) |

好神奇，安装本插件不需要依赖安装其他东西。方便提供下vscode的版本么，以及cherry插件的版本是0.0.11么

**Comment by YuehuiWu** [comment]
| |
武岳辉
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/24/2023 17:13 |
| To | ***@***.******@***.***> |
| Cc | ***@***.******@***.***> ,
***@***.******@***.***> |
| Subject | Re: [Tencent/cherry-markdown] cherry-markdown for vscode plugin has published~! (Issue #392) |
由于之前的版本打不开，vsCode刚更新到最新，还是不行，之前是1.7...





| |
武岳辉
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/24/2023 17:06 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Tencent/cherry-markdown] cherry-markdown for vscode plugin has published~! (Issue #392) |

好神奇，安装本插件不需要依赖安装其他东西。方便提供下vscode的版本么，以及cherry插件的版本是0.0.11么
