### ISSUE TITLE
[Bug report]TypeError: null is not an object (evaluating 'document.body.appendChild')

### ISSUE THREAD

**Issue by icoco** [Tencent/cherry-markdown#395]
typescript porject, 

`import Cherry from 'cherry-markdown/dist/cherry-markdown.core';
...
const cherryInstance = new Cherry({
		id: 'myEditor',
		value: markdown,
  	}); 

`

while yarn run dev,  web browser console throw error : 'null is not an object (evaluating 'document.body.appendChild')'

![image](https://user-images.githubusercontent.com/94627/220535094-31a84602-e67d-4b19-bf63-e4d461b3384b.png)

not sure the bug reason

**Comment by humyfred** [comment]
thanks，we will fix this error soon.

**Comment by eviltik** [comment]
Hi. 

Workaround :

```
window.addEventListener('load', () => {
  document.body.appendChild(this.createDom(SuggesterPanel.panelWrap));
  this.$suggesterPanel = document.querySelector('.cherry-suggester-panel');
});
```

**Comment by eviltik** [comment]
Btw, current files in dist dir have this bug, which make your lib unusable. Please fix. We are in april 2023.

**Comment by humyfred** [comment]
hi，We can‘t reproduce your situation, but we have made some repairs. Please check with the latest version
