### ISSUE TITLE
[Bug report]配置previewer的className参数后，预览界面css样式丢失

### ISSUE THREAD

**Issue by ColynYu** [Tencent/cherry-markdown#396]
**Describe the bug**
配置`previewer` 的`className` 参数后，预览界面css样式丢失，比如代码框的样式、代码框行号、引用的样式等。

**To Reproduce**
可以通过以下链接进行对比复现
https://stackblitz.com/edit/vitejs-vite-ktcwts?file=src/App.vue

**Expected behavior**
未设置`className` 参数时 dom上的class为 `cherry-previewer cherry-markdown theme__null`
自定义设置`className` 参数时 dom上的class为 `cherry-previewer my-markdown-preview theme__null`
缺少了`cherry-markdown` 导致样式缺失，个人认为应该共存，通过自定义的类名，从而修改原有样式，而不是直接把类名移除，或者说，有一个配置参数。

**Screenshots**
![image](https://user-images.githubusercontent.com/24655091/220540772-f3e8a5e4-8739-4b35-b2a0-c78e4230173e.png)

**Comment by sunsonliu** [comment]
已修复并提交到dev分支~
