### ISSUE TITLE
[Feature request]文档缺少自定义语法的demo详细例子

### ISSUE THREAD

**Issue by colynyu** [Tencent/cherry-markdown#397]
希望对`customSyntax`自定义语法有个详细的demo，目前demo如下
```javascript
var CustomHookA = Cherry.createSyntaxHook('codeBlock', Cherry.constants.HOOKS_TYPE_LIST.PAR, {
  makeHtml(str) {
    console.warn('custom hook', 'hello');
    return str;
  },
  rule(str) {
    const regex = {
      begin: '',
      content: '',
      end: '',
    };
    regex.reg = new RegExp(regex.begin + regex.content + regex.end, 'g');
    return regex;
  },
});
```
我已经通过以上demo实现了基本的功能，在预览界面拥有自定义样式，但：

希望能举例一个详细demo，比如引用(>1234)的自定义语法，像引用在换行时，默认会接着引用的样式写，而不是新起一行p标签，并且引用的编辑界面是怎么设置蓝色的字体，让体验和内置的一样。
![image](https://user-images.githubusercontent.com/24655091/221139265-75266e75-a8f1-4a92-909b-c0f8129ac902.png)

目前Readme文档比较简单，希望官网有计划搭建一个在线文档，提高体验以及入门门槛，期待能参与这项工程。

**Comment by sunsonliu** [comment]
收到，我们后续会对自定义语法的demo进行优化~~
不过目前还没有什么 机制去影响左侧编辑区的交互，换行自动补上引用是依靠codemirror的一个插件（应该是continuelist）来实现的，字体颜色也是codemirror默认支持的，所以如果希望扩展左侧编辑器的交互体验，可能需要研究下 codemirror的插件机制。。

**Comment by ColynYu** [comment]
Thanks!

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E6%B3%95

**Comment by sunsonliu** [comment]
自定义语法的文档可以看这里： https://github.com/Tencent/cherry-markdown/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E6%B3%95
