### ISSUE TITLE
Bug report: '*' in unordered list was resolved to Italic mark

### ISSUE THREAD

**Issue by lllllllqw** [Tencent/cherry-markdown#40]
【Describe the bug】
'*' in unordered list was resolved to Italic mark，and break the list

【Expected behavior】
Resolve to an unordered list correctly

【To Reproduce】
Enter these content

```
* 用星号写无序列表，且前一行有星号 * ，后面文字被解析成斜体，且接不上无需列表
* 这是后面一行
```

【Screenshots】
![image](https://user-images.githubusercontent.com/20896515/144349876-96e1461f-39f3-4606-8865-2b4bbde616d2.png)

**Comment by sunsonliu** [comment]
应该是个bug（但我老感觉已经修复过了。。。），我们周末定位下哈
