### ISSUE TITLE
[Bug report]自定义语法后，预览区域不能和编辑区域一样跟随滚动。

### ISSUE THREAD

**Issue by dreamncn** [Tencent/cherry-markdown#403]
**Describe the bug**
在具有大量自定义语法的markdown中，预览区域不能和编辑区域一样跟随滚动。

**To Reproduce**
1. 编写具有自定义语法的markdown

**Expected behavior**
希望编辑区域可以与预览区域同步滚动。

**Environment (please complete the following information):**
 - OS：macOS
 - Browser：Chrome
 - Version：0.8.9

**Screenshots**

<video src="https://user-images.githubusercontent.com/37787014/222755888-659f1e55-17b1-4bf8-88a4-c1c78c60048c.mp4" />

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/223062823-43b704d1-3c58-45bd-9e36-a4170f7c5745.png)

cherry是通过预览区域的data-lines属性来实现同步滚动的。可以尝试使用下面的方式来计算行号：
![image](https://user-images.githubusercontent.com/998441/223063212-d6d2ba04-c8c1-48a1-a495-4470db638031.png)

**Comment by dreamncn** [comment]
感谢感谢，已经解决问题
不过在 [extensions](https://github.com/Tencent/cherry-markdown/blob/main/docs/extensions.md)文档中没有看到有关`data-lines`的说明，倒是在首页看到了下面的写法。希望可以完善下文档。
```js
let BlockSensitiveWordsHook = Cherry.createSyntaxHook('blockSensitiveWords', Cherry.constants.HOOKS_TYPE_LIST.PAR, {
  // Enable caching to protect content
  needCache: true,
  // Pretreatment to avoid external influence
  beforeMakeHtml(str) {
    return str.replace(this.RULE.reg, (match, code) => {
      const lineCount = (match.match(/\n/g) || []).length;
      const sign = this.$engine.md5(match);
      const html = `<div data-sign="${sign}" data-lines="${lineCount + 1}" >***</div>`;
      return this.pushCache(html, sign, lineCount);
    });
  },
  makeHtml(str, sentenceMakeFunc) {
    return str;
  },
  rule(str) {
    return {
      reg: /sensitive words/g,
    };
  },
});
```

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/223609913-813dae68-3d2c-4539-bb2d-2cde7e139f2b.png)
cherry最新版已经增加了`:::`信息面板语法，欢迎尝试哈

**Comment by dreamncn** [comment]
昨天试过了，不过整体风格不是我的菜
个人感觉从语法上来讲
```
::: info title
paragraph
:::
```
这种语法看起来比cherry的`:::`语法更简洁容易阅读
还有后面的大段`++++` 看着好折磨

**Comment by sunsonliu** [comment]
收到，title的形式的确可以优化下

**Comment by sunsonliu** [comment]
> 收到，title的形式的确可以优化下

![image](https://user-images.githubusercontent.com/998441/224604207-bb5db3b8-84e1-457b-89cf-dad51cbf6f13.png)
title的语法已修改
