### ISSUE TITLE
如何构建 `client/scripts/` 中的 js 文件？ 

### ISSUE THREAD

**Issue by yxKryptonite** [Tencent/cherry-markdown#409]
> 抱歉看错了，`/client`目录是一个独立的客户端项目，这里的所有文件都不应该引用外部的文件。可以通过更新`/client/dist`目录里的代码来更新cherry的版本哈。
> 
> _Originally posted by @sunsonliu in https://github.com/Tencent/cherry-markdown/issues/405#issuecomment-1459248162_

我不知道如何从 `src/` 中的文件构建 `client/` 中的相关 bundle，client原作者并没有提供相应的构建脚本，发了邮件还没回orz

**Comment by yxKryptonite** [comment]
主项目和client项目的bundle应该是不一样的，前者的 `cherry-markdown.js` 有80000+行，后者有140000+行

**Comment by sunsonliu** [comment]
不出意外应该是“人工智能”构建同步的。。我找原作者确认下

**Comment by WhenLeo** [comment]
客户端的建设进度有些迟滞，client文件夹下的bundle可能已过时，暂时没有和主项目同步，目前没有能够自动构建主项目到client中的命令。@yxKryptonite

**Comment by RSS1102** [comment]
目前client 已经重新迁移构建了（正在开发中...），比之前开发方式更轻便了，未来有什么疑问或者有什么想法欢迎提出。
