### ISSUE TITLE
[Feature request] 功能请求，对目前正在编辑的区块进行高亮

### ISSUE THREAD

**Issue by hbl917070** [Tencent/cherry-markdown#411]
下面是 [tui-editor](https://ui.toast.com/tui-editor) 的截图
编辑左边的md语法时，右边的预览区会高亮当前正在编辑的地方
这样左右两边在比对会轻松很多

cherry-markdown 有可能实现这样的效果吗

![GIF 2023-3-12 上午 09-25-10](https://user-images.githubusercontent.com/12185698/224519243-b385682d-06d1-4588-8c21-24cc8cba278f.gif)

**Comment by sunsonliu** [comment]
已发布，感谢 @yxKryptonite 的PR
