### ISSUE TITLE
期待能有全屏的选项

### ISSUE THREAD

**Issue by veitool** [Tencent/cherry-markdown#412]
期待能有全屏的功能选项，以及可参数配置文本域的名称

**Comment by sunsonliu** [comment]
收到，“配置文本域的名称”这个是指给textarea增加name属性么？

**Comment by veitool** [comment]
> 收到，“配置文本域的名称”这个是指给textarea添加名称属性吗？

是的，现在好像是以固定code命名。

**Comment by veitool** [comment]
好的，非常感谢！待会用下

**Comment by veitool** [comment]
> 已实现相关功能 1、指定文本域的名称，可以在option里增加对editor的配置
> 
> ```js
> editor: {
>     name: 'cherry-text', // 设置textarea的name属性值
>     autoSave2Textarea: true, // 设置为true后，编辑区的变更会自动同步到textarea里（默认为false）
>   }
> ```
> 
> 2、全屏按钮 ，可以在option里增加对toolbar/toolbarRight的配置
> 
> ```js
> toolbars:{
>     toolbarRight: ['fullScreen'],
> }
> ```
你好，刚下载了 0.8.18 用了下，全屏是可以用了（放在toolbar:['fullScreen',...]中），属性 autoSave2Textarea，toolbarRight 好像在源码中是没有的。
不好意思，是不是还没发布新的？

**Comment by sunsonliu** [comment]
哦哦，是的，还没发布，目前只提交到了dev分支哈，需要发布后才能使用（或者直接使用dev分支的）

**Comment by veitool** [comment]
> 哦哦，是的，还没发布，目前只提交到了dev分支哈，需要发布后才能使用（或者直接使用dev分支的）

好的，那待会下dev里的试下先，谢谢!

**Comment by RSS1102** [comment]
可以查看这个示例体验：https://tencent.github.io/cherry-markdown/examples/multiple.html
