### ISSUE TITLE
[Bug report]getHtml()->makeMarkdown()的问题

### ISSUE THREAD

**Issue by alexwenbj** [Tencent/cherry-markdown#414]
**Describe the bug**

**To Reproduce**
1. md内容如下：
```
test
\`\`\`python
print("helloworld")
\`\`\`
```
2. 使用cherry.getHtml()将渲染的Html代码保存（到数据库）
3. 将保存的HTML代码取出来，使用cherry.setMarkdown(cherry.engine.makeMarkdown(htmlStr))重新设置回markdown中

**Expected behavior**
应该重新得到
```
test
\`\`\`python
print("helloworld")
\`\`\`
```
但实际得到的是：
```
test

      [ ]

       \`print("helloworld")\`
```
**Screenshots**

<img width="964" alt="screenshot" src="https://user-images.githubusercontent.com/12047524/226522713-a1247bba-9fca-4e68-ba82-4bb74f71bb75.png">

**Environment (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]
 - Version [版本 110.0.5481.77（正式版本） (arm64)]

**Comment by alexwenbj** [comment]
\`前的反斜杠是开issue时自己加的。

**Comment by sunsonliu** [comment]
收到，的确把代码块转成markdown的逻辑有问题，我们修复下

**Comment by sunsonliu** [comment]
不过不建议只保存html内容哈，建议DB里同时存markdown和html两个内容：
- markdown内容用来做编辑的回显、甚至是查看页的回显（用cherry的previewOnly模式）；
- html内容用来做导出、发邮件之类的功能

如果还有搜索场景，可以在DB里存一个纯文本内容（`cherry.previewer.getDom().textContent`）

**Comment by alexwenbj** [comment]
> 不过不建议只保存html内容哈，建议DB里同时存markdown和html两个内容：
> 
> * markdown内容用来做编辑的回显、甚至是查看页的回显（用cherry的previewOnly模式）；
> * html内容用来做导出、发邮件之类的功能
> 
> 如果还有搜索场景，可以在DB里存一个纯文本内容（`cherry.previewer.getDom().textContent`）

嗯，是保存了，只是我有旧数据只有HTML格式需要用到。
谢谢！
