### ISSUE TITLE
[Feature request] 图片加载失败时，图片不显示，是否能加一个onerror的事件绑定或者全局设置或者加一个加载失败的占位

### ISSUE THREAD

**Issue by lycoris-xmin** [Tencent/cherry-markdown#417]
图片加载失败时，图片不显示，是否能加一个onerror的事件绑定或者全局设置

![image](https://user-images.githubusercontent.com/43264181/230712217-0f1b1444-cd07-4075-9ce7-fbad801589e4.png)

由于图床崩了，图片直接没了，不显示，也没有占位

我只能全局监听img的error 来暂时处理，是否有现成的配置，我暂时没搜到

**Comment by yxKryptonite** [comment]
好像在中括号内写alt text就会显示占位了？
如：
<img width="1206" alt="截屏2023-04-08 16 53 51" src="https://user-images.githubusercontent.com/94061417/230712917-3a134da1-07a7-4346-8f3a-0fb45076a3dc.png">

不加alt text确实没有占位

**Comment by lycoris-xmin** [comment]
@yxKryptonite  可以自定加载失败后的要加载的图片吗，还是目前没有这个功能。

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/230722501-c67c3192-c449-4b48-9d49-d2f80ad6c0fc.png)
可以通过定义 `lazyLoadImg.failLoadOneImgCallback` 失败时的回调函数来实现对加载失败的图片做特殊处理（如给加载失败的图片src赋值一个裂图的地址）

**Comment by lycoris-xmin** [comment]
@sunsonliu  多谢
