### ISSUE TITLE
在iwiki的cherry markdown调整图片尺寸时窗口不能固定

### ISSUE THREAD

**Issue by phoenixxliu** [Tencent/cherry-markdown#42]
不确定是不是cherry的问题。

在预览窗口调整图片的尺寸时，会出现异常滚动的问题，窗口不固定。导致调整起来很费劲。

**Comment by sunsonliu** [comment]
收到，我们定位下~

**Comment by sunsonliu** [comment]
确认已修复哈，可在iwiki查看，如还有问题欢迎企业微信联系我们，我们看看现场~
