### ISSUE TITLE
在表单中使用若何获取到值

### ISSUE THREAD

**Issue by twtyjvkg** [Tencent/cherry-markdown#423]
如果在表单中使用cherry-markdown，提交表单的时候用什么方法能获取到编辑器的内容呢？

**Comment by sunsonliu** [comment]
https://tencent.github.io/cherry-markdown/examples/api.html
可以参考这个demo哈，另外在设计DB表结构的时候可以参考这个回答：https://github.com/Tencent/cherry-markdown/issues/414#issuecomment-1477341606
