### ISSUE TITLE
期待提供居中, 左对齐, 右对齐

### ISSUE THREAD

**Issue by yimaoe** [Tencent/cherry-markdown#424]
能不能提供居中, 左对齐, 右对齐

**Comment by lyngai** [comment]
请提供更详细的信息。是什么默认居中？

**Comment by RSS1102** [comment]
![image](https://user-images.githubusercontent.com/81673017/232401959-3f4afe25-60fd-403a-9b6b-3c40e86287a5.png)
可能是这样的？参考wold文档功能。

**Comment by yimaoe** [comment]
就是类似于word 中的居中, 左对齐, 右对齐.

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/233894998-a8ccfd8d-60c6-4e69-a50e-7fb3e4ec0c27.png)

已实现并提交到dev分支
