### ISSUE TITLE
增加输入联想功能

### ISSUE THREAD

**Issue by sunsonliu** [Tencent/cherry-markdown#430]
## 背景
cherry提供了suggester机制，可以实现类似 输入@后给出联想的能力（见下图）
![image](https://user-images.githubusercontent.com/998441/233289505-fc48ce71-5d78-4bf5-87f6-1c0a96a76fe5.png)

## 需求 
利用现有的suggester机制实现特定符号给出联想的功能（如notion输入 /就会给出联想）
![image](https://user-images.githubusercontent.com/998441/233289939-64d7dffe-4c88-4dd3-ba96-6f851275f461.png)

- 希望提供输入#号（具体符号可配置），联想出各种功能（可配置）
![image](https://user-images.githubusercontent.com/998441/233293912-2353b28b-94da-490a-8556-940fcd344dd0.png)
- 希望提供输入| 竖线，联想出表格
![image](https://user-images.githubusercontent.com/998441/233292818-46d7bc74-9267-4a66-a8a5-064fa5d8d569.png)

**Comment by ufec** [comment]
#473

**Comment by ufec** [comment]
#473 @sunsonliu
