### ISSUE TITLE
实现checklist所见即所得编辑能力

### ISSUE THREAD

**Issue by sunsonliu** [Tencent/cherry-markdown#432]
## 需求 
实现checklist所见即所得编辑能力
![image](https://user-images.githubusercontent.com/998441/233302357-74e89b58-a0ca-43ca-adee-898023dae80e.png)

**Comment by jokerwyt** [comment]
正在企图实现这个功能，目前的思路是这样的：
1. 在Previewer bubble的onClick事件里，检查是不是checkbox被click了
2. 然后到Editor去更新他。
有一个问题，找了挺久不知道怎么解决：如何找到鼠标点击的checkbox对应的 `- [ ]`，并更新成`- [ ]`。需要用到哪些API呢
