### ISSUE TITLE
预览区域代码块可切换语言

### ISSUE THREAD

**Issue by sunsonliu** [Tencent/cherry-markdown#433]
## 背景
目前预览区域代码块已支持复制代码的能力
![image](https://user-images.githubusercontent.com/998441/233303830-e0ab689c-6791-4c4b-a20f-4a844fb51996.png)

## 需求 
1. hover代码块时回显代码块的语言
![image](https://user-images.githubusercontent.com/998441/233305327-b3e8e6c6-7343-4e55-868d-4f58786de0d4.png)
2. 编辑代码块语言（仅在双栏编辑模式下生效）
![image](https://user-images.githubusercontent.com/998441/233305847-d0dbf5b2-b845-4e80-b723-1866f303c71d.png)

**Comment by tangzixuan** [comment]
> ## 背景
> 目前预览区域代码块已支持复制代码的能力 ![image](https://user-images.githubusercontent.com/998441/233303830-e0ab689c-6791-4c4b-a20f-4a844fb51996.png)
> 
> ## 需求
> 1. hover代码块时回显代码块的语言
>    ![image](https://user-images.githubusercontent.com/998441/233305327-b3e8e6c6-7343-4e55-868d-4f58786de0d4.png)
> 2. 编辑代码块语言（仅在双栏编辑模式下生效）
>    ![image](https://user-images.githubusercontent.com/998441/233305847-d0dbf5b2-b845-4e80-b723-1866f303c71d.png)
@sunsonliu , hello, 我想确认下第二点，在预览区域修改选择新的语言后，markdown内容文本中的代码块内容的语言设置项需要修改嘛
![截屏2023-06-01 08 47 17](https://github.com/Tencent/cherry-markdown/assets/51657124/03ce7859-729b-4a21-8da1-73c79611f7dd)

**Comment by sunsonliu** [comment]
是的，markdown内容中的语言设置项也是需要修改的哈，选中并修改markdown内容的逻辑可以参考预览区[表格编辑](https://github.com/Tencent/cherry-markdown/blob/main/src/utils/tableContentHander.js#L194)、[图片尺寸编辑](https://github.com/Tencent/cherry-markdown/blob/main/src/toolbars/PreviewerBubble.js#L311)~

**Comment by tangzixuan** [comment]
> 2\. @sunsonliu , hello, 我想确认下第二点，在预览区域修改选择新的语言后，markdown内容文本中的代码块内容的语言设置项需要修改嘛

好的，明白了~
