### ISSUE TITLE
vscode插件支持配置图床

### ISSUE THREAD

**Issue by sunsonliu** [Tencent/cherry-markdown#434]
## 背景
Cherry已实现vscode插件，插件中实现了配置主题的功能，切换主题时也会修改配置
![image](https://user-images.githubusercontent.com/998441/233308799-46a82f06-fcb7-4dca-ae5e-397739a86b91.png)

## 需求
希望增加配置图床的功能，配置图床后，用户上传图片会上传到图床

**Comment by ufec** [comment]
#534
