### ISSUE TITLE
[Bug report] 工具条设置sidebar: false 失效

### ISSUE THREAD

**Issue by colynyu** [Tencent/cherry-markdown#439]
**Describe the bug**
工具条设置sidebar: false 失效

**To Reproduce**
 "cherry-markdown": "^0.8.18",
 "vue": "^3.2.47"

https://stackblitz.com/edit/vitejs-vite-u6pfjo?file=src/App.vue

以下是源码的类型定义
![image](https://user-images.githubusercontent.com/24655091/233831557-67aaabf9-180f-46b3-a80a-3d1a3b38dd89.png)

**Comment by RSS1102** [comment]
目前你可以先用空数组`[]`替代false试试？
后续再看是什么问题。

**Comment by sunsonliu** [comment]
感谢反馈，已修复并提交到dev分支
