### ISSUE TITLE
分割线误将上一行渲染成h2

### ISSUE THREAD

**Issue by Elitedj** [Tencent/cherry-markdown#44]
下面这一段语法渲染不符合预期

```
啊啊啊
--------
```

渲染效果：

![image](https://user-images.githubusercontent.com/37628192/144997933-36a9e923-b315-44a7-80c6-273600ee3539.png)

**Comment by lyngai** [comment]
你好，这个是符合预期的。标题语法有两种，以 `#` 开头的是 atx 风格的 header；内容后跟 `===` 或 `---` 是 setext 风格的 header。

---

避免渲染为标题请在中间加空行

```markdown
header
---

分隔符

---

分隔符
```

**Comment by Elitedj** [comment]
学习了

**Comment by sunsonliu** [comment]
嗯嗯，这个是**设计如此**哈，是md的标准规范要求的，不过仔细想了下，这种**标准规范**也不见得有道理，我们内部讨论下有没有必要遵守这种规范。

```
下面是＝号的时候是一级标题
=======

下面是-号的时候是二级标题
----------
```
下面是＝号的时候是一级标题
=======

下面是-号的时候是二级标题
----------
