### ISSUE TITLE
用了主分支中的v0.8.18版和dev中的v0.8.19全屏功能对比

### ISSUE THREAD

**Issue by veitool** [Tencent/cherry-markdown#441]
v0.8.18 中的全屏是网页的全屏，全屏后是可以正常调用其他弹窗（比如图库弹窗选择插入图片），不会出现层级z-index的问题。这个正是想要的全屏功能。
v0.8.19 中的全屏是屏幕的全屏，全屏后，调用自定义弹窗时就会被遮住。

**Comment by sunsonliu** [comment]
全屏问题已修复，感谢 @RSS1102
