### ISSUE TITLE
[draw.io]  支持拖动

### ISSUE THREAD

**Issue by RSS1102** [Tencent/cherry-markdown#442]
**Is your feature request related to a problem? Please describe.**
希望 **cherry-dialog** 能支持拖动，因为在某些情况下，屏幕的分辨率可能有点小，不能完全展示弹窗，以至于对于操作`draw.io`产生困扰。

** What does the proposed API look like**
A clear and concise description of how you propose to solve the problem or provide code samples of how the API would work once implemented.

以在弹窗的head部分默认开启[draw.io]  支持拖动功能。

**Additional context**
![_FB%@GZFKP0P30LUA1W2}9N](https://user-images.githubusercontent.com/81673017/234161288-2081f91e-b8ee-4f05-bd67-34feeaa30f95.png)

**Comment by ArunVR2112** [comment]
Hey I am Not Understanding What need to be done so can just explain it to me in English

**Comment by RSS1102** [comment]
> 嘿，我不明白需要做什么，所以可以用英语向我解释一下
Sorry, let me explain to you.
1. Support a drag and drop effect in the red position, which allows draw.io to be placed in different positions to prevent issues caused by incomplete pages.
