### ISSUE TITLE
[Feature request]如何访问有权限的图片

### ISSUE THREAD

**Issue by yimaoe** [Tencent/cherry-markdown#449]
比如有一张图，需要有请求头有令牌才能访问到， 怎么样才能实现在访问或者预览的时候携带令牌该图片。 
正常情况下， 上传图片 -》 上传到后端 -》后端返回 URL-》插入到markdown 中， 后端接口在收到请求会查看令牌， 现在怎么才能在预览 markdown 的时候自动携带令牌去请求呢
      const headers = {
        'Authorization': 'Bearer ' + accessToken,
      };

**Comment by sunsonliu** [comment]
令牌一般会以以下三种方式存放：
1、存session
2、存cookie
3、以参数的形式放在img标签的src属性里（如`<img src="/img.png?token=accessToken">`)
如果是前两种，则md里不需要特殊处理。
如果是第三种，则又分以下两种情况：
1、每张图片的accessToken一样但不固定（一般过段时间accessToken会刷新），这种需要在把markdown源码数据交给cherry前进行预处理（一般是用正则统一给每个图片语法的url里追加token信息）
2、每张图片的accessToken不一样但固定（一般是根据图片的相关信息生成的token），这种需要在配置的 `fileUpload`的回调函数里做统一个追加。

至于直接往headers里追加token的情况，应该是可以考虑改成上述的三种方案之一的

**Comment by yimaoe** [comment]
如果是想用 headers = {
'Authorization': 'Bearer ' + accessToken,
}; 这种怎么实现呢.
