### ISSUE TITLE
疑似自动编号带来的渲染问题

### ISSUE THREAD

**Issue by Elitedj** [Tencent/cherry-markdown#45]
疑似自动编号带来的渲染问题，具体的表现和操作见图，不知道这种渲染效果是否是符合预期的？

![image](https://user-images.githubusercontent.com/37628192/145041586-bb9e34ca-e741-460a-b35a-2a2df95efdc2.png)

![cherry](https://user-images.githubusercontent.com/37628192/145043663-955176b8-2bea-4380-b024-c8915dd0ca34.gif)

**Comment by jiawei686** [comment]
收到，看起来list语法算法对空行的处理存在问题，我来定位下

**Comment by sunsonliu** [comment]
hello, 这个issue比较有价值，请问是腾讯员工吗，如果是的话可以联系一下我：）

**Comment by jiawei686** [comment]
Hi，列表算法已在#76 中进行修复，变更已在0.6.1版本中发布，感谢反馈！
