### ISSUE TITLE
[Bug report] 暗黑主题下，PDF导出背景仍然是亮色

### ISSUE THREAD

**Issue by jokerwyt** [Tencent/cherry-markdown#456]
![image](https://github.com/Tencent/cherry-markdown/assets/11886705/a4803134-b9ca-4395-9a31-718c74067a4e)

**Comment by sunsonliu** [comment]
感谢反馈，搞主题的时候没有考虑导出的场景，我们后面尝试修复下~

**Comment by IceAndIce** [comment]
您好，我尝试修复了这个bug。我在getReadyToExport里面加入了一个函数：
![image](https://github.com/Tencent/cherry-markdown/assets/93379036/7800cfc0-a000-4b4b-b1ed-3f2a3de68c60)
它可以有效的修复这个问题：
![image](https://github.com/Tencent/cherry-markdown/assets/93379036/67c1a948-3dee-41f1-b004-232dc9110e1c)
希望您能采纳

**Comment by IceAndIce** [comment]
> 感谢反馈，搞主题的时候没有考虑导出的场景，我们后面尝试修复下~
您好，我尝试修复了这个bug。我在getReadyToExport里面加入了一个函数：
image
它可以有效的修复这个问题：
image
希望您能采纳

**Comment by IceAndIce** [comment]
您好，我尝试修复了这个bug。我在getReadyToExport里面加入了一个函数：
![251495230-7800cfc0-a000-4b4b-b1ed-3f2a3de68c60](https://github.com/Tencent/cherry-markdown/assets/93379036/97b82644-5f9f-4175-9fa3-f85d34e2ed14)
它可以有效的修复这个问题：
![251495466-67c1a948-3dee-41f1-b004-232dc9110e1c](https://github.com/Tencent/cherry-markdown/assets/93379036/01ff2619-c642-40a1-bf20-e73be42c04a0)
希望您能采纳

**Comment by IceAndIce** [comment]
> 感谢反馈，搞主题的时候没有考虑导出的场景，我们后面尝试修复下~

您好，我尝试修复了这个bug。我在getReadyToExport里面加入了一个函数：
![251495230-7800cfc0-a000-4b4b-b1ed-3f2a3de68c60](https://github.com/Tencent/cherry-markdown/assets/93379036/879a756d-81d9-46ed-b6a7-1ae945cf1ba0)
它可以有效的修复这个问题：
![251495466-67c1a948-3dee-41f1-b004-232dc9110e1c](https://github.com/Tencent/cherry-markdown/assets/93379036/a4f17ff7-ce7e-471d-b9e8-ddcccd506250)
希望您能采纳

**Comment by sunsonliu** [comment]
> > 感谢反馈，搞主题的时候没有考虑导出的场景，我们后面尝试修复下~
> 
> 您好，我尝试修复了这个bug。我在getReadyToExport里面加入了一个函数： ![251495230-7800cfc0-a000-4b4b-b1ed-3f2a3de68c60](https://user-images.githubusercontent.com/93379036/251530941-879a756d-81d9-46ed-b6a7-1ae945cf1ba0.png) 它可以有效的修复这个问题： ![251495466-67c1a948-3dee-41f1-b004-232dc9110e1c](https://user-images.githubusercontent.com/93379036/251530990-a4f17ff7-ce7e-471d-b9e8-ddcccd506250.png) 希望您能采纳

哈哈，感谢分享~欢迎给我们提pr哈，提到dev分支就好~~

**Comment by RSS1102** [comment]
fixd by :https://github.com/Tencent/cherry-markdown/pull/507
