### ISSUE TITLE
关于cherry发展的一点疑问

### ISSUE THREAD

**Issue by dreamncn** [Tencent/cherry-markdown#458]
我发现cherry朝着一个很奇怪的方向发展了，我本以为cherry会是一个由基础md语法支撑通过插件进行拓展的工具，我有两点不明白：
1. 内置超多的自定义语法
明明支持语法拓展，为什么不把选择的权力交给开发者？
2. 加入chatgpt
这在一个markdown编辑器中似乎不是必备的功能

**Comment by sunsonliu** [comment]
感谢提问，也欢迎继续深入探讨~

**首先**分享下我们对cherry的一些认知或期望：
cherry的定位是“*做一个功能丰富、开箱即用、易于扩展的开源前端markdown编辑器组件*”，在这个定位中有以下几个关键词和对应的影响：
- 功能丰富
意味着cherry需要实现大部分常见的markdown语法（如加粗、表格、流程图）和常见的编辑器功能（如工具栏、导出、主题），同时还要实现一些不常见但的确有用的语法（如字体颜色、toc目录、信息面板）和编辑器功能（如复制html自动转义成markdown、拖拽文件到编辑器上传、图片懒加载）
- 开箱即用
意味着cherry要提供多种场景的“[两三行代码引入](https://github.com/Tencent/cherry-markdown/tree/main/dist)”的方案（如不需要编辑器只需要markdown转html的场景、非浏览器场景）；同时也要提供丰富的[配置能力](https://github.com/Tencent/cherry-markdown/blob/main/src/Cherry.config.js)（如配置允许渲染的HTML标签、代码块是否显示行号、预览区要不要跟随编辑区光标滚动）
- 易于扩展
对于易于扩展又分两个场景：
    - 引入cherry后再扩展
    意味着cherry需要具备一套[插件机制](https://github.com/Tencent/cherry-markdown/blob/main/examples/scripts/index-demo.js)，包括工具栏扩展机制和语法扩展机制
    - 先定制cherry，再在业务侧引入
    意味着cherry需要提供一套易于定制[工具栏](https://github.com/Tencent/cherry-markdown/blob/main/src/toolbars/HookCenter.js)和[语法能力](https://github.com/Tencent/cherry-markdown/blob/main/src/core/HooksConfig.js)的机制
- 前端组件
意味着cherry要用原生js实现，并提供[API](https://tencent.github.io/cherry-markdown/examples/api.html)，同时要保证尽可能高的[性能](https://github.com/Tencent/cherry-markdown/blob/main/docs/features.md#performance-features)


**接下来**在这种认知或期望下，我们尝试回答dream的两个问题：
1. 内置超多的自定义语法
这个一方面是在功能丰富和易于扩展的期望下慢慢演变而来的，另一方面也是在我们希望弯道超车尽力追赶第一梯队的动机下而产生的（想象一下，同样的价钱别人只提供个汉堡，连番茄酱都要额外买，我们直接全家桶不谢）
2. 加入chatgpt
这个功能并不是cherry的必备功能，即便实现了也只是以一个配置项的能力开放出来。用户用编辑器是用来写文章的，写文章自然会有续写、总结、名词解释、美化等一系列gpt交互操作，就一旦我们具备了这个配置能力，那就相当于我们不但提供了全家桶还是个鸡翅侠

**最后**，如果用cherry来写上述内容，大概会看到这样的效果（并没有拉踩，也不是引战，主要是有些用户可能需要这样的效果）
![image](https://github.com/Tencent/cherry-markdown/assets/998441/a0b27cd3-6741-4146-8af6-18b0982ba367)

**Comment by dreamncn** [comment]
这个定位很奇怪。
一个markdown编辑器，如果想要接入到不同的平台，那一定是需要开发者做深度定制的。

你们提前给开发者完成了这段**深度定制**的过程，那么留给开发者的自由度就太小了。像你们内置的`:::`语法，可能就会和开发者真实想实现的功能冲突。

对于这些额外的内容倒是可以直接做成拓展包进行引用而不是直接内嵌，应该最大化的发挥插件的功能，对不必要的功能进行解耦，后期维护也更方便。

**Comment by sunsonliu** [comment]
哦哦，你说的这种可以用二开的方式解决，可以通过修改 [配置文件](https://github.com/Tencent/cherry-markdown/blob/main/src/core/HooksConfig.js) 来实现。


语法分行内语法、段落语法，同时语法又有排他（如代码块）、不排他、有限排他三种情况，同时语法的渲染先后顺序也是需要取舍的。把这些判断完全交给开发者，无疑会让开发者头大。


所以在你说的场景里，我们首先提供了全家桶，开发者如果不希望`:::`语法，可以去到配置文件里注释掉就好了：
![image](https://github.com/Tencent/cherry-markdown/assets/998441/d60d066f-414a-4ac3-9e4f-d1de4334c6a5)

**Comment by jiakuan** [comment]
通过配置的方法也很不错。如果充分利用插件机制的话，不需要的功能有可能就不需要加载，最终的加载文件大小会不会更小？

**Comment by jokerwyt** [comment]
感觉应该多做做减法，不要随意添加太多不实用的功能。如果要添加的话，应该有一个默认不开启的option，交给用户选择。
挺多markdown用户还是很重视简洁的，如果第一眼的界面太杂乱，挺劝退的

**Comment by sunsonliu** [comment]
> 通过配置的方法也很不错。如果充分利用插件机制的话，不需要的功能有可能就不需要加载，最终的加载文件大小会不会更小？

通过注释配置重新构建的方法的确会让文件体积变小~

**Comment by sunsonliu** [comment]
> 感觉应该多做做减法，不要随意添加太多不实用的功能。如果要添加的话，应该有一个默认不开启的option，交给用户选择。 挺多markdown用户还是很重视简洁的，如果第一眼的界面太杂乱，挺劝退的

额，配置菜单和配置语法功能是两个不同的场景，我们提供了非常便捷的配置菜单的能力，业务方也是可以根据喜好进行自由配置的，如下：
```
new Cherry({
  id: 'markdown',
  toolbars:{
    toolbar: ['bold', '|', 'header', 'list', {insert: ['image', 'hr', 'toc',]}],
    bubble: ['bold', 'italic', 'strikethrough'],
  },
  value: value,
});
```
![image](https://github.com/Tencent/cherry-markdown/assets/998441/1723bcbf-568f-4170-b574-33601995bb29)

**Comment by yxl** [comment]
markdown 与 chatgpt 是天作之合，大有可为。我是强烈支持加入 chatgpt的。
markdown非常适合展示 chatgpt 这类大语言模型的输出结果，同时也方便大语言模型理解用户的输入。随着大语言模型和通用人工智能的普及，我们特别需要一个通用的基于文本的可理解的数据展示和传输标准，个人觉得 markdown尤其是扩展形 markdown是非常合适的形式。
希望这个项目能在标准化上越走越强。

**Comment by dreamncn** [comment]
做面向开发者的开源项目就应该给与足够的自由度，像做产品一样条条框框不如直接做个闭源产品。
要插件机制，就应该充分利用插件机制，什么乱七八糟的功能全部由插件实现。
像现在这样犹抱琵琶半遮面的，只会让这个项目本身越来越混乱。
开发者自己应当有自己的考量，不能被用户带着跑。

**Comment by j4587698** [comment]
为什么一定要定制呢？对很多开发者来说，就是需要一款功能丰富，开箱即用的markdown编辑器而已。作为一款编辑器，能开箱即用，一个js一个css，然后几行js就能跑起来多么舒服？为啥非要配置一大堆插件，做一大堆无用的操作才能实现呢？你这整个思路就是错的啊，开发者就不需要一个产品了嘛？非要是一个半成品才行？

**Comment by dreamncn** [comment]
> 为什么一定要定制呢？对很多开发者来说，就是需要一款功能丰富，开箱即用的markdown编辑器而已。作为一款编辑器，能开箱即用，一个js一个css，然后几行js就能跑起来多么舒服？为啥非要配置一大堆插件，做一大堆无用的操作才能实现呢？你这整个思路就是错的啊，开发者就不需要一个产品了嘛？非要是一个半成品才行？

提issue的目的不是为了争辩谁对谁错，这没有意义，萝卜青菜各有所爱。

对你的几个问号的回答：

> 1. 为什么一定要定制呢？

没有为什么，本身cherry也提供了一大堆可选的选项，配置选项不比进行定制简单。

> 2. 对很多开发者来说，就是需要一款功能丰富，开箱即用的markdown编辑器而已。作为一款编辑器，能开箱即用，一个js一个css，然后几行js就能跑起来多么舒服？

且不说你这个`对很多开发者来说`有没有可靠的佐证。一个合格的markdown编辑器即便不进行定制也可以开箱即用，可以参考富文本编辑器wangeditor

> 3. 为啥非要配置一大堆插件，做一大堆无用的操作才能实现呢？

同2，合格的markdown编辑器应该提供基本的功能，不需要一大堆无用的操作实现。而且你的表述存在矛盾，既然是**无用操作**，那怎么可能实现功能。

> 4. 你这整个思路就是错的啊，开发者就不需要一个产品了嘛？非要是一个半成品才行？

说句难听的，既然你需要产品，那你开发个P，直接做C端用户好了。

你自己去琢磨琢磨，现在cherry内置的一大堆语法，如果是自用你会用到几个？如果是给用户使用，用户会用到几个？另外给用户使用还需要提升用户学习成本。

**Comment by j4587698** [comment]
> > 为什么一定要定制呢？对很多开发者来说，就是需要一款功能丰富，开箱即用的markdown编辑器而已。作为一款编辑器，能开箱即用，一个js一个css，然后几行js就能跑起来多么舒服？为啥非要配置一大堆插件，做一大堆无用的操作才能实现呢？你这整个思路就是错的啊，开发者就不需要一个产品了嘛？非要是一个半成品才行？
> 
> 提issue的目的不是为了争辩谁对谁错，这没有意义，萝卜青菜各有所爱。
> 
> 对你的几个问号的回答：
> 
> > 1. 为什么一定要定制呢？
> 
> 没有为什么，本身cherry也提供了一大堆可选的选项，配置选项不比进行定制简单。
> 
> > 2. 对很多开发者来说，就是需要一款功能丰富，开箱即用的markdown编辑器而已。作为一款编辑器，能开箱即用，一个js一个css，然后几行js就能跑起来多么舒服？
> 
> 且不说你这个`对很多开发者来说`有没有可靠的佐证。一个合格的markdown编辑器即便不进行定制也可以开箱即用，可以参考富文本编辑器wangeditor
> 
> > 3. 为啥非要配置一大堆插件，做一大堆无用的操作才能实现呢？
> 
> 同2，合格的markdown编辑器应该提供基本的功能，不需要一大堆无用的操作实现。而且你的表述存在矛盾，既然是**无用操作**，那怎么可能实现功能。
> 
> > 4. 你这整个思路就是错的啊，开发者就不需要一个产品了嘛？非要是一个半成品才行？
> 
> 说句难听的，既然你需要产品，那你开发个P，直接做C端用户好了。
> 
> 你自己去琢磨琢磨，现在cherry内置的一大堆语法，如果是自用你会用到几个？如果是给用户使用，用户会用到几个？另外给用户使用还需要提升用户学习成本。

这一堆配置你完全可以用默认，为什么非要配置？
至于你说的表述矛盾更是无稽之谈，我的意思是我就要全家桶，明明可以直接一个js搞定，你非要加一堆配置，一堆插件，然后实现相同的功能，这不是无用操作是什么？

很多开发者需要佐证吗？你随便找个后台管理系统，或者需要做编辑的系统，有几个定制了？不都是拿来就用？
你找出几个专门定制用的系统看看？

至于用户，他用可以用，不用有什么影响？换句话说，我可以不用，但是你不能没有。

**Comment by dreamncn** [comment]
> > > 为什么一定要定制呢？对很多开发者来说，就是需要一款功能丰富，开箱即用的markdown编辑器而已。作为一款编辑器，能开箱即用，一个js一个css，然后几行js就能跑起来多么舒服？为啥非要配置一大堆插件，做一大堆无用的操作才能实现呢？你这整个思路就是错的啊，开发者就不需要一个产品了嘛？非要是一个半成品才行？
> > 
> > 
> > 提issue的目的不是为了争辩谁对谁错，这没有意义，萝卜青菜各有所爱。
> > 对你的几个问号的回答：
> > > 1. 为什么一定要定制呢？
> > 
> > 
> > 没有为什么，本身cherry也提供了一大堆可选的选项，配置选项不比进行定制简单。
> > > 2. 对很多开发者来说，就是需要一款功能丰富，开箱即用的markdown编辑器而已。作为一款编辑器，能开箱即用，一个js一个css，然后几行js就能跑起来多么舒服？
> > 
> > 
> > 且不说你这个`对很多开发者来说`有没有可靠的佐证。一个合格的markdown编辑器即便不进行定制也可以开箱即用，可以参考富文本编辑器wangeditor
> > > 3. 为啥非要配置一大堆插件，做一大堆无用的操作才能实现呢？
> > 
> > 
> > 同2，合格的markdown编辑器应该提供基本的功能，不需要一大堆无用的操作实现。而且你的表述存在矛盾，既然是**无用操作**，那怎么可能实现功能。
> > > 4. 你这整个思路就是错的啊，开发者就不需要一个产品了嘛？非要是一个半成品才行？
> > 
> > 
> > 说句难听的，既然你需要产品，那你开发个P，直接做C端用户好了。
> > 你自己去琢磨琢磨，现在cherry内置的一大堆语法，如果是自用你会用到几个？如果是给用户使用，用户会用到几个？另外给用户使用还需要提升用户学习成本。
> 
> 这一堆配置你完全可以用默认，为什么非要配置？ 至于你说的表述矛盾更是无稽之谈，我的意思是我就要全家桶，明明可以直接一个js搞定，你非要加一堆配置，一堆插件，然后实现相同的功能，这不是无用操作是什么？
> 
> 很多开发者需要佐证吗？你随便找个后台管理系统，或者需要做编辑的系统，有几个定制了？不都是拿来就用？ 你找出几个专门定制用的系统看看？
> 
> 至于用户，他用可以用，不用有什么影响？换句话说，我可以不用，但是你不能没有。

夏虫不可语冰。
思维逻辑都理不清楚，按照你这种思维做产品，能做好才怪了。

**Comment by j4587698** [comment]
理屈词穷开始夏虫不可语冰了？

你觉得有问题咱们举例啊，你去github、gitee找cms、blog、后台管理系统这种需要富文本编辑器的，真正的高端玩家比如wp人家是自己写编辑器的。除了这种高端玩家，剩下的用现成的文本编辑器的，有几个做了你所谓的高端定制？能举几个例子嘛？别说那种自己做了几个插件的就算哈。

富文本编辑器已经算是比较上游的东西了，像富文本编辑器，组件库，还有工作流什么的。这些东西对下游开发者来说在一定程度上就是产品，下游开发者大部分情况下需要的就是一个界面漂亮，许可证宽松，足够稳定的产品，而不是什么专属定制。

上面人家开发者也说了，你真的需要专属定制可以自己编译源码，什么人即不会编译源码，还能专属定制？反正我想不出来，你是大佬你给个例子？

**Comment by dreamncn** [comment]
> 理屈词穷开始夏虫不可语冰了？
> 
> 你觉得有问题咱们举例啊，你去github、gitee找cms、blog、后台管理系统这种需要富文本编辑器的，真正的高端玩家比如wp人家是自己写编辑器的。除了这种高端玩家，剩下的用现成的文本编辑器的，有几个做了你所谓的高端定制？能举几个例子嘛？别说那种自己做了几个插件的就算哈。
> 
> 富文本编辑器已经算是比较上游的东西了，像富文本编辑器，组件库，还有工作流什么的。这些东西对下游开发者来说在一定程度上就是产品，下游开发者大部分情况下需要的就是一个界面漂亮，许可证宽松，足够稳定的产品，而不是什么专属定制。
> 
> 上面人家开发者也说了，你真的需要专属定制可以自己编译源码，什么人即不会编译源码，还能专属定制？反正我想不出来，你是大佬你给个例子？

都说你思维不清了还在这狡辩，我们这是在讨论问题，不是来争吵分个对错。

我不同意但是尊重你的看法，倒也不必如此激动到咄咄逼人。

不过有一点倒是对的，cherry我会考虑进行二开。

**Comment by sunsonliu** [comment]
> 为什么一定要定制呢？对很多开发者来说，就是需要一款功能丰富，开箱即用的markdown编辑器而已。作为一款编辑器，能开箱即用，一个js一个css，然后几行js就能跑起来多么舒服？为啥非要配置一大堆插件，做一大堆无用的操作才能实现呢？你这整个思路就是错的啊，开发者就不需要一个产品了嘛？非要是一个半成品才行？


哈哈哈，非常认同`一个js一个css，然后几行js就能跑起来多么舒服？为啥非要配置一大堆插件，做一大堆无用的操作才能实现呢？`这句话。楼上两位也消消气，两位说的都有道理的。

Cherry一直坚持“**开箱即用**、**易于扩展**、**持续进化**”。
- 为了实现“开箱即用”，我们做到了尽可能的集成（比如把字体颜色、字号这种其他md编辑器都不会有的语法都集成了进来）
- 与此同时为了更方便“易于扩展”，我们又做了插件机制（业务方在引入cherry后进行扩展）和Hook机制（直接对cherry源码进行二开）来满足不同的扩展场景
- （持续进化就不说了，就是让这个项目好好的活着）。

这里开箱即用和易于扩展的**边界**其实是非常难界定的（比如字体颜色、上下标、信息面板这类语法到底要不要以插件的形式来实现），两位的分歧也是在这里，一位认为 _标准md语法外的所有语法都应该以插件的形式实现_ ，一位认为 _cherry自身提供的语法就没必要以插件的形式再引入了_ 。这里我们内部也是有分歧的，有一部分同学认为我们最近实现的信息面板、左中右对齐、手风琴语法应该放插件里，至于之前实现的诸如字体颜色、checklist这类语法就继续集成。

我的观点是（真的是我自己的观点，我们团队其他人都不是这个观点来着）：
1. 在不影响已经引入cherry的业务功能的前提下，现有的这些语法功能怎么布置爱谁谁（总不能用户用着信息面板语法好好的，结果一更新cherry版本语法没有了，需要让用户修改代码手动引入插件吧）
2. 我自己实现的语法我会争取都集成进默认能力里（我可不想好不容易实现的功能还需要用户更新完cherry后再捏着鼻子手动引入进来）
3. cherry主打的就是给的多，实惠。同样几行代码引入cherry，我们的开箱即用那必须得给用户安排明白了嗷，什么字体颜色、信息面板、图片大小啥的语法肯定都默认提供的（总不能用户看了demo很满意，引进来一看要啥没啥还要重新去翻文档吧）

所以两位也不用纠结啦（毕竟每个人都有自己的看法，要说服别人是很难的，我宁愿去做一些简单的事），只要cherry还在不断进化，即便多走一个弯路产生一些像阑尾一样的废物器官又能如何，只要还活着还有活力就会有希望（实在不行就像codemirror那样直接搞个不向下兼容的新版本出来）。

**Comment by AnkioTomas** [comment]
Hi，各位：
时隔1年，我对cherry-markdown进行了二开，仓库：https://github.com/AnkioTomas/cherry-muse
在线体验：https://cherry-muse.vercel.app/examples/index.html

**Comment by AnkioTomas** [comment]
> > Hi，各位： 时隔1年，我对cherry-markdown进行了二开，仓库：https://github.com/AnkioTomas/cherry-muse 在线体验：https://cherry-muse.vercel.app/examples/index.html
> 
> 好漂亮啊！看着整个人都舒爽了~ 可否允许我们把这套主题抄过来，在cherry-markdown这里增加个叫muse的主题？

可以

**Comment by AnkioTomas** [comment]
Hi All
我放弃二开了，改自研了 https://github.com/AnkioTomas/penna-markdown
在线Demo https://penna-markdown.vercel.app/demo/index.html

**Comment by sunsonliu** [comment]
> Hi All 我放弃二开了，改自研了 https://github.com/AnkioTomas/penna-markdown 在线Demo https://penna-markdown.vercel.app/demo/index.html

太强了！许多语法都非常有创意
