### ISSUE TITLE
点击超链接是否可支持新窗口打开？

### ISSUE THREAD

**Issue by ZJQ0925** [Tencent/cherry-markdown#459]
想请问下：后续版本是否可以支持到点击超链接在新窗口打开，或者是有没有什么方案可以在现有版本上做到点击超链接在新窗口打开的？

**Comment by RSS1102** [comment]
是想要这种形式嘛？https://tencent.github.io/cherry-markdown/examples/multiple.html#%E4%BE%8B%E5%AD%90

**Comment by ZJQ0925** [comment]
> 是想要这种形式嘛？https://tencent.github.io/cherry-markdown/examples/multiple.html#%E4%BE%8B%E5%AD%90

是的，请教一下实现方案

**Comment by RSS1102** [comment]
> > 是想要这种形式嘛？https://tencent.github.io/cherry-markdown/examples/multiple.html#%E4%BE%8B%E5%AD%90
> 
> 是的，请教一下实现方案

参考这个试一下：https://github.com/Tencent/cherry-markdown/blob/main/examples/markdown/basic.md?plain=1#L1-L13

**Comment by ZJQ0925** [comment]
> > > 是想要这种形式嘛？https://tencent.github.io/cherry-markdown/examples/multiple.html#%E4%BE%8B%E5%AD%90
> > 
> > 
> > 是的，请教一下实现方案
> 
> 参考这个试一下：https://github.com/Tencent/cherry-markdown/blob/main/examples/markdown/basic.md?plain=1#L1-L13

我看是在超链接后配置{target=_blank}，但是{target=_blank}在其他解析器下无法正常解析了

**Comment by RSS1102** [comment]
> > > > 是想要这种形式嘛？https://tencent.github.io/cherry-markdown/examples/multiple.html#%E4%BE%8B%E5%AD%90
> > > 
> > > 
> > > 是的，请教一下实现方案
> > 
> > 
> > 参考这个试一下：https://github.com/Tencent/cherry-markdown/blob/main/examples/markdown/basic.md?plain=1#L1-L13
> 
> 我看是在超链接后配置{target=_blank}，但是{target=_blank}在其他解析器下无法正常解析了

在纯Markdown环境中，是不支持这种写法的。只能在网页上使用。

**Comment by ZJQ0925** [comment]
> > > > > 是想要这种形式嘛？https://tencent.github.io/cherry-markdown/examples/multiple.html#%E4%BE%8B%E5%AD%90
> > > > 
> > > > 
> > > > 是的，请教一下实现方案
> > > 
> > > 
> > > 参考这个试一下：https://github.com/Tencent/cherry-markdown/blob/main/examples/markdown/basic.md?plain=1#L1-L13
> > 
> > 
> > 我看是在超链接后配置{target=_blank}，但是{target=_blank}在其他解析器下无法正常解析了
> 
> 在纯Markdown环境中，是不支持这种写法的。只能在网页上使用。
懂了，感谢~
