### ISSUE TITLE
预览没有以光标点的地方进行展示

### ISSUE THREAD

**Issue by dusbin** [Tencent/cherry-markdown#46]
预览没有以光标选中的地方进行展示，我的光标在编辑页面 返回Demo 这块时，预览并没有显示对应的光标处的预览， RTX robinddu

**Comment by dusbin** [comment]
<img width="1662" alt="图片" src="https://user-images.githubusercontent.com/7601584/145138189-a46db167-416e-4341-8a05-7d96e968bb52.png">

**Comment by sunsonliu** [comment]
收到，的确可以加个光标所在dom的高亮特效~

**Comment by sunsonliu** [comment]
hello, 这个issue非常有意思，请问是腾讯员工吗，如果是的话可以联系一下我：）
