### ISSUE TITLE
[Bug report] Draw.io 预览区点击图片不能重新打开编辑

### ISSUE THREAD

**Issue by jiakuan** [Tencent/cherry-markdown#460]
**Describe the bug**
Draw.io 预览区点击图片不能重新打开编辑

**To Reproduce**
1. Go to [[['...'](#)]()](https://tencent.github.io/cherry-markdown/examples/index.html)
2. 点击 draw.io 菜单创建一个drawio画图并点击确定插入Markdown编辑器
3. 在预览区点击刚插入的图片，没有反应

**Expected behavior**
预览区点击drawio图片，应该重新打开drawio编辑器

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version: Chrome Version 113.0.5672.126 (Official Build) (arm64)

**Additional context**
N/A

**Comment by sunsonliu** [comment]
奇怪。。并没有重现出来。。可以发下具体的md源码么
![20230530_111928-0-10](https://github.com/Tencent/cherry-markdown/assets/998441/38d8b021-533d-43ab-a144-5f462f20ba67)

**Comment by jiakuan** [comment]
我刚才刷新网页，再试一遍又可以了。
有可能网页打开放置很长时间以后，点击失效。
我再留意一下，看能不能想办法重现

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/issues/472
已修复并发布
