### ISSUE TITLE
全屏后编辑区和预览区中间的分隔条拖拽点错位

### ISSUE THREAD

**Issue by veitool** [Tencent/cherry-markdown#461]
当开启预览区时，中间的分隔条拖拽触发点正常。但是全屏后，中间的分隔条拖拽点会有错位（分隔条位置并不能拖拽）
版本：v0.8.20

**Comment by RSS1102** [comment]
https://tencent.github.io/cherry-markdown/examples/multiple.html
你指的是这条线吗？没有发现错位哎？
![image](https://github.com/Tencent/cherry-markdown/assets/81673017/bda859da-a8b3-4c93-b8a2-f32c48c30640)

**Comment by veitool** [comment]
> https://tencent.github.io/cherry-markdown/examples/multiple.html

刚测试了下你们官方演示，视乎全屏后，分割栏好像不能拖动改变区域大小

**Comment by RSS1102** [comment]
您看下这个呢？https://tencent.github.io/cherry-markdown/examples/index.html
好像也没有发现出问题？。。
![image](https://github.com/Tencent/cherry-markdown/assets/81673017/00c2f1d0-e374-4202-bb04-898057469273)

**Comment by veitool** [comment]
> 您看下这个呢？https://tencent.github.io/cherry-markdown/examples/index.html 好像也没有发现出问题？。。 ![image](https://user-images.githubusercontent.com/81673017/242804932-00c2f1d0-e374-4202-bb04-898057469273.png)

刚我发GIF图的时候，忘点击回复了，您看下我上面发的gif动画图应该就明白了。您刚发的这个演示是全屏和普通屏一样的尺寸，所以不会出现错位。

**Comment by RSS1102** [comment]
> > 您看下这个呢？https://tencent.github.io/cherry-markdown/examples/index.html 好像也没有发现出问题？。。 ![image](https://user-images.githubusercontent.com/81673017/242804932-00c2f1d0-e374-4202-bb04-898057469273.png)
> 
> 刚我发GIF图的时候，忘点击回复了，您看下我上面发的gif动画图应该就明白了。您刚发的这个演示是全屏和普通屏一样的尺寸，所以不会出现错位。

稍等 我改一下试试。

**Comment by RSS1102** [comment]
复现问题了：
当进行全屏之后，分割线被移动，但是选中点依然在之前的那个位置。会尽快修复一下的，谢谢。

**Comment by veitool** [comment]
> 复现问题了： 当进行全屏之后，分割线被移动，但是选中点依然在之前的那个位置。会尽快修复一下的，谢谢。

好的。

**Comment by Victor-kawai** [comment]
> 复现问题了： 当进行全屏之后，分割线被移动，但是选中点依然在之前的那个位置。会尽快修复一下的，谢谢。

请问分割线的移动是不是只被mouseup事件所触发？他这里面的调用逻辑可以向您询问一下吗？

**Comment by sunsonliu** [comment]
> 请问分割线的移动是不是只被mouseup事件所触发？他这里面的调用逻辑可以向您询问一下吗？

可以通过以下方式修改编辑区和预览区的宽度哈：`cherry.previewer.setRealLayout('60%', '40%')`

**Comment by ilxqx** [comment]
我也遇到同样的问题，我的问题是光标错位，中间分割线可拖拽的位置也错位。我已经排查出了原因，原因就是编辑器组件整体不支持resize事件的响应
举一个场景：
在Dialog框组件中使用编辑器，那么Dialog框在显示完成后，编辑器组件中的光标就错位了，这个Dialog展示的时候有Zoom动画，究其原因就是Zoom动画还没结束，编辑器可能已经渲染完毕了，在渲染的过程中肯定读取了相关Dom的尺寸属性，但是在动画过程中，Dom一直是从小到大一直变化的，也就是说编辑器渲染的过程中读取到了动画某个时间点Dom的尺寸信息，这个尺寸肯定是不对的（被缩小的），故在动画结束后也即Dialog框完全显示后编辑器光标错位，中间可拓展分割线的可拖拽点错位

解决办法，我觉得编辑器内部应该监听尺寸变化，从而重新获取相关Dom的尺寸进而重新渲染编辑器相关内容

<img width="875" alt="image" src="https://github.com/Tencent/cherry-markdown/assets/18739624/1766f954-f03a-4a09-893f-6d34f1edbc81">

**Comment by ilxqx** [comment]
切换全屏会出现这个错误，应该是编辑器内部的错误：
<img width="1918" alt="image" src="https://github.com/Tencent/cherry-markdown/assets/18739624/4eb5e468-a281-4341-8af5-3c18a09479b2">

**Comment by sunsonliu** [comment]
收到，我们定位下再增加下对resize事件的监听

**Comment by sunsonliu** [comment]
应该修复了，发布后可以再试试

**Comment by ccnnde** [comment]
@sunsonliu 你好，请问这个修复大概啥时候发布啊，我看最新的 0.8.38 版本没有包含这个

**Comment by sunsonliu** [comment]
> 修复全屏时编辑区和预览区中间分割线拖拽位置错位的问题

![image](https://github.com/Tencent/cherry-markdown/assets/998441/b6877d43-0983-41a5-9c9d-5b662c30a5e7)

哦哦，当时临近春节假期，为了避免发版后引发问题导致无人快速跟进，所以我们积攒了一批提交没有发布，我们争取明天发个版本哈

**Comment by ccnnde** [comment]
好的，谢谢 😄
