### ISSUE TITLE
是否可以支持，标签以新页面打开的方式的配置

### ISSUE THREAD

**Issue by Gestorz** [Tencent/cherry-markdown#462]

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/65cd5b9d-7a79-44e3-bcd5-501c35e2bb5c)
因为已经支持了这种语法格式`[text](url){target=_blank}`，所以并没有特别大的动力去改成配置的方式。。。

**Comment by huangjiale724** [comment]
大佬们，我这边有个问题，就是预览模式下点击超链接（或附件）没有跳转（或下载），需要自己右键在新标签页打开才能跳转，如何解决这个问题呢，想请问下是需要设置哪个配置项吗？

**Comment by RSS1102** [comment]
> 

可以看下：https://github.com/Tencent/cherry-markdown/issues/459
参考写法：https://github.com/Tencent/cherry-markdown/blob/main/examples/markdown/basic.md?plain=1#L1-L13
在这个预览下是可以的呢？https://tencent.github.io/cherry-markdown/examples/#%E4%BE%8B%E5%AD%90

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/5b1891e0-05bb-48ce-8f34-dfdf148593f1)

已提供配置新页面打开的能力，已提交到dev分支 https://github.com/Tencent/cherry-markdown/commit/be1800a64e9592f9f3b2c5c1ebd36b45ab471f14
