### ISSUE TITLE
建议toolbar菜单的文字和tooltip能够支持i18n国际化

### ISSUE THREAD

**Issue by AlucardShi** [Tencent/cherry-markdown#465]
建议能默认支持简繁英

如果不行的话，开放自定义文本的接口，或者开放i18n配置也可以

**Comment by jiakuan** [comment]
已经有locale的文件，只是代码里面很多地方写死了。我已经修改了一部分，还有一些。
欢迎提交PR

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/pull/463
