### ISSUE TITLE
mermaid画图组件，建议自动生成的序号可以由开关控制是否显示

### ISSUE THREAD

**Issue by penghyang** [Tencent/cherry-markdown#466]
mermaid.js已经支持由“autonumber”参数控制，建议跟进

**Comment by sunsonliu** [comment]
收到，其实一直都知道有`autonumber`这个参数，只是很多用户不知道这个参数然后我们恰巧又非常不想用户错过这么好的一个功能，所以我们做的时候给改成了强制开启。。。不过现在想想当时还是很弱智的，明明有其他的方案让用户知道这个功能，我们会在后续的版本里去掉“强制打开序号”的特性。
