### ISSUE TITLE
超链接、文件链接等单击不跳转（或不下载）

### ISSUE THREAD

**Issue by huangjiale724** [Tencent/cherry-markdown#474]
大佬，我把简易demo上传到git了，麻烦有空帮忙看看：https://github.com/huangjiale724/md-test.git

**Comment by RSS1102** [comment]
请关注这行代码：[ <div @click.prevent.stop>](https://github.com/huangjiale724/md-test/blob/d90947a5a4515aa41043949cbfbe939f86b85684/src/components/cherry-markdown/index.vue#L2C1-L2C1)
