### ISSUE TITLE
[Bug report]粘帖的代码排版错乱

### ISSUE THREAD

**Issue by wmui** [Tencent/cherry-markdown#476]
原本正常排版的代码，如图：
<img width="842" alt="image" src="https://github.com/Tencent/cherry-markdown/assets/24876474/61fa3320-4b26-4758-ad7e-887d460b7641">

粘帖到编辑器后自动排版了，换行也错乱了，如图：
<img width="1935" alt="image" src="https://github.com/Tencent/cherry-markdown/assets/24876474/dcc8faff-3698-44c1-b71f-a83730f3f669">

版本：0.8.20

**Comment by sunsonliu** [comment]
收到，应该是把html转成markdown的逻辑出现了问题，目前临时解决方案是在粘贴后选择“粘贴为纯文本”（如下图），我们也尽快解决这个bug
![image](https://github.com/Tencent/cherry-markdown/assets/998441/3fa91403-86b5-411f-bb22-df11765ec985)
