### ISSUE TITLE
[Bug report]Previewer.js:741的this.options.previewerCache.layout !== {}逻辑问题

### ISSUE THREAD

**Issue by Tim-1e** [Tencent/cherry-markdown#478]
![image](https://github.com/Tencent/cherry-markdown/assets/72056245/5f181ae2-acfa-4567-9f81-acac98c53f83)
而且逻辑上,初始化时this.options.previewerCache.layout==={}
根据下面描述修改逻辑如下
if (Object.keys(this.options.previewerCache.layout).length !== 0) {
则初始化化时不进此分支,导致previewer渲染失败

**Comment by sunsonliu** [comment]
收到，感谢反馈，也欢迎直接给我们提pr哈~
