### ISSUE TITLE
预览显示不全，编辑页面的信息在预览无法完整显示

### ISSUE THREAD

**Issue by dusbin** [Tencent/cherry-markdown#48]
RTX robinddu <img width="1662" alt="图片" src="https://user-images.githubusercontent.com/7601584/145137985-77d61384-3d26-4163-a932-c433acf2afa2.png">

**Comment by humyfred** [comment]
你好，这个没办法照顾到底部的预览，我们主要是对齐了顶部的内容，左右两边因为渲染不同而高度有所不同

**Comment by dusbin** [comment]
好的，理解了
