### ISSUE TITLE
[Feature request]是否考虑在工具栏增加查找字段及一键替换功能？

### ISSUE THREAD

**Issue by Victor-kawai** [Tencent/cherry-markdown#485]
想要定位某些语句的时候是否可以考虑在工具栏增加一个定位查找功能，同时也希望可以添加一键替换的功能，满足一些模板化的需求和功能的快速定位。

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/cec78c4a-506b-4aed-b263-745fb135d0bd)
已经支持了哈，可以在左侧编辑区按Ctrl+F快捷键唤起，不过也的确可以增加一个工具栏的配置，我们后续安排下~

**Comment by Victor-kawai** [comment]
> ![image](https://user-images.githubusercontent.com/998441/250702331-cec78c4a-506b-4aed-b263-745fb135d0bd.png) 已经支持了哈，可以在左侧编辑区按Ctrl+F快捷键唤起，不过也的确可以增加一个工具栏的配置，我们后续安排下~

好的谢谢
