### ISSUE TITLE
[Feature request] Mermaid Error Report

### ISSUE THREAD

**Issue by YunHsiao** [Tencent/cherry-markdown#488]
**Is your feature request related to a problem? Please describe.**
Mermaid grammar errors are not reported in any way right now, even in the DevTools, making writing diagrams directly in-place a painful experience. Currently when there are grammar errors the source mermaid code is shown instead of any error messages.

** What does the proposed API look like**
Show the relevant error message in preview when there is one.

**Comment by jiawei686** [comment]
We will look into it.
