### ISSUE TITLE
[Bug report]hooksConfig的含义错误

### ISSUE THREAD

**Issue by Tim-1e** [Tencent/cherry-markdown#489]
**查看其定义**
const hooksConfig = [
  // 段落级 Hook
  // 引擎会按当前排序顺序执行beforeMake、makeHtml方法
  // 引擎会按当前排序逆序执行afterMake方法
    // 行内Hook
  // 引擎会按当前顺序执行makeHtml方法
]
但是实际执行时,Transfer由于未更改HOOK_TYPE,现有的设置中实际表现为['sentence'']
附带现在的结构
const hooksConfig = [
  // 段落级 Hook
  // 引擎会按当前排序顺序执行beforeMake、makeHtml方法
  // 引擎会按当前排序逆序执行afterMake方法
  CodeBlock,
  InlineCode,
  MathBlock,
  InlineMath,
  HtmlBlock,
  Footnote,
  CommentReference,
  Transfer,
  Br,
  Table,
  Blockquote,
  Toc,
  Header, // 处理标题, 传入strict属性严格要求ATX风格标题#后带空格
  Hr,
  List,
  Detail,
  Panel,
  Paragraph, // 普通段落

  // 行内Hook
  // 引擎会按当前顺序执行makeHtml方法
  Emoji,
  Image,
  Link,
  AutoLink,
  Emphasis,
  BackgroundColor,
  Color,
  Size,
  Sub,
  Sup,
  Ruby,
  Strikethrough,
  Underline,
  HighLight,
  Suggester,
];

由于未知其实际设计思想,现在按照实际运行结果更改如下
const hooksConfig = [
  // 段落级 Hook
  // 引擎会按当前排序顺序执行beforeMake、makeHtml方法
  // 引擎会按当前排序逆序执行afterMake方法
  CodeBlock,
  InlineCode,
  MathBlock,
  InlineMath,
  HtmlBlock,
  Footnote,
  CommentReference,
  Br,
  Table,
  Blockquote,
  Toc,
  Header, // 处理标题, 传入strict属性严格要求ATX风格标题#后带空格
  Hr,
  List,
  Detail,
  Panel,
  Paragraph, // 普通段落

  // 行内Hook
  // 引擎会按当前顺序执行makeHtml方法
  Transfer,
  Emoji,
  Image,
  Link,
  AutoLink,
  Emphasis,
  BackgroundColor,
  Color,
  Size,
  Sub,
  Sup,
  Ruby,
  Strikethrough,
  Underline,
  HighLight,
  Suggester,
];
稍后提交pr

**Comment by Tim-1e** [comment]
另加询问:
我在原本dev分支基础上实现了一个preview的所见即所得的初步版本,由于开放了preview的可编辑性,可能不太稳定,对于pr我应该如何提交?

**Comment by sunsonliu** [comment]
刚从dev拉了个分支，可以提交到这个新分支上哈：https://github.com/Tencent/cherry-markdown/tree/feat/wysiwyg
Transfer的问题我不太清楚，已经拜托另外一个同学在看了哈~~感谢贡献~~
