### ISSUE TITLE
[Bug report]单栏编辑模式下导出工具失效

### ISSUE THREAD

**Issue by Victor-kawai** [Tencent/cherry-markdown#491]
在单栏编辑模式下的导出的文件失效。

https://github.com/Tencent/cherry-markdown/assets/113369555/3beddbe0-c32c-4d2b-bd8c-dd43bd163032

**Comment by Victor-kawai** [comment]
https://github.com/Tencent/cherry-markdown/assets/113369555/48005ef5-554c-4608-8776-fc9b62280192

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/commit/8fdaf6aa00db6be36a3bb97d1e27d15cefeed172
感谢反馈，已修复并提交到dev分支~

**Comment by sunsonliu** [comment]
已发版
