### ISSUE TITLE
[Bug report] 预览按钮逻辑混乱

### ISSUE THREAD

**Issue by LeehWinCing** [Tencent/cherry-markdown#495]
顶部导航栏 **关闭预览** 按钮和 **预览/返回编辑** 按钮存在逻辑冲突。

两个按钮仅控制三种页面状态，控制逻辑非常混乱。

如下图，从 **图 1** 到 **图 2** 按下了两次 **预览/返回编辑**，**图 2** 到 **图 3** 按下了两次 **关闭预览**，这导致 **图 1** 和 **图 3** 虽然在同一页面却有不同的导航栏显示，令人迷惑。

修改建议：将两个按钮合并为同一个，同时调整 **设置** 下的 **关闭预览** 按钮的行为。

<img width="1231" alt="屏幕截图 2023-07-07 004240" src="https://github.com/Tencent/cherry-markdown/assets/106899655/bd42fa53-0a30-46f2-9bd8-897a3b1a5d48">
<img width="1238" alt="屏幕截图 2023-07-07 004436" src="https://github.com/Tencent/cherry-markdown/assets/106899655/76350200-60dd-4d60-833b-6be062619c76">
<img width="1237" alt="屏幕截图 2023-07-07 004544" src="https://github.com/Tencent/cherry-markdown/assets/106899655/ae73c0cb-6296-46e5-946f-fa2c1f7d34b5">

**Comment by sunsonliu** [comment]
其实是demo里列出了大部分的按钮，其中“关闭预览”就是字面意思，“预览/返回编辑 ”其实是切换模式，是给移动端、类github这类场景设计的。已经在demo里去掉了“预览/返回编辑 ”这个按钮
