### ISSUE TITLE
Basic demo weird scroll behaviour after phone mode

### ISSUE THREAD

**Issue by cvertee** [Tencent/cherry-markdown#5]
After disabling phone mode left edit side becomes unscrollable.
1. Turn on phone mode
2. Turn off phone mode
3. Scroll left side
4. ???

Browser: Edge Version 95.0.1020.30 (Official build) (64-bit)

https://user-images.githubusercontent.com/79146373/139574180-d1efbf60-0462-4bc8-84eb-bae39f4bdf24.mp4

**Comment by jiawei686** [comment]
Thanks for your reporting! We found a mistake in Previewer remove event method. It can cause this bug while toggling phone mode. And it's fixed in #7
