### ISSUE TITLE
[Bug report]代码块粘贴似乎有问题

### ISSUE THREAD

**Issue by Victor-kawai** [Tencent/cherry-markdown#501]
从vscode的markdown文件中复制过来的代码会出现异常换行的情况。如下

https://github.com/Tencent/cherry-markdown/assets/113369555/427c2f92-8532-4cdd-a263-8515c2b19657

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/issues/476

感谢反馈，是已知问题，下次发版后会修复~

**Comment by sunsonliu** [comment]
已发布
