### ISSUE TITLE
[Bug report] 拼音 不支持多音字

### ISSUE THREAD

**Issue by hengrong1** [Tencent/cherry-markdown#505]
![image](https://github.com/Tencent/cherry-markdown/assets/26431796/e95f6ac1-5e18-43e0-a9aa-349b71ac3ec1)
{ 重启 | zhòng qǐ } 
  { 藤蔓 | téng màn }

**Comment by sunsonliu** [comment]
收到，这里用的汉子转拼音的能力是由第三方组件提供的（https://github.com/liu11hao11/pinyin_js），这边就不提供“售后服务”了哈
