### ISSUE TITLE
[Feature request] 希望导出文件时，可以动态设置导出的文件名

### ISSUE THREAD

**Issue by zhaoxianfang** [Tencent/cherry-markdown#506]
希望导出文件时，可以动态设置导出的文件名

**Comment by sunsonliu** [comment]
可以详细描述下诉求不，是希望cherry在导出文件时提供一个回调配置，由业务侧给出文件名；还是希望cherry 在导出文件时，自动取第一个标题为文件名？

**Comment by zhaoxianfang** [comment]
回答：希望使用者可以自定义为导出文件命名

下面是可能有用的使用场景，仅做参考
使用场景：
方式一、可以在初始化富文本时 通过回调函数返回值 为导出文件命名
方式二、可以调用富文本内置API 为导出文件命名
