### ISSUE TITLE
如何取消自动聚焦？

### ISSUE THREAD

**Issue by Nice-PLQ** [Tencent/cherry-markdown#516]
初始化之后会自动聚焦，如果这个编辑器在页面下面，会导致页面的跳动

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/blob/main/src/Cherry.config.js#L212
参考这里哈

**Comment by Nice-PLQ** [comment]
> https://github.com/Tencent/cherry-markdown/blob/main/src/Cherry.config.js#L212 参考这里哈

有效

**Comment by fyac** [comment]
已经把autofocus设置成false了还是会自动滚动页面下面怎么弄
codemirror: {
          autofocus: false,
 },
