### ISSUE TITLE
[Feature request]期待客户端功能

### ISSUE THREAD

**Issue by wade-Chan** [Tencent/cherry-markdown#519]
1. 在一些代码主题中，语言的选择框会挡住文字，建议往上或放在右下角
![image](https://github.com/Tencent/cherry-markdown/assets/48142369/f17ae3b9-2a3d-4256-ae17-d70354fe6c82)

2. 期待cherry客户端的尽快出现，并希望可以支持gitee,github,coding等git仓库的上传，最好是自带git的，而不需另外下载git，这个可以看一下nodegit库

**Comment by RSS1102** [comment]
1. code theme 已放在左上角.
2. 客户端的话，已经在开发了，之前使用electron开发的打包后优化体验比较差，目前已迁移到tauri实现，目前主要精力也放在客户端实现上了，预计不久应该能产出新的第一版。
