### ISSUE TITLE
[Feature request] 希望在编辑器中支持VIM编辑模式

### ISSUE THREAD

**Issue by V-know** [Tencent/cherry-markdown#522]
通过VIM在文本框进行Markdown编辑，效率会更高

**Comment by sunsonliu** [comment]
目前用的是类sublime的编辑方式，如果希望改成vim的编辑方式，可以自行修改下哈，需要修改 `/src/Editor.js`
首先引入codemirror的vim扩展`import 'codemirror/keymap/vim';`
然后在这个位置改成`vim`
![image](https://github.com/Tencent/cherry-markdown/assets/998441/f3074bb4-6651-41e7-b179-d05cc43be906)

这样编辑器的体验就变成了vim的编辑体验了哈

**Comment by sunsonliu** [comment]
可以先按上述方案自行实现哈，后面我们也考虑下要不要提供配置能力

**Comment by sunsonliu** [comment]
已增加vim快捷键的配置，可以在[这里](https://tencent.github.io/cherry-markdown/examples/vim.html)体验
配置方式如下：
```
new Cherry({
  editor: {
    keyMap: 'vim',
  },
});
```
