### ISSUE TITLE
如何新增对编程语言解析的支持

### ISSUE THREAD

**Issue by alexwenbj** [Tencent/cherry-markdown#529]
我们现在可以在markdown中使用```python这样的方式来生成一个代码块，如果我想加一门语言，并且用自己的解析方法去解析（比如按一定的规则解析成图片或其他形态，不一定是文字），该如何定义？谢谢！

**Comment by lyngai** [comment]
可以参考 mermaid plugin 的实现。

https://github.com/Tencent/cherry-markdown/blob/main/src/addons/cherry-code-block-mermaid-plugin.js

**Comment by alexwenbj** [comment]
谢谢！
