### ISSUE TITLE
列表支持tab快速修改层级

### ISSUE THREAD

**Issue by sunsonliu** [Tencent/cherry-markdown#540]
- 通过“-”进行无序列表的输入
- 换行后，第二行会自动补全“-”，此时光标在-后面
- 此时点击tab，无法将当前行切换为子集（除非先把光标移动到“-”之前）

希望当光标处于以下位置时支持tab快捷键：
1. 光标在行首（已支持 ）
2. 光标在-前面（已支持）
3. 光标在-后面（未支持）需提供配置开关，打开后支持，默认打开
4. 光标在行尾（未支持）需提供配置开关，打开后支持，默认关闭

在以下位置**不需要**支持快捷键：
1. 光标在-后面的文字中

以上是**无序列表**的场景，在**有序列表**场景有同样的诉求

**Comment by ufec** [comment]
Merged #553
