### ISSUE TITLE
[Bug report]更新最新版本(0.8.23)后，使用CherryEngine解析md失败

### ISSUE THREAD

**Issue by Joy-Wang** [Tencent/cherry-markdown#546]
如图：
<img width="690" alt="image" src="https://github.com/Tencent/cherry-markdown/assets/16829479/f89c94f2-b0e3-491a-a1d9-9431d372996d">

**Comment by sunsonliu** [comment]
收到，我们抓紧定位下~

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/releases/tag/v0.8.23-1.0
