### ISSUE TITLE
[Bug report]代码块的复制功能与预期不符

### ISSUE THREAD

**Issue by 3liana** [Tencent/cherry-markdown#552]
**Describe the bug**
点击代码块的复制按钮时，除了代码块的内容之外，还会复制代码块语言选择框的所有内容

**To Reproduce**
1.新建代码块
2. Click on 'copy'
3. See error

期望得到：
复制代码块中的代码内容
实际所复制的内容：
Choose here javascript typescript html css shell python golang java c c++ c# php ruby swift kotlin scala rust dart elixir haskell lua perl r sql hello

**Screenshots**
![343d50430cfd844c5b9d97c118166d6](https://github.com/Tencent/cherry-markdown/assets/115217369/48e3800a-48e8-4c0b-97fa-bcf050862197)

**Comment by sunsonliu** [comment]
感谢反馈和PR，已合入dev分支，后续将随版本发布合入main
