### ISSUE TITLE
标签元素渲染不出来

### ISSUE THREAD

**Issue by hualyz** [Tencent/cherry-markdown#56]
# 在表格或者链接描述中，填写的标签元素渲染不出来。

## 举例1：
![image](https://user-images.githubusercontent.com/93361843/145374581-f85fcc0c-0975-4085-96cf-7992bb6916ed.png)

**cherry效果**
![image](https://user-images.githubusercontent.com/93361843/145374489-ca1109e1-027f-4389-8241-9d2e9053871f.png)

**typora效果**
![image](https://user-images.githubusercontent.com/93361843/145374618-bd82a3fb-73de-4647-9eed-5e4b51b34d45.png)

## 举例2：
![企业微信截图_16390430162413](https://user-images.githubusercontent.com/93361843/145374862-e73a5a15-ab0e-47ce-a908-881b0b6487dd.png)

**cherry效果**
![企业微信截图_16390430227462](https://user-images.githubusercontent.com/93361843/145374896-8db04352-7e91-4702-83d3-4f320ae2fd7a.png)

**typora效果**
![企业微信截图_16390430347875](https://user-images.githubusercontent.com/93361843/145374922-ad5fafd4-22f2-4684-adb1-6d4b8f829262.png)

**Comment by lyngai** [comment]
我们与typora的实现逻辑不同，可以看到给出的截图对应尖括号包裹的内容是被置灰的，说明也是被typora识别成了html标签，但还未闭合。

cherry针对这类未闭合的标签采取了清洗的策略。

---

正确的做法是在左尖括号处加上转义符号，使之作为文本进行展示。例：`\<map>`
