### ISSUE TITLE
[Bug report]`toolbars`,Some of its functional panels did not expand as expected.

### ISSUE THREAD

**Issue by RSS1102** [Tencent/cherry-markdown#560]
![image](https://github.com/Tencent/cherry-markdown/assets/81673017/69380c52-459e-40d6-a266-cefb01fb2cca)

**删除线(strikethrough)**，**大小(size)**。
These display positions are incorrect。

**Comment by CainXCain** [comment]
测了下这个问题，原因是toolbar和bubble有相同的项，先加载toolbar后加载bubble，在toolbar.collectMenuInfo时后者覆盖了前者

因此在执行getMenuPosition时得到的positionModel是fixed而不是（实际应该是的）absolute，导致位置错误

同时出现在toolbar与bubble、floatmenu、sidebar三者之一，且有二级菜单的项都能触发这个bug

由于toolbar项在配置及代码中的名称与显示文字图像直接关联，不太容易通过改名的方式避免覆盖，在考虑怎么无副作用地解决掉这个问题
