### ISSUE TITLE
加载动画替换的问题

### ISSUE THREAD

**Issue by losingle** [Tencent/cherry-markdown#576]
```javascript
var customMenuA = Cherry.createMenuHook('Remote ',  {
  iconName: 'remote',
  onClick: function(selection) {
    // 加载动画
      const { begin, end } = this.$getSelectionRange();
      const loaderElement = document.createElement("span");
      loaderElement.className = "spinner-border spinner-border-sm";
      const marker = this.editor.$cherry.getCodeMirror().markText(begin, end, {
          replacedWith: loaderElement.cloneNode(true),
      });
    return '';
  }
});
```
这个span顺利加进去了, 在codemirror中显示也没问题
但是在cherry中,只要执行完毕,动画就消失了,marker还存在

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/68cbb46f-3ba1-4847-9d51-05b8af8847e2)
可以通过增加这行代码让cherry跳过点击按钮后的后续操作，欢迎尝试~

**Comment by losingle** [comment]
谢谢，但是没有达到效果
Codemirror的其他操作没发现问题，
但是mark没有生效

**Comment by sunsonliu** [comment]
![动画3](https://github.com/Tencent/cherry-markdown/assets/998441/a7616454-a26c-4e06-8797-cb78edc14aa7)

刚试了下是没问题的（见上面动图，图片比较大，可能要稍微多等一会），我在`/examples/scripts/index-demo.js`里加入了下面的代码：
```
var customMenuA = Cherry.createMenuHook('Remote ',  {
  iconName: 'remote',
  onClick: function(selection) {
    // 加载动画
      const { begin, end } = this.$getSelectionRange();
      const loaderElement = document.createElement("span");
      loaderElement.className = "spinner-border spinner-border-sm";
      loaderElement.textContent = selection;
      const marker = this.editor.$cherry.getCodeMirror().markText(begin, end, {
          replacedWith: loaderElement.cloneNode(true),
      });
      this.updateMarkdown = false;
    return '';
  }
});
```

**Comment by losingle** [comment]
> ![动画3](https://user-images.githubusercontent.com/998441/266644530-a7616454-a26c-4e06-8797-cb78edc14aa7.gif) [ ![动画3](https://user-images.githubusercontent.com/998441/266644530-a7616454-a26c-4e06-8797-cb78edc14aa7.gif) ](https://user-images.githubusercontent.com/998441/266644530-a7616454-a26c-4e06-8797-cb78edc14aa7.gif) [ ](https://user-images.githubusercontent.com/998441/266644530-a7616454-a26c-4e06-8797-cb78edc14aa7.gif)
> 
> 刚试了下是没问题的（见上面动图，图片比较大，可能要稍微多等一会），我在`/examples/scripts/index-demo.js`里加入了下面的代码：
> 
> ```
> var customMenuA = Cherry.createMenuHook('Remote ',  {
>   iconName: 'remote',
>   onClick: function(selection) {
>     // 加载动画
>       const { begin, end } = this.$getSelectionRange();
>       const loaderElement = document.createElement("span");
>       loaderElement.className = "spinner-border spinner-border-sm";
>       loaderElement.textContent = selection;
>       const marker = this.editor.$cherry.getCodeMirror().markText(begin, end, {
>           replacedWith: loaderElement.cloneNode(true),
>       });
>       this.updateMarkdown = false;
>     return '';
>   }
> });
> ```

可以得到预期效果,谢谢

**Comment by losingle** [comment]
@sunsonliu 可以考虑把 suggester-panel 用codemirror的widget来装载
这样不用折腾层级关系, 在定高的环境下,suggester-panel的用户体验就很差啦
<img width="304" alt="Screenshot 2023-09-10 at 06 44 15" src="https://github.com/Tencent/cherry-markdown/assets/540630/707cd442-778b-4d90-bcce-f5c739e8f5bc">

**Comment by sunsonliu** [comment]
> @sunsonliu 可以考虑把 suggester-panel 用codemirror的widget来装载 这样不用折腾层级关系, 在定高的环境下,suggester-panel的用户体验就很差啦 <img alt="Screenshot 2023-09-10 at 06 44 15" width="304" src="https://user-images.githubusercontent.com/540630/266805059-707cd442-778b-4d90-bcce-f5c739e8f5bc.png">

收到，之前没有了解过codemirror的widget，我们研究下，如果你有兴趣也欢迎给我们提pr哈~

**Comment by losingle** [comment]
@sunsonliu 有没有快捷安全的方式增加分屏,
看了previewer的代码,还挺复杂,
我的场景是, 把TOC新开一个分屏来显示,再做一些扩展

**Comment by sunsonliu** [comment]
是要做侧边栏目录展示吧，这个建议利用`cherry.getToc()`获取目录信息，然后在cherry外部自定义一个侧滑目录出来

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/be3d263d-1325-4874-8dfd-6f72b6eb30db)
已实现右侧悬浮目录，可在https://tencent.github.io/cherry-markdown/examples/index.html 这里体验哈
