### ISSUE TITLE
[Bug report] List 预览编辑会导致格式失效

### ISSUE THREAD

**Issue by losingle** [Tencent/cherry-markdown#579]
### Describe the bug

直观感受是去掉了markdown格式前面应该存在的空格

https://github.com/Tencent/cherry-markdown/assets/540630/177ee329-1549-4782-8a65-8723a5ea445a

### System Info

```Shell
System:
    OS: macOS 13.5.1
    CPU: (8) arm64 Apple M2
    Memory: 955.61 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.7.1 - ~/.nvm/versions/node/v18.16.0/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.179
    Edge: 114.0.1823.67
    Safari: 16.6
```

### Validations

- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Help us

None

**Comment by sunsonliu** [comment]
感谢反馈，的确是有些问题，我们定位修复下哈
