### ISSUE TITLE
[Feature report]可以在工具栏中新增一个自定义icon图标的方法吗

### ISSUE THREAD

**Issue by moxiaoli0813** [Tencent/cherry-markdown#589]
### Clear and concise description of the problem

我希望可以在这个自定义菜单工具中新增一个方法，可以使用svg，链接，或者资源路径的方式添加图标，我本身只是个后端开发，在研究文档和源码的过程中没找到对应的方法
这是我原本外置的保存按钮
![image](https://github.com/Tencent/cherry-markdown/assets/103327450/377de23a-a73c-488b-878a-d2e5f2a60483)
![image](https://github.com/Tencent/cherry-markdown/assets/103327450/7325afa8-b3b3-4fda-adea-b1e04e9dca20)
这里是我自定义的菜单按钮
![image](https://github.com/Tencent/cherry-markdown/assets/103327450/825f8100-e689-41b1-ba28-a3c537476579)

### Validations

- [ ] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Help us

None

**Comment by sunsonliu** [comment]
感谢反馈，目前还不支持配置 svg形式的按钮图标哈，每个自定义按钮都可以定义iconName，iconName会体现在按钮的class里（见下图），如果着急使用，可以用css的方式来设置图标样式哈
![image](https://github.com/Tencent/cherry-markdown/assets/998441/cad9659e-5c04-4b5c-9d66-ae4f53b699fc)

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/ceed6d85-52d1-4217-bdbd-4cd607746195)

这么引入：`<i class="ch-icon ch-icon-justify"></i>`
