### ISSUE TITLE
[Bug report] 预览区和编辑区交替滚动时，编辑区无法滚动

### ISSUE THREAD

**Issue by lllllllqw** [Tencent/cherry-markdown#59]
**Describe the bug**
预览区和编辑区交替滚动时，编辑区无法滚动，无限回弹

**To Reproduce**
1. 进入 demo 页 https://tencent.github.io/cherry-markdown/examples/index.html
2. 滚动右侧预览区
3. 惯性滚动持续时，滚动左侧编辑区
4. 编辑区一直被弹回固定位置

**Expected behavior**
编辑区能正常滚动

**Screenshots**
![iShot2021-12-09 21 04 23](https://user-images.githubusercontent.com/20896515/145402483-7ad8a640-3fed-4cfc-ab8f-413dc5c0bb73.gif)

**Environment (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]
 - Version [0.5.14]

**Comment by lyngai** [comment]
已知的滚动过程中的缓动动画逻辑导致的问题，临时解决方案是等待被动的滚动动画停止后，再去操作对应的区域。

**Comment by sunsonliu** [comment]
已经提交到dev分支了
