### ISSUE TITLE
[Bug report] 预览模式再次点击图片出现蒙层

### ISSUE THREAD

**Issue by Keeyuu** [Tencent/cherry-markdown#594]
### Describe the bug

预览模式点击图片后关闭,再次点击图片会在图片上出现一层灰色的蒙层,
再次点击后蒙层才会消失,
看html 是有几个一样的元素,手动删除后面重复的元素 蒙层会消失
![图片](https://img1.imgtp.com/2023/09/15/xw31zElt.png)
第一次点开的时候只有一个元素,猜测是不是这个重复的原因
![第一次点开](https://img1.imgtp.com/2023/09/15/a7a0v0nP.png)

### Validations

- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Help us

None

**Comment by sunsonliu** [comment]
收到，这里主要是因为引入了一个“点击图片查看原图”的组件导致的bug。具体的背景可以看这个issue：https://github.com/Tencent/cherry-markdown/issues/199 。由于团队认为绝大多数业务会自行实现点击查看原图的功能，所以该问题已经没有排期优化，目前来看短期内应该也没资源解决，如果keeyuu有兴趣的话，也欢迎给我们提pr哈

**Comment by Keeyuu** [comment]
> 收到，这里主要是因为引入了一个“点击图片查看原图”的组件导致的bug。具体的背景可以看这个issue：#199 。由于团队认为绝大多数业务会自行实现点击查看原图的功能，所以该问题一直没有排期优化，目前来看短期内应该也没资源解决，如果keeyuu有兴趣的话，也欢迎给我们提pr哈

![0617BE8E](https://github.com/Tencent/cherry-markdown/assets/38851875/0eabf63f-64c1-48af-8f54-8b98687f5cc3)
