### ISSUE TITLE
编辑区和效果展示区并非完全对齐

### ISSUE THREAD

**Issue by EMILY-ZHOU814** [Tencent/cherry-markdown#60]
编辑区通常都比效果展示区篇幅短，导致在编辑区编辑时若要同步查看展示效果，有时候滚动操作并非能在水平对齐点查看到匹配的结果，通常展示区要更往下滚动多点，这样体验不是很好，所以cherry markdown能否支持编辑区对应的展示效果区始终与编辑区光标在同一水平线上

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/145518181-5654877b-6117-4910-bc12-0eb83f065fdc.png)
Cherry已经实现了**同步滚动**哈，这里的`水平线`是不好定义的，由于编辑区域和预览区域的高度的确不相同，所以我们无法做到任何一个水平线上的内容都是对齐的，目前Cherry选择`顶部水平线对齐`这个方案哈，在滚动时Cherry可以保证顶部区域的内容是一致的。

关于光标所在位置的对齐方案，在issue #46 里已经有了讨论，我们后续会实现在预览区域高亮&滚动对齐编辑区域光标所在位置的功能哈。
