### ISSUE TITLE
Suggester Dom 

### ISSUE THREAD

**Issue by losingle** [Tencent/cherry-markdown#601]
https://github.com/Tencent/cherry-markdown/blob/b64aeb82f2f6b171546ebcddad03938aef91faca/src/core/hooks/Suggester.js#L427

```
document.body.appendChild(this.createDom(SuggesterPanel.panelWrap));
```
这样直接append到body会导致Suggester的层级不对
比如将编辑器渲染到一个z-index更高的dom上,会导致Suggester被遮挡
应该不额外设置z-index, 像bubbleDom一样来处理

**Comment by sunsonliu** [comment]
已修改哈，suggesterDom会放在cherryDom里面
