### ISSUE TITLE
[docs]您好，这个cherry-markdown\docs下的配置文档很久没更新了

### ISSUE THREAD

**Issue by moxiaoli0813** [Tencent/cherry-markdown#610]
### issue type

Feature

### Clear and concise description of the problem or idea.

最近在给比如工具栏和自定义工具，修改页面主题的时候发现这个doc文档有些甚至都已经失效了或者实现过了，但是文档里面都还标注着线
![image](https://github.com/Tencent/cherry-markdown/assets/103327450/0ebc59e8-4615-4937-b521-89c73978371e)

### Validations

- [ ] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Help us

None

**Comment by RSS1102** [comment]
好的，谢谢提醒，最近的话，会系统性的再梳理一下文档。

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/wiki/%E8%B0%83%E6%95%B4%E5%B7%A5%E5%85%B7%E6%A0%8F
新的文档可以看这篇wiki，自定义工具栏、自定义语法、自定义主题都可以在wiki右侧里找到相关文档哈：
![image](https://github.com/Tencent/cherry-markdown/assets/998441/620872d1-f52e-4a41-9cd4-2a8eb9a76023)


对于API，建议在 [这里](https://tencent.github.io/cherry-markdown/examples/api.html) 进行查看哈
