### ISSUE TITLE
[Bug report] 在预览模式下多次点击有序/无序列表会导致内容被修改

### ISSUE THREAD

**Issue by vCloudSail** [Tencent/cherry-markdown#613]
### Describe the bug

![BUG11](https://github.com/Tencent/cherry-markdown/assets/45616923/a48419c6-ad8c-4a67-b991-117f56819aed)

### Reproduction

https://tencent.github.io/cherry-markdown/examples/index.html

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 7.14 GB / 31.77 GB
  Binaries:
    Node: 16.19.1 - D:\Software\Environment\nodejs\node.EXE
    Yarn: 1.22.19 - E:\AppData\npm\node_modules\yarn.CMD
    npm: 6.14.18 - D:\Software\Environment\nodejs\npm.CMD
    pnpm: 7.29.1 - E:\AppData\npm\node_modules\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (117.0.2045.36)
    Internet Explorer: 11.0.22621.1
```

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Help us

None

**Comment by RSS1102** [comment]
这个问题在dev分支下已经修复了。

**Comment by RSS1102** [comment]
@CainXCain

**Comment by CainXCain** [comment]
> 这个问题在dev分支下已经修复了。

还测到两个相关问题dev分支也没修掉，我另开一个issue详细描述吧
