### ISSUE TITLE
[Others]工具栏

### ISSUE THREAD

**Issue by q2316367743** [Tencent/cherry-markdown#619]
我看API中，有显示工具栏的方法：`cherry.toolbar.showToolbar()`，但是并未发现与之对应的隐藏工具栏的方法

我现在的需求是：在双栏编辑时，显示工具栏，预览时关闭工具栏，编辑与预览我会在其他地方控制

**Comment by RSS1102** [comment]
试试`cherry.toolbar.previewOnly()`符合您的预期嘛？

**Comment by q2316367743** [comment]
> 试试`cherry.toolbar.previewOnly()`符合您的预期嘛？

这个方法调用后，上面会有一个空白的任务栏，特别丑

**Comment by RSS1102** [comment]
> > 试试`cherry.toolbar.previewOnly()`符合您的预期嘛？
> 
> 这个方法调用后，上面会有一个空白的任务栏，特别丑

这个问题 稍后看下。

**Comment by RSS1102** [comment]
> > > 试试`cherry.toolbar.previewOnly()`符合您的预期嘛？
> > 
> > 
> > 这个方法调用后，上面会有一个空白的任务栏，特别丑
> 
> 这个问题 稍后看下，抱歉。

**Comment by ufec** [comment]
call `cherry.toolbar.menus.hooks.settings.toggleToolbar()`

**Comment by q2316367743** [comment]
那如何判断工具栏是否隐藏呢？

**Comment by ufec** [comment]
> cherry.toolbar.menus.hooks.settings.toggleToolbar()

check `cherry.status.toolbar === 'show'`

**Comment by q2316367743** [comment]
> > cherry.toolbar.menus.hooks.settings.toggleToolbar()
> 
> check `cherry.status.toolbar === 'show'`

感谢，我去试试

**Comment by q2316367743** [comment]
确实有效，十分感谢
