### ISSUE TITLE
[docs]自定义语法

### ISSUE THREAD

**Issue by q2316367743** [Tencent/cherry-markdown#620]
### issue type

Feature

### Clear and concise description of the problem or idea.

目前wiki的拓展配置中的自定义语法，并没有提供一个可用的示例，也没有完整的说明。

并且`HOOK_NAME`并没有说明都有哪些

### Validations

- [ ] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Help us

None

**Comment by RSS1102** [comment]
抱歉这方面了解了，后续会在docs下有一个完整的实例展示。
目前的话你可以查看：https://tencent.github.io/cherry-markdown/examples/api.html 体验。

**Comment by q2316367743** [comment]
多问一下，我看编辑器的目录定位是hash，如果使用vue项目，hash定位会影响vue路由，这个可以配置解决吗

**Comment by q2316367743** [comment]
还有配置中的回调函数`beforeImageMounted`是怎么用的，markdown中有些图片的链接需要异步处理一下，这个接口可以解决吗？

**Comment by sunsonliu** [comment]
> 多问一下，我看编辑器的目录定位是hash，如果使用vue项目，hash定位会影响vue路由，这个可以配置解决吗

这个目前没有机制来解决，可以通过监听toc目录的点击事件，阻止默认的事件来避免hash被污染哈

**Comment by sunsonliu** [comment]
> 还有配置中的回调函数`beforeImageMounted`是怎么用的，markdown中有些图片的链接需要异步处理一下，这个接口可以解决吗？

目前还不支持异步回调哈。。如果一定要异步，则需要在异步的回调里自行判断预览区域的图片元素并进行替换操作

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E6%B3%95
自定义语法的文档已更新到wiki，欢迎查阅指正~

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/b13bd5d5-cf39-45f8-a100-3ff4a866b04d)

https://github.com/Tencent/cherry-markdown/blob/main/src/Cherry.config.js#L297
实现了一个悬浮目录功能，可以考虑去掉[toc]语法，起用悬浮目录功能，并打开悬浮目录的`updateLocationHash: false`配置，让点击悬浮目录跳转不修改hash。

关闭[toc]语法的配置如下：
![image](https://github.com/Tencent/cherry-markdown/assets/998441/47620195-ec31-4eb4-abda-cdccc3798f04)
