### ISSUE TITLE
[Bug report]工具栏设置丢失

### ISSUE THREAD

**Issue by q2316367743** [Tencent/cherry-markdown#621]
### Describe the bug

如果我在cherry初始化之后就设置模式为预览模式，那么我在切换回编辑模式时，我的工具栏设置会丢失；
但是如果我初始化之后是编辑模式，那么我切换为预览模式，再切换回来，工具栏还是我设置的样子

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 6800H with Radeon Graphics
    Memory: 1.12 GB / 15.19 GB
  Binaries:
    Node: 16.15.1
    Yarn: 1.22.19
    npm: 8.11.0
    pnpm: 8.6.6
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.60)
    Internet Explorer: 11.0.22621.1
```

### Validations

- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Help us

None

**Comment by sunsonliu** [comment]
的确，当配置了`isPreviewOnly: true,`时，cherry就不再渲染工具栏了，这块我们优化下

**Comment by jackrebel** [comment]
> 的确，当配置了`isPreviewOnly: true,`时，cherry就不再渲染工具栏了，这块我们优化下

啥时候优化完呀？ 这个功能很重要， 有时候需要只读。

**Comment by sunsonliu** [comment]
> > 的确，当配置了`isPreviewOnly: true,`时，cherry就不再渲染工具栏了，这块我们优化下
> 
> 啥时候优化完呀？ 这个功能很重要， 有时候需要只读。

抱歉，最近正陆陆续续的修复 https://github.com/Tencent/cherry-markdown/issues/623 这个问题（想彻底解决，所以改动比较大），希望今天能弄完然后看这个问题哈，也希望今天能解决这个问题~

**Comment by sunsonliu** [comment]
已修复并提交到dev分支，欢迎体验哈
