### ISSUE TITLE
使用文档

### ISSUE THREAD

**Issue by yangzhenyu322** [Tencent/cherry-markdown#622]
使用文档可以详细一下吗，比如关于文件上传的upload配置，一旦我自定义了upload回调函数，它只能触发该回调函数，而没有在markdown上显示我插入的图片，感觉是少了一部分配置，希望能提供此类自定义回调函数的使用demo

**Comment by sunsonliu** [comment]
感谢反馈，我们更新下文档，如果着急使用，可以先参考 https://github.com/Tencent/cherry-markdown/blob/main/src/Cherry.config.js#L26 这里哈

**Comment by yangzhenyu322** [comment]
非常感谢，这对我很有帮助^_^

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/wiki/%E4%B8%8A%E6%89%8B%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C#%E9%85%8D%E7%BD%AE%E5%9B%BE%E7%89%87%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%8E%A5%E5%8F%A3
upload的配置文档更新到这里了哈，欢迎查看和反馈~

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/wiki/%E9%85%8D%E7%BD%AE%E5%9B%BE%E7%89%87&%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%8E%A5%E5%8F%A3

最新文档已更新到wiki，请查阅指正~
