### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by Gestorz** [Tencent/cherry-markdown#623]
### Describe the bug

enablePreviewerBubble 设置为 false 时
- 预览模式下的代码块会有编辑、复制按钮。
- makeHtml 读取到的代码块，会有下拉选择、编辑、复制按钮。

### Validations

- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Help us

None

**Comment by sunsonliu** [comment]
已经提交到了dev分支，新的逻辑下makeHtml不会再输出下拉、编辑等无用的元素了。
同时在配置里增加了“是否支持预览区切换语言”的配置，见下图
![image](https://github.com/Tencent/cherry-markdown/assets/998441/b958411d-1eb3-4b13-b242-06adda0f90e0)
