### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by kylincodelab** [Tencent/cherry-markdown#625]
### Describe the bug

cherry-markdown.js?v=20231016115446:42076 
        
        
       GET https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js net::ERR_CONNECTION_TIMED_OUT

### Validations

- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Help us

None

**Comment by RSS1102** [comment]
Please provide the min demo, thank you.
![image](https://github.com/Tencent/cherry-markdown/assets/81673017/96122345-3225-43dd-b949-b0bb0ad1d0d6)

**Comment by kylincodelab** [comment]
不是就是这个cdn，国内有时抽筋





------------------ Original ------------------
From: 阿菜 Cai ***@***.***&gt;
Date: Wed, Oct 18, 2023 9:00 PM
To: Tencent/cherry-markdown ***@***.***&gt;
Cc: security and code ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Tencent/cherry-markdown] [Bug report] (Issue #625)





 
Please provide the min demo, thank you.
