### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by erzh** [Tencent/cherry-markdown#63]
**Describe the bug**
when config.customSyntax is undefined, throw Error:
Uncaught TypeError: Cannot read properties of undefined (reading 'htmlBlock')

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 0.5.15

**Comment by jiawei686** [comment]
Thanks for your report! This might be a bug in init values. I'll investigate.

**Comment by humyfred** [comment]
hi，0,5.15 has been deprecated, you can use the version 0.5.16
