### ISSUE TITLE
Custom Theme

### ISSUE THREAD

**Issue by RSS1102** [Tencent/cherry-markdown#632]
### Discussed in https://github.com/Tencent/cherry-markdown/discussions/631

<div type='discussions-op-text'>

<sup>Originally posted by **tigawanna** November  2, 2023</sup>
Are there any docs on the theme config and the available options? , Is there a way to toggle the CSS values (data-theme) to customize the colors</div>

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/wiki/%E9%85%8D%E7%BD%AE%E4%B8%BB%E9%A2%98
已更新主题配置到wiki，请查阅指正~
