### ISSUE TITLE
8.22版的 min.js 只有 2.4m，8.27版增加到了 4.2m，这是什么原因导致的？

### ISSUE THREAD

**Issue by hbl917070** [Tencent/cherry-markdown#635]
是编译时，误把无用的资料也打包进去吗
还是新加入的功能真的需要 1.8m 的大小

我尝试把 `/src/toolbars/HookCenter.js` 里面所有 import 都删除，
然而编译后的 cherry-markdown.min.js 依然达到 3.55m

![image](https://github.com/Tencent/cherry-markdown/assets/12185698/683d1bb5-a45e-4359-915e-5510005df07d)
![image](https://github.com/Tencent/cherry-markdown/assets/12185698/81ed9085-994a-4f2a-ac99-994acbb64c4b)

**Comment by lyngai** [comment]
包体积膨胀与 mermaid 版本升级有关，相关变更涉及安全问题，必须升级。如介意体积膨胀建议使用 core 版本，并按照指引自行引入 mermaid plugin，并按需配置 Code Splitting 以缩减主资源体积。

#510 #520
