### ISSUE TITLE
[Bug report]添加颜色在手机模式无效 应该用pointer替换mouse事件,CSS建议

### ISSUE THREAD

**Issue by nenge123** [Tencent/cherry-markdown#639]
### Describe the bug

js部分
=====
看来事件是采用mousedown,应该改为pointerdown替代
设计特殊事件(交互) 用"click" 例如音频播放.
不要考虑兼容IE.

部分功能希望以插件方式加载,如流程图,公式等.,不要构建在一个缝合怪里面.

css部分
=====
在字体出使用 var(--cherry-face,"ch-icon")
因为当我使用虚拟加载时 (把cherry打包成压缩包,本地解压储存到indexdb并加载),
否则CSS仍旧读取不存在的字体URL,

当然也可以js去调用字体,完全符合统一加载
``` CSS.supports('font-format(woff2)') ```
然后添加变量注册
```
var font = new FontFace("ch-icon", "url(cherry.woff2)", {...});
await font.load();
document.fonts.add(font);
CSS.registerProperty(...)
``` 
或者 直接添加CSS规则 ``` document.styleSheets[0].insertRule("",document.styleSheets[0].cssRules.length)```

要添加全局变量标记字体已加载,避免多次重复加载.

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Help us

None

**Comment by sunsonliu** [comment]
感谢反馈~
关于缝合怪问题，我们提供了`cherry-markdown.core.js`提供基础能力，引入这个包之后，再分别引入公式（公式本身并没有被缝合进cherry里面，因为它太大了，可参考[这里](https://github.com/Tencent/cherry-markdown/issues/335)）和流程图（mermaid）就好了，详情见 [构建产物介绍](https://github.com/Tencent/cherry-markdown/wiki/%E6%9E%84%E5%BB%BA%E4%BA%A7%E7%89%A9%E4%BB%8B%E7%BB%8D)

至于其他问题的确是我们没有考虑过的情况，我们会讨论下看怎么实现or取舍

**Comment by nenge123** [comment]
> 感谢反馈~ 关于缝合怪问题，我们提供了`cherry-markdown.core.js`提供基础能力，引入这个包之后，再分别引入公式（公式本身并没有被缝合进cherry里面，因为它太大了，可参考[这里](https://github.com/Tencent/cherry-markdown/issues/335)）和流程图（mermaid）就好了，详情见 [构建产物介绍](https://github.com/Tencent/cherry-markdown/wiki/%E6%9E%84%E5%BB%BA%E4%BA%A7%E7%89%A9%E4%BB%8B%E7%BB%8D)
> 
> 至于其他问题的确是我们没有考虑过的情况，我们会讨论下看怎么实现or取舍

JS中加载 CSS字体占用不了多少代码,虽说不要兼容IE,实际上IE好像也有这些API

```
  /**
   * @property
   * @type {array}
   */
  static fonts = [];
  /**
   * 
   * @param {string} fontName 
   * @param {string} fontUrl 
   * @param {object} options 
   */
  static async addFont(fontName,fontUrl,options={"style": "normal","weight":"normal"}){
    if(Cherry.fonts.indexOf(fontName)!=-1)return !0;
    // @ts-ignore
    (await window.document.fonts.ready).add(await (new FontFace(fontName, "url("+fontUrl+")", options)).load());
    //实际缓存应用中 因为字体(blob://)早已经下载本地,所以并不需要load,当然正常URL加载时候,CSS需要这个字体就会下载,所以前者强制字体先加载,避免短暂存在的框框字
    //(await window.document.fonts.ready).add(new FontFace(fontName, "url("+fontUrl+")", options));
    Cherry.fonts.push(fontName);
    return !0;
  }

//-------
    let url = 'fonts/ch-icon.';
    let fontMime = ['woff2','woff','svg'].filter(v=>CSS.supports('CSS.supports(\'font-format('+v+')\')'))[0]||'truetype';
      switch(fontMime){
        case 'svg':
          url+='svg#ch-icon'
        break;
        case 'truetype':
          url+='ttf'
        break;
        default:
        url+=fontMime;
      }
      await Cherry.addFont('ch-icon',this.options.engine.global.urlProcessor(url,null));
```
