### ISSUE TITLE
[Bug report] 调用setMarkdown方法自动滚动屏幕问题

### ISSUE THREAD

**Issue by fyac** [Tencent/cherry-markdown#642]
### Describe the bug

如果编辑器处于屏幕不可见区域，这时候editor.setMarkdown（或者setValue）方法会自动将编辑器滚动到屏幕可视区域内，这会导致我的页面处于一个奇怪的滚动位置，因为用户可能一开始并不想滚动到编辑器的位置。
我看了这个方法的参数以及初始化配置，没有找到可以控制这种行为的方式，这是一个bug还是设计成这样有别的用意？

### System Info

```Shell
MacOs 13
Google Chrome Version 119.0.6045.123 (Official Build) (arm64)
```

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Help us

None

**Comment by sunsonliu** [comment]
确实，在执行setMarkdown时会触发编辑器focus，从而导致屏幕自动滚动。由于编辑器部分底层使用的是codemirror，刚查看codemirror的api，似乎并没有什么办法来避免这个滚动效果。

目前建议临时的修复办法是滚动到编辑区时，或者通过其他事件让编辑区可见时，再通过setMarkdown进行赋值操作。同时我们也讨论下看有没有更彻底的解决办法

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/1fc6929d-8311-4243-ad47-c2a8a97f8227)
已增加配置，在cherry初始化、调用setMarkdown/setValue接口时，根据配置来判断是否要滚动到编辑器区域，默认false会滚动到编辑区，如果不希望滚动设置为true即可，欢迎体验
