### ISSUE TITLE
关于react 编写的一些疑惑

### ISSUE THREAD

**Issue by xuliuzhu1834** [Tencent/cherry-markdown#650]
这是我用react初始化的代码
````typescript
const init = () => {
      const instance = new Cherry(config(value, onValueChange))
//      instance.setTheme('preview')
      setCherryInstance(instance)
    }

useEffect(() => {
      if (containerRef?.current) {
        init()
      }
    }, [])
````

似乎没有 setConfig这样的函数，方便我改配置。
现在如果我像改config，就只能重新渲染, 比如我像从编辑模式，改成纯预览模式，并且隐藏toolbar，现在switchMode函数无法满足要求,因为它并不会隐藏toolbar.

另外setTheme也让我很疑惑， 我用了这个函数后， 基本的样式就全部丢失了，我错过了什么配置吗？
  instance.setTheme('preview')

**Comment by sunsonliu** [comment]
感谢反馈，目前还不支持setConfig，所谓的setConfig就是要先destory再new一下。。现在destory还没实现。。。。。

至于switchMode无法隐藏工具栏的问题，应该是个bug，或者说这个api没实现好，我们重新评估下怎么搞哈，我们的预期也是.switchModel('previewOnly')后隐藏工具栏

至于setTheme，这个是cherry的主题切换哈，取值范围见下图：
![image](https://github.com/Tencent/cherry-markdown/assets/998441/e2574572-487d-4846-8619-12b34bcfbb9d)

**Comment by xuliuzhu1834** [comment]
另外 setTheme，似乎也是个BUG， 比如在config中设置了
`
{
theme: [
      { className: 'default', label: 'default' },
      { className: 'preview', label: 'preview' },
      { className: 'edit', label: 'edit' },
    ],
}
`
在外部调用setTheme(preview)，default和edit全部丢失

**Comment by nenge123** [comment]
我觉其实不需要new 
只需要重绘toolbar 不就是setConfig.
因此只需要增加setToolBar 可以删除工具API  以及可以随时注册的格式转换.

**Comment by nenge123** [comment]
主题方面如果换成CSS变量,就很好解决,

添加data-theme="xxx",不要用额外类``` .theme__default ```

.cherry:not([data-theme]),.cherry:not([data-theme="default"]){
/* 默认 */
--theme-color:;
}

**Comment by sunsonliu** [comment]
> 另外 setTheme，似乎也是个BUG， 比如在config中设置了
> 
> ```js
> {
> theme: [
>       { className: 'default', label: 'default' },
>       { className: 'preview', label: 'preview' },
>       { className: 'edit', label: 'edit' },
>     ],
> }
> ```
> 
> 在外部调用setTheme(preview)，default和edit全部丢失. 这个可能才是我只要setTheme，就丢失样式的主要原因。

首先需要确认下有没有这些主题对应的css哈，如果没有，建议参考src/sass/themes/*scss （如下图）新建负责自身业务需求的主题哈。
![image](https://github.com/Tencent/cherry-markdown/assets/998441/c25ca8ae-9b72-455b-ae82-5badda8fc71f)

**Comment by sunsonliu** [comment]
> 主题方面如果换成CSS变量,就很好解决,
> 
> 添加data-theme="xxx",不要用额外类`.theme__default`
> 
> .cherry:not([data-theme]),.cherry[data-theme="default"]{ /* 默认 */ --theme-color:; }

额。这个本质上是一样的，用户目前的编辑器状态是 `.cherry[data-theme="preview"]`，还是会出现对应的样式不存在的情况。而要解决这个问题也是很简单，只要增加一套.cherry的默认样式就好了（如下），也并不需要变量化。。
```
.cherry {
  default
}
.cherry.cherry--theme-default{
  default
}
.cherry.cherry--theme-preview{
  preview
}
```

**Comment by xuliuzhu1834** [comment]
很感谢两位的回复，我目前先按照改样式和重新new的方式来实现需求，另外期待setConfig类似功能的函数

**Comment by sunsonliu** [comment]
> 从编辑模式，改成纯预览模式

如果只是**从编辑模式，改成纯预览模式**，则不需要重新new，只需要调用.switchModel('previewOnly')后，再在cherry的容器上加一个“cherry--no-toolbar”的class哈

**Comment by sunsonliu** [comment]
> > 从编辑模式，改成纯预览模式
> 
> 如果只是**从编辑模式，改成纯预览模式**，则不需要重新new，只需要调用.switchModel('previewOnly')后，再在cherry的容器上加一个“cherry--no-toolbar”的class哈

已修复.switchModel('previewOnly')无法隐藏工具栏的问题，已提交到dev分支，可以试试哈

**Comment by youchuyu** [comment]
您好，我试了一下，在触发setTheme(theme__preview)函数以后，preview所在div的class变成了
`cherry-previewer cherry-markdowncherry-preview--full theme__preview`
其中`cherry-markdowncherry-preview--full`两个类型粘在一起了，导致继承自`cherry-markdown`的样式都不生效了。

**Comment by nenge123** [comment]
> 您好，我试了一下，在触发setTheme(theme__preview)函数以后，preview所在div的class变成了
> 
> `cherry-previewer cherry-markdowncherry-preview--full theme__preview`
> 
> 其中`cherry-markdowncherry-preview--full`两个类型粘在一起了，导致继承自`cherry-markdown`的样式都不生效了。

你多了 theme__ ，

**Comment by youchuyu** [comment]
这个应该不影响，主要是触发`setTheme()`函数后，`cherry-markdown`和`cherry-preview--full`两个class变成`cherry-markdowncherry-preview--full`了

**Comment by sunsonliu** [comment]
> 补充一下，`clearfix`和`cherry--no-toolbar`两个类也会变成`clearfixcherry--no-toolbar`

已修复并更新到dev分支了哈，欢迎尝试

**Comment by youchuyu** [comment]
收到 谢谢大佬
