### ISSUE TITLE
关于获取目录getToc以及id的问题

### ISSUE THREAD

**Issue by youchuyu** [Tencent/cherry-markdown#653]
在通过`cherryInstance?.getToc()`获取目录时，得到的目录数组的id是经过URL编码的字符串。
`
{
    "level": 1,
    "id": "%E5%9F%BA%E6%9C%AC%E8%AF%AD%E6%B3%95",
    "text": "基本语法"
}
`
cherry渲染的html元素中也是使用的这个id。
但是如果我把这个id粘贴到url的#后，希望通过anchor进行定位时，浏览器会把id转换为文字，例如：此处转换为"基本语法"，此时就不能再通过复制url进行文章的定位

**Comment by sunsonliu** [comment]
这里跟url编码与否无关，主要是`location.hash`变化的时机是否在cherry完成初始化之后。在cherry完成初始化后，location.hash变化会触发浏览器滚动到对应位置。但复制url在新浏览器打开时，hash的变化在cherry初始化之前，导致页面没有正确定位。

我们这里加个配置吧，打开配置后，cherry完成初始化后会尝试检查hash，并滚动到对应位置

**Comment by youchuyu** [comment]
好的，感谢

**Comment by sunsonliu** [comment]
已增加这个配置，`autoScrollByHashAfterInit`传值为true就好了。已提交到dev分支
![image](https://github.com/Tencent/cherry-markdown/assets/998441/ae2235f2-dfbe-4069-98ae-1d197048b89a)
