### ISSUE TITLE
[Others] 近期升级到了0.8.29，发现原本有的代码复制功能不见了，能否重新恢复该功能

### ISSUE THREAD

**Issue by mikufufucom** [Tencent/cherry-markdown#656]
下图是现在的0.8.29后的预览
![image](https://github.com/Tencent/cherry-markdown/assets/103327450/c8b50486-70ec-4e43-9e72-a3eb3c11de6d)
这里是之前的
![image](https://github.com/Tencent/cherry-markdown/assets/103327450/e4c55cff-7a93-46ae-b8a6-64ef84282e05)
![image](https://github.com/Tencent/cherry-markdown/assets/103327450/124719a0-562e-498e-81f8-3b3247bdaed2)
在配置里面确实配置了
![image](https://github.com/Tencent/cherry-markdown/assets/103327450/7d2e3f5f-2eac-48e8-9687-c7b170df545d)

**Comment by sunsonliu** [comment]
https://tencent.github.io/cherry-markdown/examples/index.html

**Comment by moxiaoli0813** [comment]
> https://tencent.github.io/cherry-markdown/examples/index.html 请问可以在这里重现么？

![image](https://github.com/Tencent/cherry-markdown/assets/103327450/7f26ed21-fe62-48af-b1a4-e41242003eba)
没有复现成功，请问可以您的看一下配置吗，还有引用的版本嘛，我记得0.8.25版那会儿我这里也是能复制的，现在在我自己的网站尝试了几遍都失败了，我直接迁移您的版本试试。
下面是我编辑页面的源码部分
https://gitee.com/moxiaoli1010/blog/blob/master/blog-ui/src/components/CherryMarkdown.vue

**Comment by sunsonliu** [comment]
抱歉，把你的配置拉到本地后测试，也没有重现出来。。可能需要你关注下复制按钮的click事件有没有被拦截之类的。。
