### ISSUE TITLE
[Bug Report]"复制内容"copy的工具栏有bug, 在示例中. 

### ISSUE THREAD

**Issue by jackrebel** [Tencent/cherry-markdown#657]
### Prerequisites

- [ ] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

![image](https://github.com/Tencent/cherry-markdown/assets/3348236/8c621f40-cc91-4b23-aa91-88c4106acae9)
点击复制内容有问题. 

### Contributing

None

**Comment by sunsonliu** [comment]
已修复，主要是引入的第三方组件的报错会阻塞复制操作。目前换了新的负责策略，在点击复制按钮后，不会把<style>里的样式放进dom的行内样式里了，请知会~
