### ISSUE TITLE
添加目录在预览时的右侧[Feature Request]

### ISSUE THREAD

**Issue by FuAdmin** [Tencent/cherry-markdown#658]
### Prerequisites

- [ ] There isn't an existing issue that requests the same feature, to avoid duplicates.

### Clear and concise description of the problem

可不可以在预览的时候添加目录
像这样
![image](https://github.com/Tencent/cherry-markdown/assets/108501535/121d5c98-d8e9-4738-bf8c-ac6895e6a5e8)

### Contributing

None

**Comment by sunsonliu** [comment]
这个功能我们之前内部讨论认为比较属于业务需求，需要业务方利用`cherry.getToc()`等api来实现。。但刚仔细想想，似乎组件内实现也行，我们后面排期实现一下

**Comment by sunsonliu** [comment]
已实现并提交到dev分支，欢迎体验。

新增了悬浮目录的配置能力（默认不开启悬浮目录），具体配置如下:
![image](https://github.com/Tencent/cherry-markdown/assets/998441/0f2d753b-9089-440b-aec1-fe4f7541bd1b)

**Comment by sunsonliu** [comment]
https://tencent.github.io/cherry-markdown/examples/index.html

已发版，可以在这里体验
