### ISSUE TITLE
[Bug Report] 表格在预览区域编辑后存在焦点锁定的问题

### ISSUE THREAD

**Issue by dreamncn** [Tencent/cherry-markdown#662]
### Prerequisites

- [X] There isn't an existing issue that reports the same bug to avoid duplicates.
- [X] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

复现步骤见视频：
1. 清空数据
2. 插入表格，在右侧预览区域进行编辑
3. 回到左侧区域继续编写文档
4. 焦点还锁定在表格区域，只能使用键盘方向键移开

https://github.com/Tencent/cherry-markdown/assets/37787014/e8f89252-af9b-42ca-aa4d-c7541b7ade69

### Contributing

No, I don't plan to at this time.

**Comment by sunsonliu** [comment]
确实，这个bug严重影响了编辑表格的体验，感谢反馈，我们定位下哈（不过这两天我主要在搞悬浮目录的feat，等搞完就搞这个哈）

**Comment by sunsonliu** [comment]
已修复并提交到dev分支，感谢反馈，也欢迎体验哈~
