### ISSUE TITLE
能否提供一份完整的参数配置文档[Others]

### ISSUE THREAD

**Issue by insistence** [Tencent/cherry-markdown#665]
首先感谢各位大佬开源了这么好用的编辑器，虽然目前文档的参数配置项全解里面的参数说明已经挺全的了，但是还是不够完整，例如我在看示例的完整编辑器demo的源码时，发现有些参数和一些可选值并没有在文档中体现，比如engine的emoji的子参数，toolbar的完整可选值，希望可以提供一份完整的参数配置文档，包括参数的可选类型以及可选值，再次感谢

**Comment by RSS1102** [comment]
文档正在建设中，可以查看[wiki-config](https://github.com/Tencent/cherry-markdown/wiki/%E9%85%8D%E7%BD%AE%E9%A1%B9%E5%85%A8%E8%A7%A3)了解配置选项

**Comment by insistence** [comment]
感谢大佬的快速回复，已经看过wiki的配置选项了，因为要开发组件并将组件引入python，所以需要完整的参数配置，先按已有的配置文档写了，期待一波完整的文档

**Comment by insistence** [comment]
感谢大佬的快速回复，已经看过wiki的配置选项了，因为要开发组件并将组件引入python，所以需要完整的参数配置，先按已有的配置文档写了，期待一波完整的文档

**Comment by sunsonliu** [comment]
toolbar的完整可选值可以看 https://github.com/Tencent/cherry-markdown/wiki/%E8%B0%83%E6%95%B4%E5%B7%A5%E5%85%B7%E6%A0%8F 这篇wiki哈

**Comment by insistence** [comment]
> toolbar的完整可选值可以看 https://github.com/Tencent/cherry-markdown/wiki/%E8%B0%83%E6%95%B4%E5%B7%A5%E5%85%B7%E6%A0%8F 这篇wiki哈

好滴，感谢大佬
