### ISSUE TITLE
[Bug]自定义上传接口给视频设置封面视频无法正常显示

### ISSUE THREAD

**Issue by insistence** [Tencent/cherry-markdown#667]
### Prerequisites

- [X] There isn't an existing issue with the same question or request to avoid duplicates.

### Issue Type

Question

### Description of the Problem or Idea

按照[wiki文档](https://github.com/Tencent/cherry-markdown/wiki/%E9%85%8D%E7%BD%AE%E5%9B%BE%E7%89%87&%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%8E%A5%E5%8F%A3)自定义了上传接口，普通模式正常，但是对于精细化控制视频，当给视频设置封面后，插入视频就无法正常显示了，请问这是什么原因
![截图](https://github.com/Tencent/cherry-markdown/assets/92962165/25cd42da-0d2c-4a90-98c9-fb7e8739e775)

### Contributing

None

**Comment by RSS1102** [comment]
看着你的封面也是一个视频文件，是不是应该切一个png图片呢？

**Comment by insistence** [comment]
> 看着你的封面也是一个视频文件，是不是应该切一个png图片呢？

大佬，试过的，一样的
![image](https://github.com/Tencent/cherry-markdown/assets/92962165/af62cea0-b33f-4ef2-8ea4-3d95541fa91e)

**Comment by sunsonliu** [comment]
收到，目测是封面的url被渲染成了<a>标签，我们修复下哈

**Comment by insistence** [comment]
> 收到，目测是封面的url被渲染成了标签，我们修复下哈

好的，感谢

**Comment by sunsonliu** [comment]
已修复并提交到dev分支，欢迎体验哈，感谢反馈~

**Comment by insistence** [comment]
> 已修复并提交到dev分支，欢迎体验哈，感谢反馈~

收到，谢谢，我想问一下大概什么时候会发下一个版本呢

**Comment by sunsonliu** [comment]
> > 已修复并提交到dev分支，欢迎体验哈，感谢反馈~
> 
> 收到，谢谢，我想问一下大概什么时候会发下一个版本呢

抱歉。。实现完后就开心的玩去了。。现在才看到，我们争取今天下午发个版本哈
