### ISSUE TITLE
希望完善下开发文档，readme中的链接好多都404了

### ISSUE THREAD

**Issue by xuliuzhu1834** [Tencent/cherry-markdown#669]
作者您好，我们已经使用了您的产品有一个月了，值得肯定的是您的交互和功能都是比较友好的， 但是也发现的诸多BUG，我这边想加入到开发中来，但是您的开发文档有些欠缺，能否完善下开发文档， 比如目录组织，架构原理，设计理念，插件开发指南等等。

**Comment by xuliuzhu1834** [comment]
另外，可以公开下需求列表吗？我们可以参与其中认领任务，加快cherry的迭代速，希望cherry能尽快出一个稳定版本

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/5d0f9d5e-459f-4338-ad2e-09f3af67b6b8)
![image](https://github.com/Tencent/cherry-markdown/assets/998441/2a999870-4d26-426b-92a4-4daf51664f04)

https://github.com/Tencent/cherry-markdown/wiki
可以在wiki里查看部门文档哈，应该对理解项目有一定的帮助~

也感谢对cherry的肯定，目前cherry主要分几块大epic：
1. cherry编辑器本身
    - 所见即所得编辑，进度20%（也就是在预览区域编辑，目前支持的有表格编辑、图片尺寸编辑、代码块编辑）
    - 异步语法，进度0%
    - 移动端兼容，进度不可估
    - 多语言/国际化， 进度70%
    - 交互优化， 进度不可估
    - 样式优化（含多主题），进度80%
3. 客户端
4. vscode插件
5. 单测
6. 文档

目前并没有“需求列表”一说，一般是在我们本职工作不紧张的时候抽空翻牌子实现一下（比如上周实现了悬浮目录的功能，这功能之前并没有排期，只是觉得有点意思就实现了），或者遇到bug反馈的时候修复下。。。
当然我们还是非常欢迎一起共建的，如果有想要实现的功能，可以先提issue。或者也可以扫一下issue，看有没有有兴趣实现的，然后评论说明下，就可以提pr了（参考这个 issue： https://github.com/Tencent/cherry-markdown/issues/291 + pr： https://github.com/Tencent/cherry-markdown/pull/659 ）
