### ISSUE TITLE
希望出一个VS Code 插件

### ISSUE THREAD

**Issue by langhuihui** [Tencent/cherry-markdown#67]
如题

**Comment by jiawei686** [comment]
感谢建议！vscode插件正在排期开发中，开发完成后会第一时间对外开源~

**Comment by hailaz** [comment]
有进展吗，挺需要的

**Comment by sunsonliu** [comment]
> 有进展吗，挺需要的

我们已经发布vscode插件了，欢迎体验：https://marketplace.visualstudio.com/items?itemName=cherryMarkdownPublisher.cherry-markdown
