### ISSUE TITLE
[Bug Report]复制一个带链接的图片，黏贴到编辑器会出现两张图片

### ISSUE THREAD

**Issue by zhiqin520** [Tencent/cherry-markdown#681]
### Prerequisites

- [ ] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

1. 右键复制图片
 ![copy](https://github.com/Tencent/cherry-markdown/assets/19601319/e992bc95-47a5-498b-96dd-bc35e89f5f7e)
3. 到编辑器黏贴图片
![paste](https://github.com/Tencent/cherry-markdown/assets/19601319/dc0af4bf-8f40-4954-b259-ba18422d4db6)
5. 会出现两张图片，一张是原链接的图片，一张是触发编辑器插入的图片

### Contributing

None

**Comment by sunsonliu** [comment]
收到，应该是 https://github.com/Tencent/cherry-markdown/commit/9f46d5e667e44d96f546bd0064332a37b212f184 这个引入的，目的是粘贴时同时粘贴excel和图片，这就导致粘贴了多张图片。。我们再优化下

**Comment by sunsonliu** [comment]
已提交到dev分支，做了取舍，如果剪切板里有html内容，就不再处理剪切板里的文件了

**Comment by sunsonliu** [comment]
> 已提交到dev分支，做了取舍，如果剪切板里有html内容，就不再处理剪切板里的文件了

似乎可以单独对“右键复制图片”的场景做下支持，在这种场景下仍然粘贴文件而不是图片链接，我后续再优化下
