### ISSUE TITLE
[Others] 请问有参数支持从外部引入mermaid吗

### ISSUE THREAD

**Issue by insistence** [Tencent/cherry-markdown#687]
想缩减webpack打包的体积，请问有参数支持从外部引入mermaid吗

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/wiki/%E6%9E%84%E5%BB%BA%E4%BA%A7%E7%89%A9%E4%BB%8B%E7%BB%8D

可以参考这篇wiki哈

**Comment by insistence** [comment]
> https://github.com/Tencent/cherry-markdown/wiki/%E6%9E%84%E5%BB%BA%E4%BA%A7%E7%89%A9%E4%BB%8B%E7%BB%8D
> 
> 可以参考这篇wiki哈

感谢您的回答，对我很有帮助，ps：wiki中的内容与现在的版本有些不匹配了，需要略作修改
