### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by cole-dda** [Tencent/cherry-markdown#69]
**Describe the bug**
在vite下无法使用

**To Reproduce**
1. npm install cherry-markdown
2. import Cherry from 'cherry-markdown';

**Expected behavior**
可以正确import

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows/macOS]
 - Browser [e.g. Chrome, Safari]
 - Version [e.g. 0.5.14]

**Additional context**

**Comment by lyngai** [comment]
是否有详细的报错信息？

**Comment by joriewong** [comment]
same issue

**Comment by joriewong** [comment]
`util.inherits is not a function`

**Comment by lyngai** [comment]
vite 增加该配置项是否能临时解决问题？ https://github.com/Tencent/cherry-markdown/issues/78#issuecomment-1002386148

**Comment by lyngai** [comment]
Issue closed. Because it may be fixed in the latest(v0.6.1) version. If the problem is not resolved, you can reopen this issue.
