### ISSUE TITLE
可以提供关于customRenderer属性的详细Demo吗？[Docs]

### ISSUE THREAD

**Issue by nnnnn319** [Tencent/cherry-markdown#690]
### Prerequisites

- [ ] There isn't an existing issue with the same question or request to avoid duplicates.

### Issue Type

Question

### Description of the Problem or Idea

需要在代码中加入其他语言的高亮渲染，发现customRenderer属性没有详细的文档说明

### Contributing

None

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/wiki/%E6%89%A9%E5%B1%95%E4%BB%A3%E7%A0%81%E5%9D%97%E8%AF%AD%E6%B3%95

已补上wiki，欢迎参考和补充哈

**Comment by nnnnn319** [comment]
好的，谢谢
