### ISSUE TITLE
使用setMarkDown(content)接口，插入内容后光标位置错位,光标在插入内容的上一行，书写内容在插入内容的下一行[Bug Report]

### ISSUE THREAD

**Issue by nnnnn319** [Tencent/cherry-markdown#699]
### Prerequisites

- [ ] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

<img width="1440" alt="截屏2024-01-25 09 37 15" src="https://github.com/Tencent/cherry-markdown/assets/52495393/1b023473-fe06-4e96-9c9b-0b47590114e5">

### Contributing

None

**Comment by sunsonliu** [comment]
如果希望光标保持在最后位置，可以在setMarkdown后再执行下面的方法：`cherryObj.editor.editor.setCursor(cherryObj.getMarkdown().length)`

另外如果希望插入内容后并选中内容，可以用这个API：`insert(content:string, isSelect = false, anchor = false, focus = true)`
更多例子可以看 https://tencent.github.io/cherry-markdown/examples/api.html

**Comment by nnnnn319** [comment]
好的，谢谢
