### ISSUE TITLE
[Bug report]每一次调用setMarkdown或者setValue，光标都被重置到最前面了，对于封装成v-model形式的vue组件非常不友好

### ISSUE THREAD

**Issue by StrongerLph** [Tencent/cherry-markdown#70]
**Describe the bug**
每一次调用setMarkdown或者setValue，光标都被重置到最前面了，对于封装成v-model形式的vue组件非常不友好
![image](https://user-images.githubusercontent.com/47054165/147205001-dbfddf92-df5e-4030-a8f3-828cfe7c5d9d.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows/macOS]
 - Browser [e.g. Chrome, Safari]
 - Version [e.g. 0.5.14]

**Additional context**

**Comment by sunsonliu** [comment]
有道理，我们给setMarkdown和setValue增加第二个参数吧，autoRestoreCursor = true 会尝试保持之前的光标位置。
这里逻辑比较复杂，尤其是在光标之前变动内容的时候，盲目按照偏移量恢复光标不符合预期，比如原始内容是 `ABC光标DEF`，当内容变成`AABCDEF`的时候，光标会出现在`AAB光标CDEF`，这是不符合预期的，所以需要对setValue前后的内容进行一次diff，然后计算出光标变更偏移量，最终实现光标出现在`AABC光标DEF`，这块有些开发工作量，我们排期搞下哈

**Comment by power721** [comment]
vue组件多次创建Cherry实例怎么办？
Cherry没有destroy()方法

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/releases/tag/v0.6.6

**Comment by SKHon** [comment]
@sunsonliu 如何destroy啊？有办法吗

**Comment by sunsonliu** [comment]
> @sunsonliu 如何destroy啊？有办法吗

还没实现这个api，如果急用，可以先 `cherry.wrapperDom.remove();`。。。

**Comment by gspgsp** [comment]
@sunsonliu  还没实现这个api，如果急用，可以先 cherry.wrapperDom.remove();。。。

这个确实有用，我是在nuxt下使用的，希望有个destroy方法
