### ISSUE TITLE
图片转换html失败

### ISSUE THREAD

**Issue by xuliuzhu1834** [Tencent/cherry-markdown#701]
### Prerequisites

- [ ] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

```
![错误.png](/file/download/local/1706170449680/åºç¨çæ¿ (1).png) 
```

这个语法在程序中无法正常转换成正常的png

![image](https://github.com/Tencent/cherry-markdown/assets/8508762/af52aa6f-5a01-4d50-bbf7-f8effc1e5ad4)

### Contributing

None

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/791572c6-dc00-407a-a5d7-4cc98009229f)

是这里的括号跟图片的语法冲突了哈

**Comment by xuliuzhu1834** [comment]
看了你们图片正则
```
/((?<!\\))!\[([^\n]*?)\][ \t]*(?:\(([^"][^\s]+?)(?:[ \t]((?:".*?")|(?:'.*?')))?\)|\[((?:[^\n]*?\S[^\n]*?))\])({[^{}]+?})?/g
```
话说，如果我保证我的url是安全的， 能加个配置，不使用你们的正则， 用户自己配置个宽松正则出来吗？

**Comment by xuliuzhu1834** [comment]
emmmmmmmmm 算了 我还是在文件上传的时候 直接将文件名称中带有"()"的都去掉吧

**Comment by lyngai** [comment]
> emmmmmmmmm 算了 我还是在文件上传的时候 直接将文件名称中带有"()"的都去掉吧

这个问题是有解决方案的，通过 `<>` 包裹链接支持语法冲突的字符，待支持。 `![](</path/to/image(1).jpg>)`
