### ISSUE TITLE
[Bug Report] 热更新时触发初始化会导致存在多个编辑器内容

### ISSUE THREAD

**Issue by joker585** [Tencent/cherry-markdown#702]
### Prerequisites

- [X] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

 本地开发在didmount阶段做编辑器初始化， 热更新时触发初始化会导致存在多个编辑器内容，建议在初始化阶段对目标元素内容进行清空，或者提供销毁api在unmount阶段调用

### Contributing

None

**Comment by sunsonliu** [comment]
已实现并提交到dev，使用例子为：`cherry.destroy()`

**Comment by sunsonliu** [comment]
已发版，可以在 https://tencent.github.io/cherry-markdown/examples/api.html 这里体验

**Comment by joker585** [comment]
十分感谢！
