### ISSUE TITLE
[Feature Request] 希望增加工具栏的动态设置功能

### ISSUE THREAD

**Issue by joker585** [Tencent/cherry-markdown#703]
### Prerequisites

- [X] There isn't an existing issue that requests the same feature, to avoid duplicates.

### Clear and concise description of the problem

有切换内容时更改toolBarRight内容的需求

### Suggested solution

希望可以增加一个setToolbarRight/insertToolbarRight/removeToolbarRight类似的功能

### Contributing

None

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/3591d5aa-b5bb-40da-9903-c80a3c3bfec7)

已实现并提交到dev分支，使用例子为：
```
cherry.resetToolbar('toolbarRight', ['bold', 'italic'])
```

**Comment by sunsonliu** [comment]
已发版

**Comment by joker585** [comment]
十分感谢！
