### ISSUE TITLE
[Feature Request] 锚点延迟问题

### ISSUE THREAD

**Issue by joker585** [Tencent/cherry-markdown#707]
### Prerequisites

- [X] There isn't an existing issue that requests the same feature, to avoid duplicates.

### Clear and concise description of the problem

autoScrollByHashAfterInit这个配置很棒，但是我遇到了另外一个问题，在react项目中，当我切换一个带锚点的路由时，这里我并没有重新渲染编辑器，而是对编辑器的内容做了setMarkdown更新，然而autoScrollByHashAfterInit这个没有办法做到在修改value时也做锚点定位，期望能暴露出来一个api，比如说scrollViewToAnchor来让我可以在修改value之后来手动修正

### Contributing

None

**Comment by joker585** [comment]
当我调用switchModel时也会出现这个困扰

**Comment by sunsonliu** [comment]
收到，这里会安排暴露一个api来控制锚点定位哈

**Comment by sunsonliu** [comment]
已实现api并提交到dev分支，用法如下：
```
<h2 id="xxx">xxx</he>
...
...
cherryObj.previewer.scrollToId('xxx');
cherryObj.previewer.scrollToId('#xxx');
```

**Comment by joker585** [comment]
感谢
