### ISSUE TITLE
[Others]  node后端进行makeHtml，怎么没有样式，或者说样式怎么不生效呢？

### ISSUE THREAD

**Issue by win-magic** [Tencent/cherry-markdown#709]
makeHtml的界面显示效果和editor时不一样；个人理解，应该显示和预览是一致的，在做nuxt的ssr，发现样式没生效；

**Comment by JL-Code** [comment]
> makeHtml的界面显示效果和editor时不一样；个人理解，应该显示和预览是一致的，在做nuxt的ssr，发现样式没生效；

你 Nuxt 集成 cherry-markdown 成功了吗？
