### ISSUE TITLE
[Bug report]工具栏-插入-[图片、视频等]功能失效

### ISSUE THREAD

**Issue by Morris-G** [Tencent/cherry-markdown#71]
**Describe the bug**
插入-图片失效，没有选择文件的弹框

**To Reproduce**
1.点击工具栏-插入
2.点击图片

**Expected behavior**
弹出选择文件的弹框

**Environment (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]
 - Version [0.5.16]

**Additional context**
[这里的代码](https://github.com/Tencent/cherry-markdown/blob/cb22da6e252dfd216f49855a2966fa88198910ff/src/toolbars/hooks/Insert.js#L85)设置input类型的时候有问题，传入的['image', 'video', 'pdf']等是无效值，此时浏览器会将其设置为默认的'text'，参考[MDN文档](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/Input#%3Cinput%3E_types)所以不会出现选择文件的弹框。0.5.14版本中默认的就是'file'，不知为何后来改掉了...另外目前没有限制指定类型的字段，希望加入限制，或添加相应的配置项。

**Comment by jiawei686** [comment]
收到，0.5.16版本中参数的使用出现问题，已在0.5.17版本中修复并紧急发布。已预留字段，后续版本会通过accept进行适当限制，感谢反馈！
