### ISSUE TITLE
[Others] code 粘贴的时候，能进行格式化吗？

### ISSUE THREAD

**Issue by win-magic** [Tencent/cherry-markdown#712]
1、复制的代码，粘贴后就乱了，最后只显示一行
2、需要安装插件，实现自动格式化吗？类似vscode的保存，自动格式化那种效果

**Comment by sunsonliu** [comment]
请问是从哪复制的代码，vscode么。然后粘贴后乱码是什么效果呢，可以截图看看不。

针对第二个问题，想确认下，这里的自动格式化是对代码块里的代码进行格式化，还是对md内容进行格式化？如果是前者的话我们目前并没有这样的规划，因为我们缺乏各语言代码风格格式化的经验。如果是后者我们是有这样的计划，不过还在孵化中。。。

**Comment by win-magic** [comment]
<img width="1192" alt="infoflow 2024-02-01 16-26-29" src="https://github.com/Tencent/cherry-markdown/assets/158010019/587259bd-5112-4b5f-b667-b84f14a2a8ae">
这种的，粘贴后只显示1行，但是在控制台粘贴有对应的换行，想粘贴后至少右侧里面自动格式化。

**Comment by sunsonliu** [comment]
想问下，是从哪里粘贴过来的呢？vscode么

**Comment by win-magic** [comment]
Ai大模型给出的一些参考代码

**Comment by sunsonliu** [comment]
收到，我们定位下

**Comment by win-magic** [comment]
文心一言等可以测测

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/138b1155-e47a-4890-a5d1-c7000180ac85)
这个问题比较复杂，可以在粘贴后选择“**TEXT**” 来临时解决哈

**Comment by sunsonliu** [comment]
是 [复制Html粘贴成MD语法](https://github.com/Tencent/cherry-markdown/wiki/%E7%89%B9%E6%80%A7%E5%B1%95%E7%A4%BA-features#%E7%89%B9%E6%80%A7-1%E5%A4%8D%E5%88%B6html%E7%B2%98%E8%B4%B4%E6%88%90md%E8%AF%AD%E6%B3%95) 这个特性导致的这个问题，目前我们还没有特别好的解决方案，建议还是在粘贴后，选择“TEXT”就好了，这个选择有记忆，下次再粘贴默认就是TEXT格式了

**Comment by win-magic** [comment]
TEXT这个选择，怎么出现呢？

**Comment by sunsonliu** [comment]
在粘贴的时候有选项哈，可以看这个：
![html转md](https://raw.githubusercontent.com/Tencent/cherry-markdown/main/examples/images/feature_copy.gif)
