### ISSUE TITLE
[Feature Request] 希望提供拦截粘贴行为的回调

### ISSUE THREAD

**Issue by joker585** [Tencent/cherry-markdown#714]
### Prerequisites

- [X] There isn't an existing issue that requests the same feature, to avoid duplicates.

### Clear and concise description of the problem

需求背景是在粘贴链接时想要对链接进行处理，比如说对粘贴的链接自动转换成[超链接](href)，或者对链接内容进行替换等，希望可以在config阶段提供onPaste类似的回调

### Contributing

None

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/commit/e9154f6ad05cf081cfe90dae4ff06dcf3fc58cd8#diff-ac619e69fcccbc9dfbfe634055467f773c2c4bb88617ae6e59756a28da67eb7cR366

已增加配置并提交到dev分支
