### ISSUE TITLE
[Bug Report] 使用makeHtml对markdown转换时发生错误

### ISSUE THREAD

**Issue by Leeero** [Tencent/cherry-markdown#724]
### Prerequisites

- [ ] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

```
const { default: CherryEngine } = require('cherry-markdown/dist/cherry-markdown.engine.core.common');
const cherryEngineInstance = new CherryEngine();
const htmlContent = cherryEngineInstance.makeHtml('# welcome to cherry editor!');
```
在使用makeHtml进行转换是，当 markdown 内容为：'TCE\u7684\u4ea7\u54c1\u529f\u80fd\u548c\u4ea7\u54c1\u4f18\u52bf\u5305\u62ec\uff1a\n-'时，转换结果发生错误，结果被转换成：
`<h2 id="tce%E7%9A%84%E4%BA%A7%E5%93%81%E5%8A%9F%E8%83%BD%E5%92%8C%E4%BA%A7%E5%93%81%E4%BC%98%E5%8A%BF%E5%8C%85%E6%8B%AC%EF%BC%9A"><a href="#tce%E7%9A%84%E4%BA%A7%E5%93%81%E5%8A%9F%E8%83%BD%E5%92%8C%E4%BA%A7%E5%93%81%E4%BC%98%E5%8A%BF%E5%8C%85%E6%8B%AC%EF%BC%9A" class="anchor"></a>TCE的产品功能和产品优势包括：</h2>`
实际上的结果应该是：`<p data-type="p">TCE的产品功能和产品优势包括：</p><ul class="cherry-list__default"><li class="cherry-list-item"><p></p></li></ul>`
经排查出现原因是因为此时markdown的结尾是'-',就会发生转换错误。'- '-后加上空格，也能正确转换。

**Comment by sunsonliu** [comment]
收到，流式传输的场景确实会出现这个问题，我们增加个配置来规避这种情况~

**Comment by sunsonliu** [comment]
已发版（V 0.8.41），欢迎使用新版
