### ISSUE TITLE
[Bug Report] 上传flv等不常见的文件时，不会触发uploadfile

### ISSUE THREAD

**Issue by Baihhh** [Tencent/cherry-markdown#725]
### Prerequisites

- [ ] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

win电脑上传flv等不常见的文件时，不会触发uploadfile；mac电脑可以触发
初步判断是因为flv等不常见文件在win上的type为""，所以在上传之前会忽略掉这部分文件
![image](https://github.com/Tencent/cherry-markdown/assets/63110802/4be7f005-3404-4b60-8aaa-9a3036200a5e)

### Contributing

None

**Comment by sunsonliu** [comment]
收到~这个有点难搞，我们想想怎么办哈
