### ISSUE TITLE
克隆仓库到本地问题

### ISSUE THREAD

**Issue by veitool** [Tencent/cherry-markdown#729]
克隆仓库到本地问题，直接下载包似乎也是不全的（dist目录）。
![clone](https://github.com/Tencent/cherry-markdown/assets/79551972/2751b9b6-8c3a-4f09-9919-4420bca98905)

**Comment by lyngai** [comment]
从日志看是本地 dns 问题，解析不到 github.com

**Comment by veitool** [comment]
> 从日志看是本地 dns 问题，解析不到 github.com

谢谢！是的。
但本地clone其他的仓库可以，用其他的服务器克隆这个也是不全。奇怪了！

**Comment by lyngai** [comment]
仓库使用了 lfs 托管部分文件，lfs 依赖 git-lfs 进程，建议是排查机器的网络代理是否有覆盖。

**Comment by veitool** [comment]
> 仓库使用了 lfs 托管部分文件，lfs 依赖 git-lfs 进程，建议是排查机器的网络代理是否有覆盖。

好的，谢谢！
