### ISSUE TITLE
[Bug report]编辑器重复引入MathJax导致控制台报错

### ISSUE THREAD

**Issue by Morris-G** [Tencent/cherry-markdown#73]
**Describe the bug**
使用src引入MathJax时，多个实例切换时控制台会报错

**To Reproduce**
1. 在Vue 2.x环境下使用Cherry封装编辑器组件
``` javascript
const options =  {
  ...
  engine: {
    ...
    syntax: {
      ...
      mathBlock: {
           engine: 'MathJax', // katex或MathJax
           src: './static/mathjax/text-svg.js'
      },
  ...
}
this.cherry = new Cherry(this.options)
```
2. 外层页面引用封装的组件
3. 外层页面切换不同的MD文档

**Expected behavior**
正常显示，控制台无报错

**Screenshots**
控制台报错：
![控制台报错](https://user-images.githubusercontent.com/33714914/147430699-cadd6a9a-de90-4731-a6eb-d591f3c5563b.png)
多次重复引入：
![多次重复引入](https://user-images.githubusercontent.com/33714914/147430763-dea30fe9-8352-4d05-9489-9cdb7ad3cde6.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version:0.5.14

**Additional context**
感觉像是Engine.js[这里](https://github.com/Tencent/cherry-markdown/blob/02c500b24fe4ce4ad4772337e6665ac24c4dcc6f/src/Engine.js#L69)在动态加载script的时候没有做是否存在的判断，每次都会加载一遍对应的js文件，然后mathjax抛出了错误...

如果使用externals配置MathJax为window.MathJax同时设置mathBlock的src为空，此时可以自行控制引入js文件，但是插件（cherry配置默认引入的'input/asciimath', '[tex]/noerrors', '[tex]/cancel', '[tex]/color', '[tex]/boldsymbol'）不会自动引入，需要手动一个一个去加载，感觉不太友好...
```javascript
if (!window.MathJax) {
  loadScript(MATH_JAX_LIB).then(() => {
     this.initCherry()
  })
} else {
     this.initCherry()
}
```
设置externals时未自动加载plugins：
![设置externals时未自动加载plugins](https://user-images.githubusercontent.com/33714914/147431820-faa0fbdc-c234-41f3-94e5-7ca65c90d0b4.png)
设置mathBlock.src时会自动加载同目录下的plugins：
![设置mathBlock.src时会自动加载同目录下的plugins](https://user-images.githubusercontent.com/33714914/147431859-17bcdf23-f453-4263-b563-82f25d7f3bef.png)

**Comment by jiawei686** [comment]
收到，问题描述很详细，我们优化下mathjax的引入机制，感谢反馈！
