### ISSUE TITLE
[Bug Report] showToolbar功能失效

### ISSUE THREAD

**Issue by joker585** [Tencent/cherry-markdown#733]
### Prerequisites

- [ ] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

toolbars.showToolbar=false在previewOnly状态switchModel到editOnly时未生效

### Contributing

None

**Comment by joker585** [comment]
类似的问题
[初始化阶段设置的toolbar在切换编辑模式时未生效](https://github.sheincorp.cn/Tencent/cherry-markdown/issues/721)
toolbars中的配置是否都有这个通病？

**Comment by sunsonliu** [comment]
这里的逻辑做了修改（https://github.com/Tencent/cherry-markdown/commit/6294fa997485a5e83bb901f200e377e661547182），switchModel增加了第二个参数{showToolbar:Boolean}，文档还么有更新，可以这么调用：
```
cherry.switchModel('editOnly', false); //切换到编辑模式并隐藏工具栏
cherry.switchModel('editOnly', true); //切换到编辑模式并展示工具栏
```
