### ISSUE TITLE
[Others] 如何禁用联想面板？

### ISSUE THREAD

**Issue by djllll** [Tencent/cherry-markdown#743]
我想要禁用联想面板，

![image](https://github.com/Tencent/cherry-markdown/assets/72971770/01d6a814-31f1-4208-8e45-54b71caeec7b)

但我没有在配置中找到相关的配置项

**Comment by sunsonliu** [comment]
哦。。并没有开关控制关闭这个特性，我们后面加上这个配置~感谢反馈~

**Comment by sunsonliu** [comment]
已发版（V 0.8.41），欢迎使用新版
