### ISSUE TITLE
draw.io 引入问题

### ISSUE THREAD

**Issue by RSS1102** [Tencent/cherry-markdown#745]
> > 请问下,公式功能应该怎么引入?我现在是这么写的,公式和 draw.io 没有反应 请问下怎么用公式功能和draw.io?该调整哪里?这是我的html,目前无法用公式和draw.io,请问我该怎么写?
> > <title>Document</title> <script src="./cherry-markdown.js"></script>
> > <script> new Cherry({ id: 'markdown-container', value: '# 到此一游!', toolbars: { // 定义顶部工具栏 toolbar: [ 'undo', 'redo', '|', // 把字体样式类按钮都放在加粗按钮下面 { bold: ['bold', 'italic', 'underline', 'strikethrough', 'sub', 'sup', 'ruby'] }, 'color', 'size', '|', 'header', 'list', 'panel', '|', // 把插入类按钮都放在插入按钮下面 { insert: ['image', 'audio', 'video', 'link', 'hr', 'br', 'code', 'formula', 'toc', 'table', 'drawIo'] }, 'graph' ], // 定义侧边栏，默认为空 sidebar: ['theme', 'mobilePreview', 'copy'], // 定义顶部右侧工具栏，默认为空 // user_cola,2024年4月12日21:47:12,需要使用导出功能时,必须有两行字,才可以导出,我想了想,可能是因为 toolbarRight: ['fullScreen', 'export'], // 定义选中文字时弹出的“悬浮工具栏”，默认为 ['bold', 'italic', 'underline', 'strikethrough', 'sub', 'sup', 'quote', '|', 'size', 'color'] bubble: ['bold', 'italic', 'underline', 'strikethrough', 'sub', 'sup', 'ruby', '|', 'color', 'size',], // 定义光标出现在行首位置时出现的“提示工具栏”，默认为 ['h1', 'h2', 'h3', '|', 'checklist', 'quote', 'table', 'code'] float: ['table', 'code', 'graph'], }, }); </script>
> 
> 你需要引入`draw.io`资源: https://github.com/Tencent/cherry-markdown/blob/main/examples/scripts/index-demo.js#L206

佬,好像有点问题,我直接用 live-server 运行了 /docs/public/example/ 目录,然后点 draw.io,显示一个弹窗,但弹窗是空白的,和官网的不一样,请问应该看是哪里的问题?该怎么弄一下?

![image](https://github.com/Tencent/cherry-markdown/assets/76413761/79c903e0-2d27-42ee-89b0-b8d154026e26)

![image](https://github.com/Tencent/cherry-markdown/assets/76413761/6fb40394-d4d9-4a24-bb9c-0612991ace7c)

看这些文件都请求了

![image](https://github.com/Tencent/cherry-markdown/assets/76413761/43db3e67-4fff-458f-8171-2fcd307f5c39)

_Originally posted by @honglvagan in https://github.com/Tencent/cherry-markdown/issues/335#issuecomment-2053520553_

**Comment by RSS1102** [comment]
https://github.com/Tencent/cherry-markdown/blob/main/examples/index.html

你可以参考这个实例，引入对应的draw.io资源文件。

**Comment by honglvagan** [comment]
> https://github.com/Tencent/cherry-markdown/blob/main/examples/index.html
> 
> 你可以参考这个实例，引入对应的draw.io资源文件。

谢谢哥,我完全懂了,在 cherry-markdown-main 目录下用 live-server 就能运行了,非常感谢
