### ISSUE TITLE
video自定义视频播放器

### ISSUE THREAD

**Issue by wr1688** [Tencent/cherry-markdown#746]
video自定义视频播放器,插入视频后，使用其他播放器，当前版本是否可以实现呢?可以实现的话，分享下文档?

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/bad21e28-2da9-4aa7-9103-c7f5267ea313)
优化了下自定义视频播放器配置的能力（原来也是支持的，不过原来的配置能力实现起来有点复杂）
如果使用目前版本（V0.8.40及以前），可以这么配置实现：
```
engine: {
    syntax: {
      image: {
        videoWrapper: (link) => {
          // 先判断是否是视频，如果是视频则返回自定义的内容，如果不是，需要自己实现图片、音频等内容（是不是很难用）
          return ‘xxxx‘’’;
        },
      },
  }
}
```

在使用新版本（比如dev分支的版本），则可以这么配置实现：
```
engine: {
    syntax: {
      image: {
        videoWrapper: (link, type, defaultWrapper) => {
          if (type !== 'video')
            return defaultWrapper;
          return 自己的视频解析(link);
        },
      },
  }
}
```

**Comment by sunsonliu** [comment]
> ![image](https://private-user-images.githubusercontent.com/998441/325537821-bad21e28-2da9-4aa7-9103-c7f5267ea313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzU3OTUsIm5iZiI6MTcxNDk3NTQ5NSwicGF0aCI6Ii85OTg0NDEvMzI1NTM3ODIxLWJhZDIxZTI4LTJkYTktNGFhNy05MTAzLWM3ZjUyNjdlYTMxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwNjA0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzUxMjhmNGQxMmNmYzY4YWQwMDA1MGU4NjVlZTgzNTYzYjZkNzE1NmE5YzE1ZDIxNmZhZjA5NmFhNzE4ZmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K-LYeF-u9tAAKtm0IzlltvsjM_PTZzzlNC8fm0mJuFc) 优化了下自定义视频播放器配置的能力（原来也是支持的，不过原来的配置能力实现起来有点复杂） 如果使用目前版本（V0.8.40及以前），可以这么配置实现：
> 
> ```
> engine: {
>     syntax: {
>       image: {
>         videoWrapper: (link) => {
>           // 先判断是否是视频，如果是视频则返回自定义的内容，如果不是，需要自己实现图片、音频等内容（是不是很难用）
>           return ‘xxxx‘’’;
>         },
>       },
>   }
> }
> ```
> 
> 在使用新版本（比如dev分支的版本），则可以这么配置实现：
> 
> ```
> engine: {
>     syntax: {
>       image: {
>         videoWrapper: (link, type, defaultWrapper) => {
>           if (type !== 'video')
>             return defaultWrapper;
>           return 自己的视频解析(link);
>         },
>       },
>   }
> }
> ```

已发版（V 0.8.41），欢迎使用新版
