### ISSUE TITLE
预览点击事件无效

### ISSUE THREAD

**Issue by q2316367743** [Tencent/cherry-markdown#749]
### Prerequisites

- [ ] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

onClickPreview这个事件之间听到了纯预览模式的页面，但是编辑&预览中，预览没有收到事件。

主要的目的是，我使用vue开发，toc生成的目录直接使用hash，会导致路由变化

### Contributing

None

**Comment by RSS1102** [comment]
重复， https://github.com/Tencent/cherry-markdown/issues/750 跟进
