### ISSUE TITLE
[Bug Report] 编辑&预览模式下，a标签有问题

### ISSUE THREAD

**Issue by q2316367743** [Tencent/cherry-markdown#750]
### Prerequisites

- [ ] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

onClickPreview这个事件之间听到了纯预览模式的页面，但是编辑&预览中，预览没有收到事件。

主要的目的是，我使用vue开发，toc生成的目录直接使用hash，会导致路由变化

### Contributing

No, I don't plan to at this time.

**Comment by RSS1102** [comment]
能提供一个最小复现嘛？谢谢。

**Comment by q2316367743** [comment]
能提供截图，其实就是有个配置，可以配置目录是使用hash定位还是使用事件，但是这个设置貌似只在纯预览的视图生效了

**Comment by sunsonliu** [comment]
toc生成的目录目前只能hash，倒是右侧滑目录是支持配置是否用hash的。
onClickPreview确实在双栏模式下失效（当时是设计如此）
我们看看怎么修复哈，大概会做成这样：
- toc生成的目录也支持配置不用hash定位
- 在双栏模式下也支持onClickPreview

**Comment by sunsonliu** [comment]
> toc生成的目录目前只能hash，倒是右侧滑目录是支持配置是否用hash的。 onClickPreview确实在双栏模式下失效（当时是设计如此） 我们看看怎么修复哈，大概会做成这样：
> 
> * toc生成的目录也支持配置不用hash定位
> * 在双栏模式下也支持onClickPreview

https://github.com/Tencent/cherry-markdown/commit/0cff250305ff5db08a4deb9777ddd698323c3411
已实现上述两个特性
