### ISSUE TITLE
[Others] 在toolbar中未添加drawIo时, 如何使用api方式调用drawIo

### ISSUE THREAD

**Issue by edeye** [Tencent/cherry-markdown#755]
在toolbar配置了drawIo时,可以使用 cherryObj.toolbar.toolbarHandlers.drawIo()方式调用

在toolbar中未添加drawIo时, 如何使用api方式调用drawIo

**Comment by edeye** [comment]
目前可以设置样式为隐藏解决该问题

<style>
span[title="draw.io"] {
  display: none;
}
</style>

**Comment by sunsonliu** [comment]
确实，目前并不支持调用未配置到toolbar里的工具组件，感谢反馈哈，我们后续考虑在toolbar配置里增加一个表示隐藏的特殊工具组件

**Comment by sunsonliu** [comment]
已发布
