### ISSUE TITLE
代码块、行内代码相关交互优化

### ISSUE THREAD

**Issue by sunsonliu** [Tencent/cherry-markdown#767]
## 优化点1
当用户输入一个`` ` ``符号时，给出联想如下：
![image](https://github.com/Tencent/cherry-markdown/assets/998441/08e5a5ad-7765-4820-8594-7ec63b25aca9)
- 当用户点击“行内代码”后，插入两个` `` `，并让光标处于两个` `` `中间
- 当用户点击“代码块”后，插入` ```\n\n``` `，并让光标处于第二行起始位置

## 优化点2
当用户输入三个 ` ``` `符号后，给出语言联想如下：
![image](https://github.com/Tencent/cherry-markdown/assets/998441/8e01ce61-fe8f-4106-9ea3-80c94fd480b2)
- 当用户点击其中一个语言后（如点击javascript），插入` javascript\n\n``` `，并让光标处于第二行起始位置

## ~~优化点3~~
~~高亮代码块语言，当用户点击时出现语言选择框~~
![image](https://github.com/Tencent/cherry-markdown/assets/998441/8820a09e-1cfc-45c4-8451-6e9836b38230)
- ~~用户点击其中一个语言后进行替换~~

## 优化点4
（见第一条评论）
在优化点2的基础上，用户输入三个 ` ``` `符号后，给出语言联想，这时用户可以按上下键选择语言（现有功能），还可以继续输入，此时联想根据用户输入匹配命中的语言列表（应该也是现有功能）

**Comment by foxfire881** [comment]
补充一个优化点4：自动过滤提示代码种类。
优化点2的列表太长了，可以只显示top常用的几种。其他的每多敲一个字符，过滤匹配的语言种类显示在列表里。
例如∶
输入```弹出列表提示常用的10~20种语言；
输入```c列表过滤只显示c、cpp、csharp、ascii……等以字母c开头或者包含字母c的语言，以后每多敲一个字符，匹配命中的精确度越高，像搜索引擎提示词那样；
输入```ja基本就只过滤剩下java和javascript两种了

**Comment by foxfire881** [comment]
另外优化点3感觉不是很必要，理由∶
1、用户贴代码之前肯定知道自己贴的是啥语言，一般初次就确定好了，不会或者很少贴完了再回头去改代码类型。这个优化点使用频率不高；
2、\```标记符号是通过键盘敲的，敲完后此时手还在键盘上，要修改语言种类直接敲几个back回退键，配合上述优化点4的列表提示、命中过滤功能效率更高。如果还要通过点击鼠标、展开列表、点击选择这种方式修改，手还要从键盘上移开，眼睛也还要离开屏幕去找找鼠标在哪儿……一来一回太影响效率了，毕竟markdown本来就是为了提高文档编写效率而生。

**Comment by sunsonliu** [comment]
> 另外优化点3感觉不是很必要，理由∶ 1、用户贴代码之前肯定知道自己贴的是啥语言，一般初次就确定好了，不会或者很少贴完了再回头去改代码类型。这个优化点使用频率不高； 2、```标记符号是通过键盘敲的，敲完后此时手还在键盘上，要修改语言种类直接敲几个back回退键，配合上述优化点4的列表提示、命中过滤功能效率更高。如果还要通过点击鼠标、展开列表、点击选择这种方式修改，手还要从键盘上移开，眼睛也还要离开屏幕去找找鼠标在哪儿……一来一回太影响效率了，毕竟markdown本来就是为了提高文档编写效率而生。

确实，当时设想的时候觉得“不做白不做”，现在想想的确违背markdown高效编写的初衷，我修改下描述，感谢提醒~~
