### ISSUE TITLE
调用makeHtml方法转换 markdown 时，发生转换错误。

### ISSUE THREAD

**Issue by Leeero** [Tencent/cherry-markdown#770]
### Prerequisites

- [ ] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

使用makeHtml方法转换 markdown 语法时，转换出错，具体如下：
```
const { default: CherryEngine } = require('cherry-markdown/dist/cherry-markdown.engine.core.common');
const cherryEngineInstance = new CherryEngine();

const str = '\u4f18\u60e0\u590d\u5236\u8bf4\u660e\n---\n\n\u4f18\u60e0';

const result = cherryEngineInstance.makeHtml(str);
```
预期结果应该是：
![image](https://github.com/Tencent/cherry-markdown/assets/22819077/2a9cd3df-a5f9-4209-a344-4ad7aa5fc2da)
但是实际上被转换成了：
![image](https://github.com/Tencent/cherry-markdown/assets/22819077/ad7bb8f4-7115-4bf4-bc6c-9cbda2f7e178)

### Contributing

None

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/671397cf-628d-49f4-8170-17a73c14bb87)


**这是命中了标题语法了，可以考虑以下两种解决方案：**


1. 
![image](https://github.com/Tencent/cherry-markdown/assets/998441/051d25e5-4b84-48fc-ba98-765cfa575c59)
2. 
![image](https://github.com/Tencent/cherry-markdown/assets/998441/04dda5b7-ee7b-4daa-b990-642973c2a889)

**Comment by Leeero** [comment]
在解析过程之前有没有什么办法呢？比如说类似判断命中的这个语法词然后特殊处理(类似之前处理"\n-"这种)？因为现在的使用场景是解析其他用户输入的 markdown(内容不可控)。

**Comment by sunsonliu** [comment]
额，这个是markdown[标准语法](https://www.markdown.xyz/basic-syntax/)来着，一个熟悉markdown的用户输入这段内容预期也是出现“标题”。如果盲目的去掉该语法会让正常的markdown书写用户产生困惑。如果一定要去掉的话，可以考虑提前过滤下用户输入内容如：`cherryEngineInstance.makeHtml(str.replace(/([^\n]\n)(-{1,}\s*)\n/g, "$1\\$2\n"))`

**Comment by Leeero** [comment]
> 额，这个是markdown[标准语法](https://www.markdown.xyz/basic-syntax/)来着，一个熟悉markdown的用户输入这段内容预期也是出现“标题”。如果盲目的去掉该语法会让正常的markdown书写用户产生困惑。如果一定要去掉的话，可以考虑提前过滤下用户输入内容如：`cherryEngineInstance.makeHtml(str.replace(/([^\n]\n)(-{1,}\s*)\n/g, "$1\\$2\n"))`

抱歉，忘了回复，已经用其他方式解决了，感谢回复～
