### ISSUE TITLE
[Docs] 为什么没有文字选中监听事件？

### ISSUE THREAD

**Issue by dongmucat** [Tencent/cherry-markdown#774]
### Prerequisites

- [ ] There isn't an existing issue with the same question or request to avoid duplicates.

### Issue Type

Question

### Description of the Problem or Idea

- [ ] 希望有一个文字选中监听事件

### Contributing

None

**Comment by sunsonliu** [comment]
收到，安排~

**Comment by sunsonliu** [comment]
已实现，可在[这里](https://github.com/Tencent/cherry-markdown/wiki/%E4%BA%8B%E4%BB%B6&%E5%9B%9E%E8%B0%83#selectionchange-%E7%BC%96%E8%BE%91%E5%8C%BA%E9%80%89%E5%8C%BA%E6%94%B9%E5%8F%98%E6%97%B6%E8%A7%A6%E5%8F%91)查看文档，目前在dev分支
