### ISSUE TITLE
[VSCode Plugin] vscode plugin `Usage` 功能设置无效。

### ISSUE THREAD

**Issue by RSS1102** [Tencent/cherry-markdown#776]
### issue type

Bug

### Clear and concise description of the problem or idea.

vscode plugin 的设置取值到workspace的配置了，应该取值到User配置。

<img width="754" alt="723dfc174e86085025fa3076290f7d3" src="https://github.com/Tencent/cherry-markdown/assets/81673017/51c0b79e-503d-4a86-8721-0aa130962fd9">

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Help us

Yes, I would like to try submitting a PR for this issue.

**Comment by sunsonliu** [comment]
vscode插件0.0.16已发布
