### ISSUE TITLE
[Docs]自定义语法demo少了engine这一层

### ISSUE THREAD

**Issue by huchaolin** [Tencent/cherry-markdown#778]
### Prerequisites

- [X] There isn't an existing issue with the same question or request to avoid duplicates.

### Issue Type

Documentation Error

### Description of the Problem or Idea

<img width="957" alt="image" src="https://github.com/Tencent/cherry-markdown/assets/35719961/8c555565-0514-48c2-b1ed-454994b10ff1">
自定义语法demo少了engine这一层, 导致照着demo写customSyntax 不生效

### Contributing

None

**Comment by sunsonliu** [comment]
我敲。。。竟然还有这种问题。。非常感谢，我们改下改下。。。。心虚，跪谢~

**Comment by sunsonliu** [comment]
已修改，非常感谢提醒~~~

**Comment by huchaolin** [comment]
> 已修改，非常感谢提醒~~~

大佬回复速度这么快的吗， 那再反应个小问题吧， 国际化en_US的 toolbars中size和color点开之后还是中文的，并未翻译

**Comment by sunsonliu** [comment]
补上了补上了，已经提交到dev分支了，感谢反馈哈
