### ISSUE TITLE
[Bug Report]当输入http://时，会无视配置弹出工具框

### ISSUE THREAD

**Issue by huchaolin** [Tencent/cherry-markdown#779]
### Prerequisites

- [X] There isn't an existing issue that reports the same bug to avoid duplicates.
- [X] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

<img width="220" alt="image" src="https://github.com/Tencent/cherry-markdown/assets/35719961/2c932529-9ea3-4d3a-b96a-154bcd553450">
如图， 当在输入框输入http://时， 会弹出工具提示框， 然而config.toolbars.bubble 、 config.toolbars.float 、config.toolbars.toc 尝试设置为false、[]、null, 均无效， 工具提示框仍会弹出，且内容与toolbars.toolbar中的也不一致
版本为0.8.42

### Contributing

None

**Comment by sunsonliu** [comment]
这个配置是  `config.editor.showSuggestList: false; // 是否显示联想框`  可以把这个改成false再试试哈

**Comment by huchaolin** [comment]
感谢~~~~
