### ISSUE TITLE
[Bug report] 使用vite开发时报错，引入jsdom导致，可以动态引入

### ISSUE THREAD

**Issue by gongliangshuai** [Tencent/cherry-markdown#78]
![企业微信截图_ce2d6dd1-23c9-4eb0-a917-02d6aac01e27](https://user-images.githubusercontent.com/8306113/147625222-cbdb2aba-9507-4e89-a605-3cfe25238403.png)
![wecom-temp-a198d9dc71776a35f5b4ad28b386ecfe](https://user-images.githubusercontent.com/8306113/147625237-3b3e9a87-8e9c-42b9-86a7-ccce8db3ce39.png)

**Comment by lyngai** [comment]
已知的 BUG，在下一个版本我们会将 browser 和 node 版本的包分开打包。目前浏览器环境可以先按下方配置规避该问题。

```ts
// vite.config.ts
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import path from 'path';

export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      // jsdom 解析到空文件
      jsdom: path.resolve(__dirname, 'src', 'empty.js'),
    },
  },
});
```
empty.js 参考如下
```js
// src/empty.js
export const JSDOM = {};
```

**Comment by lyngai** [comment]
issue 先关闭了，新版本（v0.6.1）实测已修复该问题。
