### ISSUE TITLE
[Bug Report] Detail的国际化问题

### ISSUE THREAD

**Issue by jiakuan** [Tencent/cherry-markdown#782]
### Prerequisites

- [ ] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

1. Cherry Markdown 的 locale 设置成：

```
 "locale": "en_US",
```

2. 选择 Detail 插入
<img width="306" alt="Screenshot 2024-06-14 at 12 41 04" src="https://github.com/Tencent/cherry-markdown/assets/533236/49890043-d1b7-474e-bc67-358c0b1409f9">

3. Detail的默认值显示了中文，正确的方式是显示英文
<img width="937" alt="Screenshot 2024-06-14 at 12 41 18" src="https://github.com/Tencent/cherry-markdown/assets/533236/838a396d-a9fe-4fb2-bb27-3736f75acea2">

### Contributing

None

**Comment by sunsonliu** [comment]
感谢反馈，已补上提交到dev分支了
