### ISSUE TITLE
[Bug Report]setMarkdown/setValue方法导致长文本被截断

### ISSUE THREAD

**Issue by foxfire881** [Tencent/cherry-markdown#788]
### Prerequisites

- [ ] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

调用setMarkdown/setValue方法填写编辑器时，会导致长文本被截断。

场景举例：
1、发布一篇文章，内容来自[官方demo](https://tencent.github.io/cherry-markdown/examples/index.html)的markdown文本，原封不动复制粘贴进去，正常发布到服务端；
2、编辑修改这边文章，从服务端取回文本内容，通过setMarkdown/setValue方法填进编辑器，内容会被截断，见截图（如果文本内容短一点则没问题，不会被截断。暂不确定是因为有特殊符号原因导致截断还是文本超长被截断）

![cddd](https://github.com/Tencent/cherry-markdown/assets/273961/06ca7b9b-e745-444e-a1b0-57eb578fe2f8)

### System Information

```Shell
版本号：最新的0.8.42
```

### Contributing

None

**Comment by foxfire881** [comment]
补充，原封不动二次发布后，通过console打印二次发布到服务器的文本，确认内容被截断了，而不是隐藏起来没显示出来。

**Comment by foxfire881** [comment]
又发现好几个问题，感觉setValue问题很多啊，完全不可用的状态，今天折腾了一天快炸了：

1、同上，服务端拉取markdown文本到本地，通过setValue/setMarkdown填进编辑器时，如果文本比较多，编辑区最上面会空出来一大片，滚动条滚的位置也乱七八糟，看了之前的issue给了一个keepDocumentScrollAfterInit的参数设置了也没用

2、如果文本比较少（例如只有一个单词），拉取到本地填进编辑器后，倒是可以正常显示，但是不能正常编辑，把光标移动到单词末尾，按backspace回退键时，光标退了一格，但是并没有把最后一个字符删掉，多按几次删到头，最后总会有一个字符删不掉，相当于光标已经顶格移动不了了，左也移动不了，右也移动不了，但是编辑器还是会保留一个字符删不了，调用setValue('')也不行，那个恶心的字符还是删不了。

3、还有好多关于setValue/setMarkdown莫名其妙的问题，已经无力吐槽了……

**Comment by foxfire881** [comment]
如果编辑器是全新初始化没填过任何内容的，那么在编辑区编辑markdown文本一切正常；

但是只要是拉取了外部文本通过setValue/setMarkdown填进编辑区之后，编辑区就开始乱七八糟各种问题一堆，完全没法正常使用。

**Comment by sunsonliu** [comment]
https://tencent.github.io/cherry-markdown/examples/index.html
请问在这里可以重现不？我尝试在上面demo里进行setValue一个长文本的操作，并没有重现，怀疑是我重现步骤有缺失。。

**Comment by RSS1102** [comment]
https://github.com/Tencent/cherry-markdown/assets/81673017/bce136e3-a87f-469d-8c1a-eada6e87c99d

**Comment by foxfire881** [comment]
我是把cherry封装进一个Vue的组件，然后挂到主页面下加载的，是不是和这个使用方式有关系呢？目前观察到的现象很奇怪，只有第一次初始化时是正常的，只要不调用setValue/setMarkdown也是正常的，但是只要一调用setValue/setMarkdown往编辑器里面填东西进去之后，编辑器就出现各种莫名其妙异常

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/issues/381#issuecomment-1455484863
会不会是这个原因。。

**Comment by foxfire881** [comment]
> [#381 (comment)](https://github.com/Tencent/cherry-markdown/issues/381#issuecomment-1455484863) 会不会是这个原因。。

我擦！果然是这个问题！！我之前的代码是这样的：
```javascript
this.contentEditor = new Cherry(this.cherry_config)  //contentEditor是我Vue组件的一个成员变量
this.contentEditor.setValue('xxxxxx...') //异常，各种莫名其妙问题无力吐槽
``

换成下面这样就一切正常了
```javascript
const cherryInstance = new Cherry(this.cherry_config)
cherryInstance.setValue('xxx...')

//或者下面这样也可以
new Cherry(this.cherry_config).setValue('xxx...')
```

这个问题还真是第一次遇见啊~~ 之前用Vditor的时候是可以把new出来的实例赋给Vue组件的一个变量的，代码和上面第一段一样是可以正常工作的，换了Cherry就爆了。感谢~~

**Comment by sunsonliu** [comment]
不客气哈。。。看来这是一个普遍的问题，我们也比较困惑为什么代理时会出错，关于这个问题我们也尝试支持下

**Comment by foxfire881** [comment]
> 不客气哈。。。看来这是一个普遍的问题，我们也比较困惑为什么代理时会出错，关于这个问题我们也尝试支持下

是的，这个问题很隐蔽。一般情况要么就是能正常工作，要么就是不能正常工作抛个错误出来。cherry这种是一半正常，一半不正常，也没有抛错误出来，很难做but shooting定位原因。建议更新下文档给后来的新手一个避坑指引。

**Comment by sunsonliu** [comment]
嗯嗯，最好是能解决这个问题，让开发者想怎么用就怎么用。。。我们尝试解决下这个问题哈

**Comment by sunsonliu** [comment]
比较悲剧，这是我们用的codemirror组件的[问题](https://github.com/codemirror/codemirror5/issues/6886#issuecomment-2094015217)，我们后面更新下文档哈

**Comment by foxfire881** [comment]
> 比较悲剧，这是我们用的codemirror组件的[问题](https://github.com/codemirror/codemirror5/issues/6886#issuecomment-2094015217)，我们后面更新下文档哈

杯具了~ 看来依赖外部的代码还是不太可控呀，不过好在还是定位到问题点有变通解决方案了。
