### ISSUE TITLE
[Bug report] Copy the pasted code will add extra tags

### ISSUE THREAD

**Issue by Young6118** [Tencent/cherry-markdown#79]
**Describe the bug**
Brought extra strange style when i pasted pieces of code, this feature is completely unable to use.
**To Reproduce**
1. Copy code from xcode
![image](https://user-images.githubusercontent.com/16507306/147719379-12c25809-e022-4af1-9c11-5420ea6ffdd8.png)

2. Paste into the editor
![image](https://user-images.githubusercontent.com/16507306/147719409-0ff7d211-54af-4fcc-98c2-61bf5c39dfe7.png)

3. See error

**Expected behavior**
It will add the '**' tag what I don't need in my statement.

**Screenshots**
![image](https://user-images.githubusercontent.com/16507306/147719509-e2139379-7f7a-470f-9858-f9c23d69faf0.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 15.2

**Additional context**
Excess markers will appear from copying from Xcode.

**Comment by jiawei686** [comment]
Hi, thanks for your report!
Clipboard will get rich text when you copy from xcode. There is a feature to convert clipboard html to markdown while pasting for typesetting. In this case, some keywords would be converted to Emphasize format. You could click the text button right after paste action to disable it and use plain text instead.
![image](https://user-images.githubusercontent.com/12953093/147730982-e009a127-784a-46ac-8a06-b4fda1ff1c8a.png)

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/blob/main/docs/features.md#feature-1copy-html-paste-into-md-syntax

Maybe cherry can remember your last choice ...
