### ISSUE TITLE
[Others] TOC和锚点的问题

### ISSUE THREAD

**Issue by foxfire881** [Tencent/cherry-markdown#790]
1、如果editor的div不是挂在body下，在preview浏览模式时 TOC 位置是固定的，不能悬浮在右侧中间位置，当滚动条下拉时会把TOC滚上去不可见。（如图）

2、Vue如果使用的是hash模式路由，URL后面已经有一个 \# 了（例如：`http://localhost:3000/#/article/1`），在preview模式下生成的所有锚点链接都失效（例如锚点url变成 `http://localhost:3000/锚点#`），这种情况有啥好的解决方案吗？

![1](https://github.com/Tencent/cherry-markdown/assets/273961/0f99654f-18e7-463a-a34b-694689e39ff1)

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/cd86f4b4-1a07-488b-9f46-54d4c3fdced1)

第二个问题，可以尝试给这个配置哈

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/03890f36-49ff-4ec4-9668-25448f0e3301)

第一个问题可能是设计如此。。如果预览区高度是自增的，确实会出现上述问题。。可以通过 `position: fixed;` 临时解决该问题哈

**Comment by foxfire881** [comment]
> ![image](https://private-user-images.githubusercontent.com/998441/340241068-cd86f4b4-1a07-488b-9f46-54d4c3fdced1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTQ2NTgsIm5iZiI6MTcxODYxNDM1OCwicGF0aCI6Ii85OTg0NDEvMzQwMjQxMDY4LWNkODZmNGI0LTFhMDctNDg4Yi05ZjQ2LTU0ZDRjM2ZkY2VkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QwODUyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGQ4YWZlMjc1YjE5ZTcwYTI4NmRlMWU0MDg5YjU3MDA5ODY3MWExMmFiMmU4MDk2OWU1M2Q1YzU2YmM5NDliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f64RDWTG92DfLSCqNtxigcc56WYkLKHeKCY2ezJg5uM)
> 
> 第二个问题，可以尝试给这个配置哈

updateLocationHash: true  -- 锚点链接点击之后页面变成空的；
updateLocationHash: false -- 锚点链接点击之后页面没有变空，但也保持静止不动，没有滚到锚点的位置，也是失效状态。

网上查资料[关于Vue hash模式锚点问题](https://blog.csdn.net/weixin_42079403/article/details/136687046)，是在锚点位置设置路由，但那是针对已知的固定锚点才能那么搞，像cherry这种动态生成锚点的不太适用。

**Comment by foxfire881** [comment]
是不是因为我的editor不是挂在body下面，所以才导致跟TOC一样，点击锚点没用？

Vue一般都是组件式开发，所有组件都是挂在div下面的，很少有直接挂在body下面的情况。建议cherry调整一下相关设计。

**Comment by sunsonliu** [comment]
哦。。我大概懂了。。因为你没有设置高度，所以cherry的高度是自增的，滚动条是外部页面的滚动条，导致cherry的滚动逻辑失效（估计左右两边的同步滚动逻辑也是失效的）
可以尝试给cherry一个固定高度试试，然后`updateLocationHash: false`

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/25bfefb3-2c1e-48b3-aabb-709aa9438139)
可以参考[在线demo](https://tencent.github.io/cherry-markdown/examples/index.html)哈

**Comment by foxfire881** [comment]
> 哦。。我大概懂了。。因为你没有设置高度，所以cherry的高度是自增的，滚动条是外部页面的滚动条，导致cherry的滚动逻辑失效（估计左右两边的同步滚动逻辑也是失效的） 可以尝试给cherry一个固定高度试试，然后`updateLocationHash: false`

哈哈，设置了800px高度之后可以正常滚动到锚点了，TOC也固定不会动了，不过编辑器变成一个窗口了，在div窗口里面能滚动（像iframe那样），外面body没有滚动条了，看上去有点怪怪的，不是一整页能滚动那种，哈哈~

高度如果设置成100%，倒是一整页能滚动了，但是TOC和锚点又不正常了。

能不能鱼和熊掌兼得呀？

**Comment by foxfire881** [comment]
一般涉及到文章编辑发布的系统开发，都还会有标题头header、左边栏sidebar、主区域main等区域，editor一般是挂在main区域的div里面，很少有直接挂在body下面的情况。

所以editor如果是挂在某个div下面，TOC和锚点有木有好点的解决方案呢

**Comment by sunsonliu** [comment]
https://tencent.github.io/cherry-markdown/examples/index.html
这个就是高度设置成100%的效果哈


如果是放在div里，div只要是有高度的，就没有太大的问题哈，见[这个demo](https://tencent.github.io/cherry-markdown/examples/multiple.html)：

https://github.com/Tencent/cherry-markdown/assets/998441/697f6068-fa48-4778-a4e1-0c583df6419d

**Comment by foxfire881** [comment]
> https://tencent.github.io/cherry-markdown/examples/index.html 这个就是高度设置成100%的效果哈
> 
> 如果是放在div里，div只要是有高度的，就没有太大的问题哈，见[这个demo](https://tencent.github.io/cherry-markdown/examples/multiple.html)：


可能是我没表达清楚：
上面两个demo演示的都是页面中只有编辑器的情况，而且左右两边编辑、预览区都开了。

而我是想实现类似CSDN博客、博客园那种文章发布系统，文章发布后，在前台浏览时已经没有editor的编辑框了，左右两边编辑/预览同步区也没有了，整个文章页面是一个整体，滚动条也只有最外层body滚动条，可以从最上面拉到最下面，从头拉到尾，没有编辑器内部的滚动条了。

但是cherry-editor在前台页面浏览模式时，似乎还是一个编辑器的模式，只是通过preview等参数设置把上面的工具栏、左边的编辑区给隐藏了，只保留了右侧预览区设置成预览模式，但它本质上还是一个div，还是一个编辑器。如果把这个div设置成固定高度那么就会有内部的滚动条产生，导致文章部分看上去像是iframe嵌入页面的，很丑陋；而如果把编辑器的div高度设置成100%，高度自增，div内部的滚动条是没了，整个页面也可以实现了上述类似CSDN博客那种只有最外面一层滚动条、可以从头拉到尾的效果了，但此时浮动TOC、锚点又失效了。

所以有没有一种既能实现CSDN博客那种100%高度自增模式，又能保持TOC和锚点有效的解决方案呢？

**Comment by sunsonliu** [comment]
哦哦，明白了，这种情况下确实是组件无法支持的。目前这种情况有两种解法：
1、推荐的做法还是利用hash（`updateLocationHash: true`）通过浏览器的默认行为来实现（比较常见的播客系统都是支持的，比如github的[wiki](https://github.com/Tencent/cherry-markdown/wiki/%E5%88%9D%E8%AF%86cherry-markdown-%E7%BC%96%E8%BE%91%E5%99%A8#%E7%AE%80%E4%BB%8B)），不过这就需要我们**修改路由策略**了。
2、自行实现一套不更新hash的滚动机制（比如CSDN播客），缺点是有一定的开发工作量

**Comment by foxfire881** [comment]
> 哦哦，明白了，这种情况下确实是组件无法支持的。目前这种情况有两种解法： 1、推荐的做法还是利用hash（`updateLocationHash: true`）通过浏览器的默认行为来实现（比较常见的播客系统都是支持的，比如github的[wiki](https://github.com/Tencent/cherry-markdown/wiki/%E5%88%9D%E8%AF%86cherry-markdown-%E7%BC%96%E8%BE%91%E5%99%A8#%E7%AE%80%E4%BB%8B)），不过这就需要我们**修改路由策略**了。 2、自行实现一套不更新hash的滚动机制（比如CSDN播客），缺点是有一定的开发工作量
> 
> 然后，我们也想想在组件层面能不能支持下这种情况哈



感觉应该可以的，我之前用vditor时修改过vditor的源码，大体上就是在页面初始化加载editor后，重新扫描整个页面的header元素，然后动态生成一个TOC，绑定在指定的div元素下面，然后监听scroll事件滚动到指定锚点。cherry只要对外暴露一个配置参数，设置把TOC绑定在外层哪个div下，就能实现这个功能了。

相关代码如下，看看能否集成进去

```javascript
const initOutline = () => {
      const headingElements = []
      Array.from(document.getElementById('content').children).forEach(item => {
        if (item.tagName.length === 2 && item.tagName !== 'HR' && item.tagName.indexOf('H') === 0) {
          headingElements.push(item)
        }
      })

      let toc = []
      let el = document.querySelector('.el-main')    //把TOC挂到上层 .el-main 的div下，TOC根据.el-main的高度和滚动条位置浮动在固定区域，然后滚动到锚点指定区域。
      el.addEventListener('scroll', () => {
        const scrollTop = el.scrollTop
        toc = []
        headingElements.forEach(item => {
          toc.push({
            id: item.id,
            offsetTop: item.offsetTop
          })
        })
        const currentElement = document.querySelector('.vditor-outline__item--current')
        for (let i = 0, iMax = toc.length; i < iMax; i++) {
          if (scrollTop < toc[i].offsetTop - 30) {
            if (currentElement) {
              currentElement.classList.remove('vditor-outline__item--current')
            }
            let index = i > 0 ? i - 1 : 0
            document.querySelector('span[data-target-id="' + toc[index].id + '"]').classList.add('vditor-outline__item--current')
            break
          }
        }
      })
    }
```

**Comment by sunsonliu** [comment]
已实现并提交到dev分支了，可参考demo：[`/examples/preview_only.html`](https://github.com/Tencent/cherry-markdown/blob/dev/examples/preview_only.html) 和 [`/examples/scripts/preview-demo.js`](https://github.com/Tencent/cherry-markdown/blob/dev/examples/scripts/preview-demo.js)

主要在`toolbars.toc`里增加了两个配置，见下图：
![image](https://github.com/Tencent/cherry-markdown/assets/998441/7ab3d16b-5b28-409f-a9ed-8807bec7aee3)

当滚动条在浏览器上而非cherry编辑器时，cherry会自动调节

**Comment by foxfire881** [comment]
> 已实现并提交到dev分支了，可参考demo：[`/examples/preview_only.html`](https://github.com/Tencent/cherry-markdown/blob/dev/examples/preview_only.html) 和 [`/examples/scripts/preview-demo.js`](https://github.com/Tencent/cherry-markdown/blob/dev/examples/scripts/preview-demo.js)

卓越！
