### ISSUE TITLE
npm 包 404 了

### ISSUE THREAD

**Issue by CaptainJack-Git** [Tencent/cherry-markdown#8]
error Couldn't find package "cherry-markdown" on the "npm" registry.

**Comment by humyfred** [comment]
你好，可能是镜像不可用，建议修改成国内哈，npm config set registry https://registry.cnpmjs.org/ 。如果已经是此地址，看看是否存在`.yarnrc` 或者 `.npmrc` 文件设置了不同的镜像

**Comment by lyngai** [comment]
issue 先关闭了，如再遇到类似问题欢迎再反馈。
