### ISSUE TITLE
[Feature request] Toolbar appears when some of code block is selected

### ISSUE THREAD

**Issue by Young6118** [Tencent/cherry-markdown#80]
**Toolbar appears when some of code block is selected**
![image](https://user-images.githubusercontent.com/16507306/147719961-ce539ef4-1c32-49e9-8ef4-f7c9b71c5277.png)

**Toolbar does not have to appear when some of code block is selected**
Even if I select some of the contents in the code block, the toolbar doesn't need to appear.

**Additional context**
![image](https://user-images.githubusercontent.com/16507306/147720038-524e1e17-3873-4b04-8458-f827d2a83d12.png)
Just like github's editor

**Comment by sunsonliu** [comment]
![image](https://user-images.githubusercontent.com/998441/149161543-3840dbe7-501b-4a57-9a7f-4c4d97d11516.png)
set `toolbars.bubble=false` can disable bubble toolbar
