### ISSUE TITLE
【所见即所得】- 表格增加删除列操作

### ISSUE THREAD

**Issue by sunsonliu** [Tencent/cherry-markdown#803]
希望达到效果：
鼠标hover到表格某一列时，在列的上方和下方**出现**“删除按钮”
当鼠标hover到删除按钮时，将将要被删除的列的边框**标红**
效果如下：
![image](https://github.com/Tencent/cherry-markdown/assets/998441/0aefffc3-0b8a-4083-a05d-f4cebc361c19)

**本issue为2024犀牛鸟开源人才培养活动专属issue，仅供在校大学生参与领取**
【认领issue】在[研学基地](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D)"issue营地"对应issue行的M~R列**抢滩报名**，即视为**认领成功**。
【完成issue】已认领issue的同学，请同步在本issue评论区回复“已成功领取本issue”； 如7天内无提交任何进展包括不限于comment \ commit \ Pull Request，则将视为同学主动放弃issue，组委会将释放issue给下一位等候者。

相关代码在[这里](https://github.com/Tencent/cherry-markdown/blob/main/src/utils/tableContentHandler.js)
开发文档在[这里](https://github.com/Tencent/cherry-markdown/wiki/%E5%88%9D%E8%AF%86cherry-markdown-%E7%BC%96%E8%BE%91%E5%99%A8)

开发方式：
1. fork项目到自己的项目里
2. 从自己项目里的**dev**分支拉个新分支开发
3. 完成开发后pr到cherry markdown项目的**dev**分支 （提交时不需要提交`/dist/`目录下的变更）

**Comment by Old-Second** [comment]
已成功领取本issue

**Comment by Runtus** [comment]
已成功领取本issue

**Comment by Shirley0803** [comment]
已成功领取本issue

**Comment by sunsonliu** [comment]
v0.8.50 版本上已支持
