### ISSUE TITLE
Nuxt2.js下无法使用

### ISSUE THREAD

**Issue by My52Hz** [Tencent/cherry-markdown#811]
### Prerequisites

- [X] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

版本: nuxtjs:2.0
         node:16.17.0
         
         引入后构建失败,提示:
   
ERROR in ./node_modules/cherry-markdown/dist/cherry-markdown.esm.js 1:1635306
Module parse failed: Unexpected token (1:1635306)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
(Source code omitted for this binary file)
 @ ./pages/article/test.vue?vue&type=script&lang=js (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/article/test.vue?vue&type=script&lang=js) 3:0-70 17:25-39
 @ ./pages/article/test.vue?vue&type=script&lang=js
 @ ./pages/article/test.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

我已经在客户端使用了:
<template>
    <div>
        <client-only>
            <div ref="markdownContainer"></div>
        </client-only>
    </div>
</template>

请问一下是因为这个编辑器本身不支持nuxtjs吗还是因为版本问题

**Comment by sunsonliu** [comment]
请问使用的cherry是哪个版本呢，目前已知v0.8.43版本是有[问题](https://github.com/Tencent/cherry-markdown/issues/808)的，可以尝试使用v0.8.44版本哈，如果还有问题可以再尝试使用v0.8.42版本试试。。如果42版正常，44版有问题，也麻烦同步下哈，我们再看看怎么优化

**Comment by My52Hz** [comment]
感谢回复,我安装的是最新版本的;直接&nbsp;npm&nbsp;install&nbsp;cherry-markdown&nbsp; 这样子
&nbsp;


吴兴政
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月27日(星期四) 下午2:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/cherry-markdown] Nuxt.js下无法使用 (Issue #811)














 
请问使用的cherry是哪个版本呢，目前已知v0.8.43版本是有问题的，可以尝试使用v0.8.44版本哈，如果还有问题可以再尝试使用v0.8.42版本试试。。如果42版正常，44版有问题，也麻烦同步下哈，我们再看看怎么优化

**Comment by sunsonliu** [comment]
哦哦。。那可以试试安装v0.8.42 这个版本不，如果这个版本没有报错那我们就基本能定位是哪里有问题了。。

**Comment by My52Hz** [comment]
0.8.44提示这个;非我程序的问题;这个问题貌似也处理不了,搞了很久







吴兴政
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/cherry-markdown"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月27日(星期四) 下午2:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/cherry-markdown] Nuxt.js下无法使用 (Issue #811)





 
请问使用的cherry是哪个版本呢，目前已知v0.8.43版本是有问题的，可以尝试使用v0.8.44版本哈，如果还有问题可以再尝试使用v0.8.42版本试试。。如果42版正常，44版有问题，也麻烦同步下哈，我们再看看怎么优化

**Comment by RSS1102** [comment]
能提供一下最小复现的代码仓库嘛？谢谢。

**Comment by My52Hz** [comment]
最新版本、0.8.42、0.8.44的都有问题；我的nuxtjs package如下：
"dependencies": {
    ***@***.***/kit": "^3.11.2",
    ***@***.***/axios": "^5.13.6",
    "cherry-markdown": "^0.8.44",
    "cookie-universal-nuxt": "^2.1.4",
    "element-ui": "^2.15.1",
    "highlight.js": "^11.9.0",
    "less-loader": "^5.0.0",
    "mavon-editor": "^2.10.4",
    "node-sass": "^6.0.1",
    "nuxt": "^2.0.0",
    "nuxt-socket-io": "^3.0.13",
    "sass-loader": "^10.0.1",
    "vue-clipboard2": "^0.3.3",
    "vue-socket.io": "^3.0.10"
},
"devDependencies": {
    ***@***.***/types": "~2.17.0",
    "cross-env": "^7.0.3",
    "increase-memory-limit": "^1.0.7"
}
&nbsp;


吴兴政
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "阿菜 ***@***.***&gt;; 
发送时间: 2024年6月27日(星期四) 下午2:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/cherry-markdown] Nuxt.js下无法使用 (Issue #811)














 
能提供一下最小复现的代码仓库嘛？谢谢。

**Comment by sunsonliu** [comment]
@RSS1102 菜总说他晚上瞅瞅哈

**Comment by My52Hz** [comment]
> @RSS1102 菜总说他晚上瞅瞅哈

谢谢你,谢谢菜总,我也在捣鼓一下看能否解决

**Comment by RSS1102** [comment]
@My52Hz 可以升级到nuxt3嘛？babel处理起来问题有点多，实在不想兼容了，而且Nuxt 2 将于 2024 年 6 月 30 日终止使用寿命 (EOL)（[见](https://nuxt.com/blog/nuxt2-eol)）

**Comment by My52Hz** [comment]
> @My52Hz 可以升级到nuxt3嘛？babel处理起来问题有点多，实在不想兼容了，而且Nuxt 2 将于 2024 年 6 月 30 日终止使用寿命 (EOL)（[见](https://nuxt.com/blog/nuxt2-eol)）

OK,我开始着手升级,反正都是自己的网站,搞崩了大不了回退,感谢

**Comment by RSS1102** [comment]
嗯呢，如果在nuxt3的时候遇到问题再沟通。
