### ISSUE TITLE
[Others] 请问如何引入plantuml、echarts插件？

### ISSUE THREAD

**Issue by foxfire881** [Tencent/cherry-markdown#812]
起因是参考[全功能版Cherry](https://tencent.github.io/cherry-markdown/examples/index.html)实现插入折线图、柱状图时，发现插入到编辑区里只有示例数据表格，没有示例里的折线图、柱状图，猜测是没有引入ECharts？

于是参考mermaid的引入方式，在`cherry-markdown/dist/addons/`目录下还找到了`cherry-code-block-plantuml-plugin.js`、`cherry-table-echarts-plugin.js`这两个插件。

```javascript
import CherryMermaidPlugin from 'cherry-markdown/dist/addons/cherry-code-block-mermaid-plugin';
import mermaid from 'mermaid';
  Cherry.usePlugin(CherryMermaidPlugin, {
    mermaid,
  });
```

但是npm install plantuml后，照葫芦画瓢引入plantuml和echarts时会报错
```javascript
import CherryPlantumlPlugin from 'cherry-markdown/dist/addons/cherry-code-block-plantuml-plugin';
import plantuml from 'plantuml';
  Cherry.usePlugin(CherryPlantumlPlugin , {
    plantuml ,
  });
```

报错：
```shell
main.js:66 
 
ReferenceError: process is not defined
    at node_modules/pump/index.js (index.js:6:29)
    at __require2 (chunk-PR4QN5HX.js?v=d677b78f:14:50)
    at node_modules/get-stream/index.js (index.js:3:14)
    at __require2 (chunk-PR4QN5HX.js?v=d677b78f:14:50)
    at node_modules/plantuml/lib/plantuml.js (plantuml.js:2:19)
    at __require2 (chunk-PR4QN5HX.js?v=d677b78f:14:50)
    at plantuml.js:33:18
```

请问要如何引入plantuml、echarts？如何插入折线图、柱状图时可以把图形也插入编辑器？

**Comment by foxfire881** [comment]
另外调试时在console里还看到一些warning，看看是否一起处理了，有强迫症的人看着好难受.


初始化编辑器时：
```shell
TypeError: s2 is not a constructor
    at new n2 (cherry-markdown.core.js:1:610477)
    at e2.value (cherry-markdown.core.js:1:373547)
    at cherry-markdown.core.js:1:372807
    at Array.forEach (<anonymous>)
    at e2.value (cherry-markdown.core.js:1:372780)
    at new e2 (cherry-markdown.core.js:1:372624)
    at new e2 (cherry-markdown.core.js:1:734939)
    at new n2 (cherry-markdown.core.js:1:1285314)
    ......
```


配置toolbar参数时：
```shell
Editor.vue:558 
 this subMenu config type will be deprecated, please use {subMenu: ['strikethrough']} config: [object Object]
Editor.vue:558 
 this subMenu config type will be deprecated, please use {subMenu: ['insert']} config: [object Object]
Editor.vue:558 
 this subMenu config type will be deprecated, please use {subMenu: ['customMenuBName']} config: [object Object]
```

**Comment by sunsonliu** [comment]
echart的话，可以用这种方式引入：https://github.com/Tencent/cherry-markdown/blob/main/examples/index.html#L44
echart的配置见这里：https://github.com/Tencent/cherry-markdown/blob/main/examples/scripts/index-demo.js#L99

然后plantuml 是默认支持的，不需要额外配置的。。

**Comment by foxfire881** [comment]
> echart的话，可以用这种方式引入：https://github.com/Tencent/cherry-markdown/blob/main/examples/index.html#L44 echart的配置见这里：https://github.com/Tencent/cherry-markdown/blob/main/examples/scripts/index-demo.js#L99
> 
> 然后plantuml 是默认支持的，不需要额外配置的。。

Vue组件里不能用script src这种方式引用 js 文件呢，所以才产生这个问题。如果要用 script src 引用的话得把它放在index.html里面，这样每次不管访问什么页面都要加载这个js，有点得不偿失了。

所以Vue组件里应该怎么导入ECharts呢？文档只写了怎么在Vue中引入Cherry以及Mermaid，但是对于ECharts怎么在Vue的Cherry环境中引入没有提及。

**Comment by foxfire881** [comment]
另外，Quick Start里已经yarn install echarts了，为啥还要用scrpit src去重复引用外部CDN的库？不能用 import 的方式直接用已安装的echarts库吗？
![捕获](https://github.com/Tencent/cherry-markdown/assets/273961/3f564e0d-4375-4a3f-bcd0-8ddb4eedff77)

**Comment by foxfire881** [comment]
试了在index.html里面引入echarts，代码原封不动从examples里面拷贝出来的，还是渲染不出来图，只有数据表，console也没有报错。哪里出问题了呢？难道又是因为Vue的问题？

``html
 <body>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts@4.6.0/dist/echarts.js"></script>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
```

```javascript
externals: {
          // externals
          echarts: window.echarts,
          katex: window.katex,
          MathJax: window.MathJax,
        }

 table: {
              enableChart: true,
              //chartRenderEngine: EChartsTableEngine,
              //externals: ['echarts'],
            }
```



![捕获](https://github.com/Tencent/cherry-markdown/assets/273961/0ddadeb3-2f3c-4490-8fdd-691d9aee2f6a)

**Comment by sunsonliu** [comment]
![image](https://github.com/Tencent/cherry-markdown/assets/998441/f6cf0d24-1479-4091-8cf4-a6b546adf0c0)

试试这样哈，我们也更新下wiki

**Comment by sunsonliu** [comment]
> 试了还是不行，还是只有表格没有图形，不知道是哪里出了问题，代码和config是从examples原封不动拷过来的，只是封装在Vue组件里，不知道是不是又和上次一样的ref问题

试试这样：
```
import Cherry from 'cherry';
import echarts from 'echarts';
import EChartsTableEngine from 'cherry/dist/addons/advance/cherry-table-echarts-plugin';

Cherry.usePlugin(EChartsTableEngine);
new Cherry({
  externals: { echarts },
});
```

或者这样：
```
import Cherry from 'cherry';
import echarts from 'echarts';
import EChartsTableEngine from 'cherry/dist/addons/advance/cherry-table-echarts-plugin';

Cherry.usePlugin(EChartsTableEngine, { echarts });
new Cherry();
```

看行不行哈

**Comment by foxfire881** [comment]
> > 试了还是不行，还是只有表格没有图形，不知道是哪里出了问题，代码和config是从examples原封不动拷过来的，只是封装在Vue组件里，不知道是不是又和上次一样的ref问题
> 
> 试试这样：
> 
> ```
> import Cherry from 'cherry';
> import echarts from 'echarts';
> import EChartsTableEngine from 'cherry/dist/addons/advance/cherry-table-echarts-plugin';
> 
> Cherry.usePlugin(EChartsTableEngine);
> new Cherry({
>   externals: { echarts },
> });
> ```
> 
> 或者这样：
> 
> ```
> import Cherry from 'cherry';
> import echarts from 'echarts';
> import EChartsTableEngine from 'cherry/dist/addons/advance/cherry-table-echarts-plugin';
> 
> Cherry.usePlugin(EChartsTableEngine, { echarts });
> new Cherry();
> ```
> 
> 看行不行哈


终于有了。想起来了，Cherry.usePlugin这种引入方式，之前测试 plantuml 时因为照着mermaid的葫芦画瓢引入plantuml 不成功，所以后面的 Echarts 没有继续按这种方法引用测试了。折腾到最后又回到最初的路上
![捕获](https://github.com/Tencent/cherry-markdown/assets/273961/41c5faf4-4256-49a2-9210-3a5e7643a4ef)
