### ISSUE TITLE
[Bug report]打字被输入法遮挡问题

### ISSUE THREAD

**Issue by heyanfeng** [Tencent/cherry-markdown#82]
基本信息

发现版本: [0.4.13]

是否稳定复现: [是]

运行环境及版本: [Chrome 96.0.4664.110（正式版本） (x86_64)]

详细描述
用户在使用过程中发现输入法对文字有遮挡
![企业微信截图_16412652781590](https://user-images.githubusercontent.com/15811017/148022533-3cb92fee-bb92-4a1f-8fb2-4314ef411aef.png)

在cherry官网试了下也存在同样的问题
![wecom-temp-94a22c2dfe2d0d590261913f45129bcc](https://user-images.githubusercontent.com/15811017/148022473-a6dc5765-362f-49cc-b9ad-2b32fd68483b.png)

WritePreview

**Comment by sunsonliu** [comment]
感谢反馈，我们能够稳定重现这个问题，不过还没有找到解决方案，我们会继续尝试解决这个问题，如果你有思路欢迎反馈给我们~

**Comment by yangrunkang** [comment]
![image](https://user-images.githubusercontent.com/46257933/153832538-cc7977bf-1e73-4261-9b6c-0530f7a6729d.png)
今天网站用户也反馈了这个问题

**Comment by yangrunkang** [comment]
这个Bug什么时候解决....

**Comment by sunsonliu** [comment]
还在修，目前定位是codemirror样式问题，不是特别好修
