### ISSUE TITLE
[Feature Request]增加现有工具栏配置项所对应的API

### ISSUE THREAD

**Issue by mmmaming** [Tencent/cherry-markdown#823]
### Prerequisites

- [X] There isn't an existing issue that requests the same feature, to avoid duplicates.

### Clear and concise description of the problem

目前现有工具栏对应的功能中，只有部分功能提供了对应的api，其他诸如文字颜色，文字大小，对齐方式，引用等没有提供对应的api方式去调用，期望可以把工具栏里的每个功能都提供对应的api方式调用。

### Suggested solution

这样可以支持使用者更好的定制化自己想要的工具栏样式并调用内置API实现对应的功能。

### Contributing

None

**Comment by sunsonliu** [comment]
已提交到dev分支

**Comment by sunsonliu** [comment]
已发布，可以在[这里](https://tencent.github.io/cherry-markdown/examples/api.html)体验
