### ISSUE TITLE
[Bug Report] 代码提示自动补全国际化问题

### ISSUE THREAD

**Issue by jiakuan** [Tencent/cherry-markdown#835]
### Prerequisites

- [X] There isn't an existing issue that reports the same bug to avoid duplicates.
- [X] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

参见下图，当cherry选项设置成英文的时候（`"locale": "en_US"`），代码补全的提示菜单里面仍然显示中文。
<img width="202" alt="Screenshot 2024-07-07 at 21 11 42" src="https://github.com/Tencent/cherry-markdown/assets/533236/00ce4a5b-6266-4c4a-9e11-18becf2d3f30">

### Contributing

None

**Comment by jiakuan** [comment]
英文可以是：

```
Inline Code
Code Block
```

**Comment by Saraph1nes** [comment]
好的 感谢您的建议

> 英文可以是：
> 
> ```
> Inline Code
> Code Block
> ```

好的 感谢您的建议
