### ISSUE TITLE
[Feature Request] 代码块语法中的语言支持更多的别名

### ISSUE THREAD

**Issue by mmmaming** [Tencent/cherry-markdown#838]
### Prerequisites

- [ ] There isn't an existing issue that requests the same feature, to avoid duplicates.

### Clear and concise description of the problem

例如TS语言，如果输入
``` TypeScript
const a:number = 2;
```
，不会有对应的语法高亮效果，
只能输入
``` typescript
const a:number = 2;
```
才有正确的高亮效果。

### Suggested solution

期望把语言的大小写版本都能显示出对应的语法高亮效果。

### Contributing

None

**Comment by sunsonliu** [comment]
已提交到dev分支

**Comment by sunsonliu** [comment]
已发布
