### ISSUE TITLE
[Bug report]多脚注解析错乱

### ISSUE THREAD

**Issue by chuwarriors** [Tencent/cherry-markdown#846]
### Prerequisites

- [x] There isn't an existing issue that reports the same bug to avoid duplicates.
- [x] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug

Bug：多个脚注的场景，previewer展示解析结构错乱
![1721192889014](https://github.com/user-attachments/assets/1dd06f14-3f00-40fd-a5ef-c1d7c9f8b007)

### System Information

```Shell
直接在提供的basic demo上粘贴百度提供的多脚注示例内容：

这里是文本内容。[^1]
[^1]: 这是第一个脚注的内容。
这里是更多的文本内容。[^2]
[^2]: 这是第二个脚注的内容。
```

### Contributing

None

**Comment by sunsonliu** [comment]
![image](https://github.com/user-attachments/assets/036b5d41-14f2-4df5-b7c9-89ad10971ec9)
额，应该是脚注内容没有以连续两个换行结束哈，cherry的脚注内容支持换行，所以当脚注内容没有正确结束的时候就会有这样的问题哈~
