### ISSUE TITLE
[Feature Request] 添加“内联代码”按钮或者改进现有的“代码块”工具条按钮

### ISSUE THREAD

**Issue by jiakuan** [Tencent/cherry-markdown#847]
### Prerequisites

- [X] There isn't an existing issue that requests the same feature, to avoid duplicates.

### Clear and concise description of the problem

目前的“代码块”工具条按钮只支持多行的代码块，例如在一句话中，如果我只选择一个词，点击“代码块”工具条按钮，这个被选择的词被转换成一个代码块，但是用户可能只想将选定的词格式成内联代码 (Inline Code)

### Suggested solution

有两种方案支持 Inline Code：一种是添加一个新的工具条按钮用来切换内联代码；另一种方式的改进现有的代码块按钮，根据当前选择判断是内联代码还是代码块。

我感觉第二种方案更好。当没有选择文本的时候，将光标所在行转换成代码块；如果有选择的时候，则看选择的文字是否跨多行，只在一行之内的时候，则按照内联代码处理。

### Contributing

None

**Comment by Saraph1nes** [comment]
> ### Prerequisites
> * [x]  There isn't an existing issue that requests the same feature, to avoid duplicates.
> 
> ### Clear and concise description of the problem
> 目前的“代码块”工具条按钮只支持多行的代码块，例如在一句话中，如果我只选择一个词，点击“代码块”工具条按钮，这个被选择的词被转换成一个代码块，但是用户可能只想将选定的词格式成内联代码 (Inline Code)
> 
> ### Suggested solution
> 有两种方案支持 Inline Code：一种是添加一个新的工具条按钮用来切换内联代码；另一种方式的改进现有的代码块按钮，根据当前选择判断是内联代码还是代码块。
> 
> 我感觉第二种方案更好。当没有选择文本的时候，将光标所在行转换成代码块；如果有选择的时候，则看选择的文字是否跨多行，只在一行之内的时候，则按照内联代码处理。
> 
> ### Further Information
> _No response_
> 
> ### Contributing
> None

我更倾向于第一种，这样可以对插入行内代码这一操作增加单独的快捷键（ctrl + `），和现在的插入代码块（ctrl + k）区分开

具体逻辑如下：
1、未选中内容时，新增空的``
<img width="290" alt="image" src="https://github.com/user-attachments/assets/e0324a0c-fd56-4adb-afda-400eff64f842">

2、选中单行内容时，在选中内容两边增加``
<img width="374" alt="image" src="https://github.com/user-attachments/assets/1979f368-dd77-4d0f-8215-f531a9a73a65">

3、选中多行内容时，每一行选中的内容两边增加``
<img width="508" alt="image" src="https://github.com/user-attachments/assets/7013540a-602c-4a4e-b52a-6b111f5542d6">

**Comment by jiakuan** [comment]
第一种方案在区分两种格式方面更好，更清晰。但是关于：

> 选中多行内容时，每一行选中的内容两边增加``

好像并不常用，多行用单引号可读性并不好，我不倾向于鼓励这样的操作

另外，在工具条上“行内代码”和“代码块”的图标尽量很好的区分。下面这个图是Slack的做法：
![unnamed](https://github.com/user-attachments/assets/aea8e34b-c0a2-42eb-a5dd-43b315bd9fa0)

供参考

**Comment by Saraph1nes** [comment]
> 第一种方案在区分两种格式方面更好，更清晰。但是关于：
> 
> > 选中多行内容时，每一行选中的内容两边增加``
> 
> 好像并不常用，多行用单引号可读性并不好，我不倾向于鼓励这样的操作
> 
> 另外，在工具条上“行内代码”和“代码块”的图标尽量很好的区分。下面这个图是Slack的做法： ![unnamed](https://private-user-images.githubusercontent.com/533236/350205881-aea8e34b-c0a2-42eb-a5dd-43b315bd9fa0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNjI3NDMsIm5iZiI6MTcyMTM2MjQ0MywicGF0aCI6Ii81MzMyMzYvMzUwMjA1ODgxLWFlYThlMzRiLWMwYTItNDJlYi1hNWRkLTQzYjMxNWJkOWZhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwNDE0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWU1YmM0ODM4M2VlYjU4YjA1NDA0NGExMjljOTY0NTNiNDRkYTU0OWZiOGJlMWM5YmRiOWU0ZGFhYWRiMDI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JtEPL4QZikfJnSVMt_XF-gXAn77i34wGjAmYmYhkXvU)
> 
> 供参考

感谢建议～
对于多行用单引号的操作，我体验了Typora与Slack，它们是支持的，所以我还是希望可以支持这种操作，保持一致的操作习惯。

**Comment by sunsonliu** [comment]
![image](https://github.com/user-attachments/assets/58f84650-9875-4646-8aec-0ad3c615af0d)
已发布，可以在[这里](https://tencent.github.io/cherry-markdown/examples/index.html)体验
