### ISSUE TITLE
[Others]【drawio】纯预览点击drawio图片能弹窗iframe界面 还能修改

### ISSUE THREAD

**Issue by snoopy123321** [Tencent/cherry-markdown#866]
尽管使用callback.onClickPreview直接return掉，但是没有效果
纯预览的情况能否不用弹出drawio啦

**Comment by sunsonliu** [comment]
收到，纯预览模式下确实不应该弹draw.io的编辑框，我们修改下哈

**Comment by foxfire881** [comment]
> 收到，纯预览模式下确实不应该弹draw.io的编辑框，我们修改下哈

顺便加个css啊 #813

**Comment by sunsonliu** [comment]
> > 收到，纯预览模式下确实不应该弹draw.io的编辑框，我们修改下哈
> 
> 顺便加个css啊 #813

收到收到，开会前紧急改了下，现在才散会，马上搞搞
