### ISSUE TITLE
快捷键配置无效

### ISSUE THREAD

**Issue by foxfire881** [Tencent/cherry-markdown#871]
1、如下，全部注释掉配置为空则工作正常可以使用默认快捷键，但是如果只开启一个，例如 'Ctrl-b': 'bold',则无法正常工作；

2、默认只设置了几个常用按钮的快捷键，如何对其他按钮新增快捷键？例如给全屏按钮 'full' 加个快捷键，要如何配置？以下配置中设置'Ctrl-Alt-f': 'full' 无效，提示找不到 full 按钮

3、快捷键只能Alt、Ctrl吗？能否设置 Ctrl+Alt+Shift+H 这种带Shift的快捷键？

```javascript
   // 快捷键配置，如果配置为空，则使用toolbar的配置
    shortcutKey: {
      // 'Alt-1': 'header',
      // 'Alt-2': 'header',
      // 'Ctrl-b': 'bold',
      // 'Ctrl-Alt-m': 'formula',
      // 'Ctrl-Alt-f': 'full'
    }
```

**Comment by sunsonliu** [comment]
https://github.com/Tencent/cherry-markdown/wiki/%E9%85%8D%E7%BD%AE%E5%BF%AB%E6%8D%B7%E9%94%AE
新的快捷键配置规则可以参考这篇wiki哈，会在下次发版后生效
