### ISSUE TITLE
主题样式的覆盖与修改？

### ISSUE THREAD

**Issue by foxfire881** [Tencent/cherry-markdown#873]
[主题配置](https://github.com/Tencent/cherry-markdown/wiki/%E9%85%8D%E7%BD%AE%E4%B8%BB%E9%A2%98) 只能修改theme文件夹下的一些基础的内容样式（如green.scss），而我想修改的样式在上一层 cherry.scss 里面，请问有没有方案可以在green.scss中覆盖cherry.scss的样式？试了用 !important 关键字也覆盖不了…

背景是Cherry的PreviewOnly页面的3D阴影边框不太适合我的整体页面风格，想调整成无边框的扁平风格，但是这个样式的控制点在cherry.scss 里面，每次版本更新都去修改这个文件、重新编译Cherry太麻烦了，想找个一劳永逸的方法。

另外，Cherry的 theme 都是打包集成在dist里面，自定义主题做好了也要随着新版本发布每次都要重新编译，很麻烦，最好能放在外部目录，直接扫描加载。

![捕获](https://github.com/user-attachments/assets/3c91cb2d-e7e3-45b2-bac7-cdb417a33ca1)

**Comment by sunsonliu** [comment]
可以在自己应用里用css控制样式哈，没必要改cherry的

**Comment by foxfire881** [comment]
> 可以在自己应用里用css控制样式哈，没必要改cherry的

优秀啊~~困扰了我好几天的问题，一句话就解决了666  试了在外部控制，效果满意
