### ISSUE TITLE
各种主题如何持久化保存？

### ISSUE THREAD

**Issue by foxfire881** [Tencent/cherry-markdown#874]
编辑器主题、代码主题目前都是缓存机制保存的，清空缓存或者换电脑登录后，主题又变回默认主题了，只能手动再切回去，比较麻烦。

如何才能持久化保存呢？配置参数中有个{editor: {theme: 'default'}} 参数改了没有生效。

**Comment by sunsonliu** [comment]
好像确实没有。。我们后面实现下，提供配置、api两种方式

**Comment by sunsonliu** [comment]
![image](https://github.com/user-attachments/assets/765af32f-fede-4e08-a18e-893b9725cd43)
如果着急的话，可以考虑直接修改这里的class

**Comment by foxfire881** [comment]
>  如果着急的话，可以考虑直接修改这里的class

改成编辑器主题改成 “default” 吗？主要是修改、编写css主题的时候比较麻烦，不能持久化导致稍微改动一下css想看看效果，结果vscode的热重载后主题就刷新了，又得重新设置。

**Comment by sunsonliu** [comment]
已实现并提交到dev分支，对应文档可以看[这里](https://github.com/Tencent/cherry-markdown/wiki/%E9%85%8D%E7%BD%AE%E4%B8%BB%E9%A2%98#%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE%E6%8C%81%E4%B9%85%E5%8C%96%E6%96%B9%E6%A1%88)哈

**Comment by sunsonliu** [comment]
> 已实现并提交到dev分支，对应文档可以看[这里](https://github.com/Tencent/cherry-markdown/wiki/%E9%85%8D%E7%BD%AE%E4%B8%BB%E9%A2%98#%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE%E6%8C%81%E4%B9%85%E5%8C%96%E6%96%B9%E6%A1%88)哈

那个。。抱歉。。这里的配置我还要改一改。。主要是把 `themeSettings.themeNameSpace`去掉，挪到了`nameSpace`里 ，`nameSpace`会影响所有cherry的缓存（还没提交代码，先打个预防针哈）

**Comment by sunsonliu** [comment]
> > 已实现并提交到dev分支，对应文档可以看[这里](https://github.com/Tencent/cherry-markdown/wiki/%E9%85%8D%E7%BD%AE%E4%B8%BB%E9%A2%98#%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE%E6%8C%81%E4%B9%85%E5%8C%96%E6%96%B9%E6%A1%88)哈
> 
> 那个。。抱歉。。这里的配置我还要改一改。。主要是把 `themeSettings.themeNameSpace`去掉，挪到了`nameSpace`里 ，`nameSpace`会影响所有cherry的缓存（还没提交代码，先打个预防针哈）

这段逻辑已更新，wiki文档也更新了，如有需要，可以使用`nameSpace`
