### ISSUE TITLE
脚注锚点失效

### ISSUE THREAD

**Issue by foxfire881** [Tencent/cherry-markdown#879]
之前修复 #790 的问题时，只改了 toc 的点击滚动代码，脚注的锚点还是用链接形式，点击一下就跳转走了没有适配 Vue单页面应用

**Comment by foxfire881** [comment]
点击后无法回滚到目标位置，应该是在[这个feat里](https://github.com/Tencent/cherry-markdown/commit/18aef74dcfbba548a4dab476fe3441e5d8d8ee7e) 没有只适配了toc，没有适配脚注

![捕获](https://github.com/user-attachments/assets/222c0292-a913-4771-a9af-b1312d7076cb)

**Comment by lai397826696** [comment]
![image](https://github.com/user-attachments/assets/d955c585-a3fe-456c-af68-0e98726547cb)
hash模式路由下，标题里的这些定位也是没有解决的，看下能否一并解决？

**Comment by sunsonliu** [comment]
收到收到。。。我们再改改。。感谢反馈哈~

**Comment by sunsonliu** [comment]
> ![image](https://private-user-images.githubusercontent.com/13134964/366284564-d955c585-a3fe-456c-af68-0e98726547cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjg3MjcsIm5iZiI6MTcyNjAyODQyNywicGF0aCI6Ii8xMzEzNDk2NC8zNjYyODQ1NjQtZDk1NWM1ODUtYTNmZS00NTZjLWFmNjgtMGU5ODcyNjU0N2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA0MjAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwOGU1ZDcxZTRiMTFiODI0N2JlMGFkOGIzMzgzNWI4Y2M5MTI4NDUyMmZmNGZiYmZiNzQzNmZhYTQwYjA0YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RBtziRjMuKiY8cPRs7GNDSABjIBFVLIjgRBg6jym0Nw) hash模式路由下，标题里的这些定位也是没有解决的，看下能否一并解决？

咦，不对呀，如果应用使用了hash路由，其实就不建议放出来标题旁边的超链接了。。建议修改配置去掉标题旁的超链接。配置如下：`engine.syntax.header.anchorStyle = 'none'`

**Comment by lai397826696** [comment]
> > ![image](https://private-user-images.githubusercontent.com/13134964/366284564-d955c585-a3fe-456c-af68-0e98726547cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjg3MjcsIm5iZiI6MTcyNjAyODQyNywicGF0aCI6Ii8xMzEzNDk2NC8zNjYyODQ1NjQtZDk1NWM1ODUtYTNmZS00NTZjLWFmNjgtMGU5ODcyNjU0N2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA0MjAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwOGU1ZDcxZTRiMTFiODI0N2JlMGFkOGIzMzgzNWI4Y2M5MTI4NDUyMmZmNGZiYmZiNzQzNmZhYTQwYjA0YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RBtziRjMuKiY8cPRs7GNDSABjIBFVLIjgRBg6jym0Nw) hash模式路由下，标题里的这些定位也是没有解决的，看下能否一并解决？
> 
> 咦，不对呀，如果应用使用了hash路由，其实就不建议放出来标题旁边的超链接了。。建议修改配置去掉标题旁的超链接。配置如下：`engine.syntax.header.anchorStyle = 'none'`

感谢，看配置大全可能看漏了，就脚注跳转的问题了
