### ISSUE TITLE
[Bug Report] MathJax 无法渲染

### ISSUE THREAD

**Issue by xdewx** [Tencent/cherry-markdown#880]
### Prerequisites

- [X] There isn't an existing issue that reports the same bug to avoid duplicates.
- [X] The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Describe the Bug
公式无法正常渲染,相关的配置文档也不详细;

```json
 mathBlock: {
    engine: 'MathJax', // katex or MathJax
    src: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js',
    plugins: true, // Default load plug-in
},
inlineMath: {
    engine: 'MathJax', // katex or MathJax
},
```

![图片](https://github.com/user-attachments/assets/4495c7f3-f0b6-4d9a-be74-1ff2d0690ee0)

另外经实践发现,根据当前的文档描述,mermaid的异步引入会出错,同样需要使用default解构才可以正常工作

```ts
const registerPlugin = async () => {
    const [{ default: CherryMermaidPlugin }, { default: mermaid }] = await Promise.all([
        import('cherry-markdown/src/addons/cherry-code-block-mermaid-plugin'),
        // import('cherry-markdown/src/addons/cherry-code-block-plantuml-plugin'),
        import('mermaid'),
        // import('mathjax/es5/tex-mml-svg'),
    ]);
    console.info(CherryMermaidPlugin, mermaid)
    Cherry.usePlugin(CherryMermaidPlugin, {
        mermaid, // pass in mermaid object
    });
};
```

### Contributing

None

**Comment by foxfire881** [comment]
配置问题吧，我这里是正常的：

```javascript
      mathBlock: {
        engine: "MathJax", // katex或MathJax
        src: import.meta.env.BASE_URL + "/mathjax/es5/tex-svg.js",
        plugins: true, // 默认加载插件
      },
      inlineMath: {
        engine: "MathJax", // katex或MathJax
        src: import.meta.env.BASE_URL + "/mathjax/es5/tex-svg.js",
      },
```


```javascript
import CherryMermaidPlugin from "cherry-markdown/dist/addons/cherry-code-block-mermaid-plugin";
import mermaid from "mermaid";

Cherry.usePlugin(CherryMermaidPlugin, {
  mermaid,
});
```


![捕获](https://github.com/user-attachments/assets/e6ce366a-c26a-4f9a-b17c-474934e82f1d)

**Comment by foxfire881** [comment]
> 你是指其他配置项可能影响到公式吗？直觉上来说都是独立的不应该呀
> 另外我是用的最新版本的markdown+mermaid9+echarts4(READMD文档上的版本号)
> 再者，您可以试下异步import看看mermaid的导入方式是不是如我所说

我也是最新版本，不过我没有用异步加载耶~ 很早之前在其他项目用过异步加载，感觉问题比较多处理、调试起来都很麻烦，意义也不大，所以后来就不用了，直接copy demo代码就能调通的事就不折腾了。

**Comment by foxfire881** [comment]
> ### Prerequisites
> * [x]  There isn't an existing issue that reports the same bug to avoid duplicates.
> * [x]  The provided information offers a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
> * [x]  For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.
> 
> ### Describe the Bug
> 公式无法正常渲染,相关的配置文档也不详细;
> 
> ```json
>  mathBlock: {
>     engine: 'MathJax', // katex or MathJax
>     src: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js',
>     plugins: true, // Default load plug-in
> },
> inlineMath: {
>     engine: 'MathJax', // katex or MathJax
> },
> ```
> 
> ![图片](https://private-user-images.githubusercontent.com/20438962/361233620-4495c7f3-f0b6-4d9a-be74-1ff2d0690ee0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTk1NTEsIm5iZiI6MTcyNDg5OTI1MSwicGF0aCI6Ii8yMDQzODk2Mi8zNjEyMzM2MjAtNDQ5NWM3ZjMtZjBiNi00ZDlhLWJlNzQtMWZmMmQwNjkwZWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAyNDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNDljZTU0MGI2MDU3MDY0YmEzOTlmYjJiMTU0NzU0Y2E1NGE3NzZlMTYxOTc5Mjc0YjZjY2I0MGJiZjc0NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vHF2TerZn0mHtj4bk5_ZJG_bQkicm16B98aCxcZLecU)
> 
> 另外经实践发现,根据当前的文档描述,mermaid的异步引入会出错,同样需要使用default解构才可以正常工作
> 
> ```ts
> const registerPlugin = async () => {
>     const [{ default: CherryMermaidPlugin }, { default: mermaid }] = await Promise.all([
>         import('cherry-markdown/src/addons/cherry-code-block-mermaid-plugin'),
>         // import('cherry-markdown/src/addons/cherry-code-block-plantuml-plugin'),
>         import('mermaid'),
>         // import('mathjax/es5/tex-mml-svg'),
>     ]);
>     console.info(CherryMermaidPlugin, mermaid)
>     Cherry.usePlugin(CherryMermaidPlugin, {
>         mermaid, // pass in mermaid object
>     });
> };
> ```
> 
> ### Reproduction Steps
> _No response_
> 
> ### System Information
> _No response_
> 
> ### Contributing
> None

又看了一遍你的配置，确实是少了一行，你只配置了Block块级公式的src，Inline行级公式的src没有配置，而你截图里插入的都是行级公式的代码，当然无法解析。

**Comment by ruisen2020** [comment]
您好，我版本改到0.8.45还是没有渲染成功该怎么办呀

**Comment by RSS1102** [comment]
> 您好，我版本改到0.8.45还是没有渲染成功该怎么办呀
见: https://github.com/Tencent/cherry-markdown/issues/961

**Comment by ruisen2020** [comment]
> > 您好，我版本改到0.8.45还是没有渲染成功该怎么办呀
> > 见: #961

这个不稳定，偶尔成功，经常失败

**Comment by RSS1102** [comment]
> > > 您好，我版本改到0.8.45还是没有渲染成功该怎么办呀
> > > 见: #961
> 
> 这个不稳定，偶尔成功，经常失败

mathjax 资源下载到本地引用

**Comment by ruisen2020** [comment]
抱歉，我用本地的，还是偶然成功，经常失败

**Comment by RSS1102** [comment]
> 抱歉，我用本地的，还是偶然成功，经常失败

请新开问题，提供一个复现视频和可复现代码片段。
