### ISSUE TITLE
如何隐藏联系框，配置showSuggestList为false没有生效

### ISSUE THREAD

**Issue by caseykshe** [Tencent/cherry-markdown#881]
<img width="275" alt="企业微信截图_cc7c3182-3895-4a3e-a39c-bbf7f3ee6304" src="https://github.com/user-attachments/assets/335b6a24-5120-4278-baf7-7ec95833a773">

希望隐藏上图的联系框，通过将showSuggestList设置为false无法生效，具体配置如下

```
    new Cherry({
      id: 'markdown-container',
      value: '## hello world',
      toolbars: {
        // 配置切换主题的按钮到顶部工具栏里
        toolbar: ['link'],
        float: false,
        bubble: false,
      },
      editor: { showSuggestList: false, height: '500px' },
      engine: {
        syntax: {
          header: false,
        },
      },
    });
```

**Comment by caseykshe** [comment]
> ![image](https://private-user-images.githubusercontent.com/998441/361704026-96bd0013-c204-4f37-8445-8c208d0e0c29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDUxNDksIm5iZiI6MTcyNDc0NDg0OSwicGF0aCI6Ii85OTg0NDEvMzYxNzA0MDI2LTk2YmQwMDEzLWMyMDQtNGYzNy04NDQ1LThjMjA4ZDBlMGMyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwNzQ3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzFlY2JiOGFlNjE5Y2UyOTY3NjIzOTEyZWIzODhmMGFlMWI1YTY5YTkxZmFhNDg4M2UwYjk3ZTQ4NzE5Yzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ma7V8eCdgLopsLIDZyRJk-6X5mGgs-PIQmWYrexV86I) ![image](https://private-user-images.githubusercontent.com/998441/361704419-76ca31a1-bc57-4ab1-9c47-81052fbae778.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDUxNDksIm5iZiI6MTcyNDc0NDg0OSwicGF0aCI6Ii85OTg0NDEvMzYxNzA0NDE5LTc2Y2EzMWExLWJjNTctNGFiMS05YzQ3LTgxMDUyZmJhZTc3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwNzQ3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODU4ZTQyY2IzOWU5NTNmYjRlMmFmZGEzNDEwNDYwYjM5YmU0ZGM0NTlmMWM0NDU5YmZiZjQzNGNlMDdiZWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.48vJcFP4UJnBSplXX1VDPUQekx_M79aZ8lpN2xOUcA8) 不应该呀。。。我这里试了下`showSuggestList: false`是正常的。。。

我使用的版本是 0.8.35，可以尝试复现一下

**Comment by sunsonliu** [comment]
哦哦，需要至少 0.8.41版本以上才支持该配置哈，可以参考这个issue： https://github.com/Tencent/cherry-markdown/issues/743
