### ISSUE TITLE
[Others]从其他平台导出的md文件存进cherry，外链图片因refererPolicy而加载失败

### ISSUE THREAD

**Issue by snoopy123321** [Tencent/cherry-markdown#882]
读取md文件，图片以外链存在，外链限制referer

故想给img标签增加referrerpolicy="no-referrer"属性，看了许久cherry配置文档，找不到img标签额外追加的属性。

请问img标签能不能追加属性？  需要我自定义语法去解决这个问题吗？

**Comment by sunsonliu** [comment]
![image](https://github.com/user-attachments/assets/94518f84-c2ad-4941-9a02-123ddd076714)

似乎可以尝试下这个回调函数。。。在提交前修改img标签的属性。。

**Comment by snoopy123321** [comment]
> ![image](https://private-user-images.githubusercontent.com/998441/362521354-94518f84-c2ad-4941-9a02-123ddd076714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDQzMTIsIm5iZiI6MTcyNDkwNDAxMiwicGF0aCI6Ii85OTg0NDEvMzYyNTIxMzU0LTk0NTE4Zjg0LWMyYWQtNDk0MS05YTAyLTEyM2RkZDA3NjcxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNDAwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTU3MjE0YzZlYzY1MjJjZWIyNDVhMzMxZmMzYTFkZTIzM2JmOWViOTU5ZWFmZGU1NzAxODY4NWRjNGZmYjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZozCJAYBO5_3onBPFoeM9tr74OIeFQsyFOJsNmLk7SE)
> 
> 似乎可以尝试下这个回调函数。。。在提交前修改img标签的属性。。

成了！测出来调用beforeLoadOneImgCallback前提是noLoadImgNum得是0（因为我的外链图片是第一张，所以让所有图片懒加载），才执行这个钩子。怪不得试了半天不打日志！
