### ISSUE TITLE
[Bug report] Err display when inline code mix usage with code

### ISSUE THREAD

**Issue by hanye9895** [Tencent/cherry-markdown#90]
Err display when inline code mix usage with code

**To Reproduce**
when code is 
```
```使用 `代码` 表示行内代码```

**示例**
```
would be fine
<img width="607" alt="Screen Shot 2022-01-05 at 8 40 16 PM" src="https://user-images.githubusercontent.com/68373171/148219157-b9a68803-a321-4dab-a7bb-fc080138f723.png">

but add an code block after will case error

```
```使用 `代码` 表示行内代码```

**示例**
\```
让我们聊聊 `html`
\```
```
<img width="637" alt="Screen Shot 2022-01-05 at 8 40 20 PM" src="https://user-images.githubusercontent.com/68373171/148219184-e3a9970a-525b-41ae-8fee-20560522289f.png">

**Expected behavior**
show the previous code block normally

**Environment (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 96

**Comment by jiawei686** [comment]
Hi, thanks for your report!
It seems that code block hook make a mistake while handling this. I will investigate.
