### ISSUE TITLE
[Docs] Loading from the top of the page in the browser

### ISSUE THREAD

**Issue by evgip** [Tencent/cherry-markdown#907]
### Prerequisites

- [X] There isn't an existing issue with the same question or request to avoid duplicates.

### Issue Type

Question

### Description of the Problem or Idea

On the editor's website page, it is located at the very bottom of the article. The article may consist of several paragraphs and be quite large. When you go to this page, it is automatically adjusted to the editor, and a vertical scroll appears.

I removed the focus, but the situation doesn't seem to change.

```
codemirror: {
	autofocus: false,
},
```

![1-2](https://github.com/user-attachments/assets/cf4e81a6-323b-4e7b-b811-b8b548f4db59)

Maybe this will be useful:  if you turn off editing  `defaultModel: 'previewOnly',` 

![2](https://github.com/user-attachments/assets/a3765a3e-1a5e-442c-b8db-d666ed0a3125)

then the page with the article loads as it should from the very top, as if there is no editor.

Perhaps I missed some setting, or how can I get out of this situation (the article should open at the top, the focus should not go to the editor).. Thank you.

### Contributing

None

**Comment by sunsonliu** [comment]
Try the code below：
```
new Cherry({
    ...
    editor: {
        keepDocumentScrollAfterInit: true,
    }
    ...
})
```

**Comment by evgip** [comment]
@sunsonliu  Thanks, I tried that. Unfortunately, the browser page still scrolls to the editor.

**Comment by sunsonliu** [comment]
Sorry, I cannot reproduce it. Maybe you can try the following code.
```
new Cherry({
    ...
    editor: {
        keepDocumentScrollAfterInit: true,
        codemirror: {
            autofocus: false,
        },
    }
    ...
})
```

**Comment by evgip** [comment]
@sunsonliu Thank you, unfortunately it doesn't work.

I created a working example on a test domain:  https://agouti.ru/

There is an editor code on the article page, I will duplicate it here, maybe there is an error somewhere.

```
<script>
	var cherry = new Cherry({
		id: 'markdown-container',
		value: '',
		togglePreview: false,

		editor: {
			name: 'content',
			keepDocumentScrollAfterInit: true,
			defaultModel: 'editOnly',
			height: '300px',
			showSuggestList: false,
			codemirror: {
				autofocus: false,
			},
		},

		toolbars: {
			showToolbar: false,
			sidebar: ['togglePreview'],
			toolbarRight: ['togglePreview'],
			bubble: ['bold', 'italic', 'strikethrough', 'quote', 'inlineCode'],
			float: ['h2', 'h3', '|', 'checklist', 'quote', 'code'],
		},
	});
</script>
```

The archive of this example itself (maybe it will be useful) is attached here.

[editor.zip](https://github.com/user-attachments/files/17098014/editor.zip)

**Comment by sunsonliu** [comment]
You can try the latest version（[v0.8.48](https://github.com/Tencent/cherry-markdown/releases/tag/v0.8.48)）. I tested it with the latest version and found that it works fine.
![1111](https://github.com/user-attachments/assets/bd587e5f-173e-429c-bff4-2950246f22ce)

**Comment by evgip** [comment]
Thank you very much! Yes, it works.
