### ISSUE TITLE
[Feature request] 老tapd语法兼容-图片大小语法

### ISSUE THREAD

**Issue by PointMountain** [Tencent/cherry-markdown#91]
老tapd语法兼容-图片大小语法

```
![一条dog#auto#100px#right](images/demo-dog.png =20x20)
```

<img width="1109" alt="wecom-temp-f388a66cbef5311d6a8ec3589f9452a5" src="https://user-images.githubusercontent.com/29696798/148348097-b00e7d8a-bd64-4f68-8315-9afae8b4bfa8.png">

**Comment by sunsonliu** [comment]
目前我们**不打算**支持这种语法哈，我们已经实现了新的图片宽高的语法，并且TAPD也支持了这种新的语法，建议改成新的图片高宽语法哈，新的语法还支持图片对齐方式，很强的，欢迎体验：
https://tencent.github.io/cherry-markdown/examples/img.html
