### ISSUE TITLE
[VSCode Plugin] 针对vscode插件的若干优化

### ISSUE THREAD

**Issue by sunsonliu** [Tencent/cherry-markdown#926]
### issue type

Feature

### Clear and concise description of the problem or idea.

1. 过往代码整理，对于过往的vscode代码进行代码梳理，优化代码逻辑和移除冗余文件和代码。 #920 
2. 支持不同 link 使用默认浏览器打开网页，本地文件。#922

3. 修复预览图片错误的问题。 https://github.com/Tencent/cherry-markdown/pull/972

~~4. 添加文件右键菜单打开预览按钮。~~

> 因之前的逻辑实现问题，可能要大量重构，先搁置此需求。

5. 添加快捷键，支持在md文件内容内可以用快捷键打开。#934
6. 在 cherry-markdown 面板添加 toc 功能。#937
7. 升级 cherry-markdown 资源到 `v0.8.49` #935
8. 在 vscode 为 `dark` 模式时，cherry-markdown 的 theme 为 default 的时，vscode 的 scrollbar 会出现黑色滚动条。 #946
![image](https://github.com/user-attachments/assets/263461df-43dc-44a9-8db0-e9ac1e2427bf)
![image](https://github.com/user-attachments/assets/af661115-e967-457b-89a6-e8792b263435)
9. 修复选中主题回显 https://github.com/Tencent/cherry-markdown/pull/965 (此 pr 将 cherry-markdown 资源到 `v0.8.50` )

### Validations

- [ ] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Help us

None

**Comment by RSS1102** [comment]
其中`3.修复预览图片错误的问题(代码回归问题)。`出现无法访问得情况是因为 vscode无法访问工作区意外的文件。
即当md文件引用的图片在vscode所打开的文件夹之外的话将无法访问和显示。
