### ISSUE TITLE
[Bug report] 视频poster希望能正常显示

### ISSUE THREAD

**Issue by PointMountain** [Tencent/cherry-markdown#93]
视频poster貌似不能正常显示啦

eg:
```
## 插入音视频
**说明**
- 使用 `!v[描述](视频链接地址)` 插入视频
    - 使用 `!v[描述](视频链接地址){poster=封面地址}` 插入视频并配上封面
- 使用 `!audio[描述](视频链接地址)` 插入音频
!video[不带封面演示视频](images/demo.mp4){poster=https://www.tapd.cn/img/nwx-official/logo-square.png}
```

<img width="1590" alt="wecom-temp-5fc286c81607880944487430499dae06" src="https://user-images.githubusercontent.com/29696798/148350249-551597f5-0939-4f98-b328-825be400d6a6.png">

**Comment by hanye9895** [comment]
It seems that Image(video) hook do not deal with poster yet, I will try to fix it.

**Comment by PointMountain** [comment]
感谢修正
