### ISSUE TITLE
[Feature Request]onPaste入参增加Editor实例

### ISSUE THREAD

**Issue by xuliuzhu1834** [Tencent/cherry-markdown#931]
### Prerequisites

- [ ] There isn't an existing issue that requests the same feature, to avoid duplicates.

### Clear and concise description of the problem

目前onPaste的callback是这样的
```
onPaste?: (clipboardData: ClipboardEvent['clipboardData']) => string | boolean;
```

### Suggested solution

建议增加editor实例
```
onPaste?: (clipboardData: ClipboardEvent['clipboardData']， cherry: Cherry) => string | boolean;
```

### Contributing

None

**Comment by sunsonliu** [comment]
已发布，0.8.50在onPaste回调函数中传入了cherry实例
