### ISSUE TITLE
为啥我这里公式展示没有效果，是哪里没有配置嘛

### ISSUE THREAD

**Issue by ruisen2020** [Tencent/cherry-markdown#961]
### Prerequisites

- [ ] There isn't an existing issue that requests the same feature, to avoid duplicates.

### Issue Type

Bug Report

### Version

0.8.49

### Description of the Problem or Idea

![image](https://github.com/user-attachments/assets/d804a76d-c79d-488a-9a44-18055d0839c6)

### Contributing

None

**Comment by RSS1102** [comment]
参考: https://github.com/Tencent/cherry-markdown/blob/main/examples/scripts/index-demo.js#L138

**Comment by ruisen2020** [comment]
![image](https://github.com/user-attachments/assets/31e9edcd-279c-41d8-9e89-5068a87226d8)

this.problemDescriptionMarkdown = new Cherry({
        id: "problemDescriptionMarkdown",
        value:
          "<p>有 $N$ 种物品和一个容量是 $V$ 的背包。</p><p>第 $i$ 种物品最多有 $s_i$ 件，每件体积是 $v_i$，价值是 $w_i$。</p><p>求解将哪些物品装入背包，可使物品体积总和不超过背包容量，且价值总和最大。<br />输出最大价值。</p>",
        editor: {
          defaultModel: "previewOnly",
        },
        engine: {
          syntax: {
            mathBlock: {
              engine: "MathJax", // katex或MathJax
              src: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js", // 如果使用MathJax plugins，则需要使用该url通过script标签引入
            },
            inlineMath: {
              engine: "MathJax", // katex或MathJax
            },
          },
        },
      });
      
      我这样没有起作用是为啥

**Comment by RSS1102** [comment]
你可以提供一个你当前可运行的最小实现repo，以便快速发现问题。

![image](https://github.com/user-attachments/assets/0f9444f6-6936-4122-9093-d0a587e7d513)

**Comment by ruisen2020** [comment]
```
<template>
  <div>
    <!-- Markdown 编辑器容器 -->
    <div ref="markdownContainer"></div>
    <!-- 可选：Markdown 输入框，用于动态改变编辑器内容 -->
    <!-- <textarea ref="markdownTextarea" v-model="markdownText"></textarea> -->
  </div>
</template>
  
  <script>
// import "cherry-markdown/dist/cherry-markdown.css";
import Cherry from "cherry-markdown/dist/cherry-markdown.core";
import CherryMermaidPlugin from "cherry-markdown/dist/addons/cherry-code-block-mermaid-plugin";
import mermaid from "mermaid";
import api from "@/common/api";
export default {
  data() {
    return {
      markdownText: "# Hello, Cherry Editor!", // 初始 Markdown 文本
    };
  },
  created() {
    this.initCherryEditor();
  },
  methods: {
    initCherryEditor() {
      // 初始化 Cherry 编辑器实例
      // 插件注册必须在Cherry实例化之前完成
      Cherry.usePlugin(CherryMermaidPlugin, {
        mermaid, // 传入mermaid引用
        // mermaidAPI: mermaid.mermaidAPI, // 也可以传入mermaid API
        // 同时可以在这里配置mermaid的行为，可参考mermaid官方文档
        // theme: 'neutral',
        // sequence: { useMaxWidth: false, showSequenceNumbers: true }
      });
      this.cherryInstance = new Cherry({
        id: this.$refs.markdownContainer, // 绑定到指定 DOM 节点
        value: this.markdownText, // 初始化的 Markdown 内容
        fileUpload: this.myFileUpload,
        toolbars: {
          // 定义顶部工具栏
          toolbar: [
            "undo",
            "redo",
            "|",
            {
              bold: [
                "bold",
                "italic",
                "underline",
                "strikethrough",
                "sub",
                "sup",
                "ruby",
              ],
            },
            "|",
            "color",
            "header",
            "|",
            "list",
            "panel",
            "detail",
            "drawIo",
            {
              insert: [
                "image",
                "pdf",
                "word",
                "file",
                "link",
                "hr",
                "br",
                "code",
                "formula",
                "toc",
                "table",
                "drawIo",
              ],
            },
            "graph",
            "settings",
            "codeTheme",
          ],

          // 定义侧边栏，默认为空
          sidebar: ["theme", "mobilePreview", "copy"],
          // 定义顶部右侧工具栏，默认为空
          toolbarRight: ["fullScreen", "export", "wordCount"],
          // 定义选中文字时弹出的“悬浮工具栏”，默认为 ['bold', 'italic', 'underline', 'strikethrough', 'sub', 'sup', 'quote', '|', 'size', 'color']
          bubble: [
            "bold",
            "italic",
            "underline",
            "strikethrough",
            "sub",
            "sup",
            "quote",
            "|",
            "size",
            "color",
          ],
          engine: {
            syntax: {
              mathBlock: {
                engine: "MathJax", // katex或MathJax
                src: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js", // 如果使用MathJax plugins，则需要使用该url通过script标签引入
              },
              inlineMath: {
                engine: "MathJax", // katex或MathJax
              },
            },
          },

          // toc: true, // 不展示悬浮目录

          // toc: {
          //   updateLocationHash: false, // 要不要更新URL的hash
          //   defaultModel: "full", // pure: 精简模式/缩略模式，只有一排小点； full: 完整模式，会展示所有标题
          //   showAutoNumber: false, // 是否显示自增序号
          //   position: "fixed", // 悬浮目录的悬浮方式。当滚动条在cherry内部时，用absolute；当滚动条在cherry外部时，用fixed
          //   cssText: "", // 自定义样式
          // },

          // 定义光标出现在行首位置时出现的“提示工具栏”，默认为 ['h1', 'h2', 'h3', '|', 'checklist', 'quote', 'table', 'code']
          float: ["h1", "h2", "h3", "|", "checklist", "quote", "table", "code"],
        },
        drawioIframeUrl:
          window.location.origin + "/cherryMarkdown/drawio_demo.html",
        drawioIframeStyle: "border: none; width: 100%; height: 100%;",
      });
    },
    myFileUpload(file1, callback) {
      const formData = new FormData();
      formData.append("file", file1);
      // 先把文件上传到服务端，上传文件的具体代码需要自行实现
      api.uploadArticlePictureAndFile(formData).then((response) => {
        if (response.data.code == "200") {
          callback(response.data.data);
        }
      });
      // putFile(file, function (err, url) {
      //   if (err) {
      //     // 上传失败
      //   } else {
      //     callback(url);
      //   }
      // });
    },
  },
  beforeDestroy() {
    // 清理工作，例如销毁编辑器实例
    if (this.cherryInstance) {
      this.cherryInstance.destroy();
    }
  },
};
</script>

<style >
::v-deep #cherry-markdown {
  width: 1000px;
  height: 500px;
}
</style>
```

抱歉，我这里还是没效果，您帮我看下好吗

**Comment by RSS1102** [comment]
层级错误 请仔细核对
![image](https://github.com/user-attachments/assets/3bf8b511-62dd-4916-b111-0edbad21318a)

![image](https://github.com/user-attachments/assets/ad2a8a50-b0c5-449d-8d47-4871e24d167b)

**Comment by ruisen2020** [comment]
# 还是没作用，我心态炸裂了
```
<template>
  <div>
    <!-- Markdown 编辑器容器 -->
    <div ref="markdownContainer"></div>
    <!-- 可选：Markdown 输入框，用于动态改变编辑器内容 -->
    <!-- <textarea ref="markdownTextarea" v-model="markdownText"></textarea> -->
  </div>
</template>
  
  <script>
// import "cherry-markdown/dist/cherry-markdown.css";
import Cherry from "cherry-markdown/dist/cherry-markdown.core";
import CherryMermaidPlugin from "cherry-markdown/dist/addons/cherry-code-block-mermaid-plugin";
import mermaid from "mermaid";
import api from "@/common/api";
export default {
  data() {
    return {
      markdownText: "# Hello, Cherry Editor!", // 初始 Markdown 文本
    };
  },
  created() {
    this.initCherryEditor();
  },
  methods: {
    initCherryEditor() {
      // 初始化 Cherry 编辑器实例
      // 插件注册必须在Cherry实例化之前完成
      Cherry.usePlugin(CherryMermaidPlugin, {
        mermaid, // 传入mermaid引用
        // mermaidAPI: mermaid.mermaidAPI, // 也可以传入mermaid API
        // 同时可以在这里配置mermaid的行为，可参考mermaid官方文档
        // theme: 'neutral',
        // sequence: { useMaxWidth: false, showSequenceNumbers: true }
      });
      this.cherryInstance = new Cherry({
        id: this.$refs.markdownContainer, // 绑定到指定 DOM 节点
        value: this.markdownText, // 初始化的 Markdown 内容
        fileUpload: this.myFileUpload,
        toolbars: {
          // 定义顶部工具栏
          toolbar: [
            "undo",
            "redo",
            "|",
            {
              bold: [
                "bold",
                "italic",
                "underline",
                "strikethrough",
                "sub",
                "sup",
                "ruby",
              ],
            },
            "|",
            "color",
            "header",
            "|",
            "list",
            "panel",
            "detail",
            "drawIo",
            {
              insert: [
                "image",
                "pdf",
                "word",
                "file",
                "link",
                "hr",
                "br",
                "code",
                "formula",
                "toc",
                "table",
                "drawIo",
              ],
            },
            "graph",
            "settings",
            "codeTheme",
          ],

          // 定义侧边栏，默认为空
          sidebar: ["theme", "mobilePreview", "copy"],
          // 定义顶部右侧工具栏，默认为空
          toolbarRight: ["fullScreen", "export", "wordCount"],
          // 定义选中文字时弹出的“悬浮工具栏”，默认为 ['bold', 'italic', 'underline', 'strikethrough', 'sub', 'sup', 'quote', '|', 'size', 'color']
          bubble: [
            "bold",
            "italic",
            "underline",
            "strikethrough",
            "sub",
            "sup",
            "quote",
            "|",
            "size",
            "color",
          ],

          // toc: true, // 不展示悬浮目录

          // toc: {
          //   updateLocationHash: false, // 要不要更新URL的hash
          //   defaultModel: "full", // pure: 精简模式/缩略模式，只有一排小点； full: 完整模式，会展示所有标题
          //   showAutoNumber: false, // 是否显示自增序号
          //   position: "fixed", // 悬浮目录的悬浮方式。当滚动条在cherry内部时，用absolute；当滚动条在cherry外部时，用fixed
          //   cssText: "", // 自定义样式
          // },

          // 定义光标出现在行首位置时出现的“提示工具栏”，默认为 ['h1', 'h2', 'h3', '|', 'checklist', 'quote', 'table', 'code']
          float: ["h1", "h2", "h3", "|", "checklist", "quote", "table", "code"],
        },
        engine: {
          syntax: {
            mathBlock: {
              engine: "MathJax", // katex或MathJax
              src: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js", // 如果使用MathJax plugins，则需要使用该url通过script标签引入
            },
            inlineMath: {
              engine: "MathJax", // katex或MathJax
            },
          },
        },
        drawioIframeUrl:
          window.location.origin + "/cherryMarkdown/drawio_demo.html",
        drawioIframeStyle: "border: none; width: 100%; height: 100%;",
      });
    },
    myFileUpload(file1, callback) {
      const formData = new FormData();
      formData.append("file", file1);
      // 先把文件上传到服务端，上传文件的具体代码需要自行实现
      api.uploadArticlePictureAndFile(formData).then((response) => {
        if (response.data.code == "200") {
          callback(response.data.data);
        }
      });
      // putFile(file, function (err, url) {
      //   if (err) {
      //     // 上传失败
      //   } else {
      //     callback(url);
      //   }
      // });
    },
  },
  beforeDestroy() {
    // 清理工作，例如销毁编辑器实例
    if (this.cherryInstance) {
      this.cherryInstance.destroy();
    }
  },
};
</script>

<style >
::v-deep #cherry-markdown {
  width: 1000px;
  height: 500px;
}
</style>
```

**Comment by RSS1102** [comment]
> # 还是没作用，我心态炸裂了
> ```
> <template>
>   <div>
>     
>     <div ref="markdownContainer"></div>
>     
>     
>   </div>
> </template>
>   
>   <script>
> // import "cherry-markdown/dist/cherry-markdown.css";
> import Cherry from "cherry-markdown/dist/cherry-markdown.core";
> import CherryMermaidPlugin from "cherry-markdown/dist/addons/cherry-code-block-mermaid-plugin";
> import mermaid from "mermaid";
> import api from "@/common/api";
> export default {
>   data() {
>     return {
>       markdownText: "# Hello, Cherry Editor!", // 初始 Markdown 文本
>     };
>   },
>   created() {
>     this.initCherryEditor();
>   },
>   methods: {
>     initCherryEditor() {
>       // 初始化 Cherry 编辑器实例
>       // 插件注册必须在Cherry实例化之前完成
>       Cherry.usePlugin(CherryMermaidPlugin, {
>         mermaid, // 传入mermaid引用
>         // mermaidAPI: mermaid.mermaidAPI, // 也可以传入mermaid API
>         // 同时可以在这里配置mermaid的行为，可参考mermaid官方文档
>         // theme: 'neutral',
>         // sequence: { useMaxWidth: false, showSequenceNumbers: true }
>       });
>       this.cherryInstance = new Cherry({
>         id: this.$refs.markdownContainer, // 绑定到指定 DOM 节点
>         value: this.markdownText, // 初始化的 Markdown 内容
>         fileUpload: this.myFileUpload,
>         toolbars: {
>           // 定义顶部工具栏
>           toolbar: [
>             "undo",
>             "redo",
>             "|",
>             {
>               bold: [
>                 "bold",
>                 "italic",
>                 "underline",
>                 "strikethrough",
>                 "sub",
>                 "sup",
>                 "ruby",
>               ],
>             },
>             "|",
>             "color",
>             "header",
>             "|",
>             "list",
>             "panel",
>             "detail",
>             "drawIo",
>             {
>               insert: [
>                 "image",
>                 "pdf",
>                 "word",
>                 "file",
>                 "link",
>                 "hr",
>                 "br",
>                 "code",
>                 "formula",
>                 "toc",
>                 "table",
>                 "drawIo",
>               ],
>             },
>             "graph",
>             "settings",
>             "codeTheme",
>           ],
> 
>           // 定义侧边栏，默认为空
>           sidebar: ["theme", "mobilePreview", "copy"],
>           // 定义顶部右侧工具栏，默认为空
>           toolbarRight: ["fullScreen", "export", "wordCount"],
>           // 定义选中文字时弹出的“悬浮工具栏”，默认为 ['bold', 'italic', 'underline', 'strikethrough', 'sub', 'sup', 'quote', '|', 'size', 'color']
>           bubble: [
>             "bold",
>             "italic",
>             "underline",
>             "strikethrough",
>             "sub",
>             "sup",
>             "quote",
>             "|",
>             "size",
>             "color",
>           ],
> 
>           // toc: true, // 不展示悬浮目录
> 
>           // toc: {
>           //   updateLocationHash: false, // 要不要更新URL的hash
>           //   defaultModel: "full", // pure: 精简模式/缩略模式，只有一排小点； full: 完整模式，会展示所有标题
>           //   showAutoNumber: false, // 是否显示自增序号
>           //   position: "fixed", // 悬浮目录的悬浮方式。当滚动条在cherry内部时，用absolute；当滚动条在cherry外部时，用fixed
>           //   cssText: "", // 自定义样式
>           // },
> 
>           // 定义光标出现在行首位置时出现的“提示工具栏”，默认为 ['h1', 'h2', 'h3', '|', 'checklist', 'quote', 'table', 'code']
>           float: ["h1", "h2", "h3", "|", "checklist", "quote", "table", "code"],
>         },
>         engine: {
>           syntax: {
>             mathBlock: {
>               engine: "MathJax", // katex或MathJax
>               src: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js", // 如果使用MathJax plugins，则需要使用该url通过script标签引入
>             },
>             inlineMath: {
>               engine: "MathJax", // katex或MathJax
>             },
>           },
>         },
>         drawioIframeUrl:
>           window.location.origin + "/cherryMarkdown/drawio_demo.html",
>         drawioIframeStyle: "border: none; width: 100%; height: 100%;",
>       });
>     },
>     myFileUpload(file1, callback) {
>       const formData = new FormData();
>       formData.append("file", file1);
>       // 先把文件上传到服务端，上传文件的具体代码需要自行实现
>       api.uploadArticlePictureAndFile(formData).then((response) => {
>         if (response.data.code == "200") {
>           callback(response.data.data);
>         }
>       });
>       // putFile(file, function (err, url) {
>       //   if (err) {
>       //     // 上传失败
>       //   } else {
>       //     callback(url);
>       //   }
>       // });
>     },
>   },
>   beforeDestroy() {
>     // 清理工作，例如销毁编辑器实例
>     if (this.cherryInstance) {
>       this.cherryInstance.destroy();
>     }
>   },
> };
> </script>
> 
> <style >
> ::v-deep #cherry-markdown {
>   width: 1000px;
>   height: 500px;
> }
> </style>
> ```

你提供的代码是可以正常运行的

**Comment by ruisen2020** [comment]
啊？为啥我还是不起作用

**Comment by RSS1102** [comment]
> 啊？为啥我还是不起作用

请仔细检查一下自己的代码，或者从https://github.com/Tencent/cherry-markdown/tree/main/examples 下载代码进行尝试。

**Comment by ruisen2020** [comment]
突然好了，可能是样式没加载上来，感谢

**Comment by CNWebArmy** [comment]
我的配置感觉没啥问题，但是不展示呢

**Comment by CNWebArmy** [comment]
cherryConfig: {
        editor: {
          height: 'auto',
          defaultModel: 'previewOnly'
        },
        engine: {
          global: {
            // 开启流式模式 （默认 true）
            flowSessionContext: true
          },
          syntax: {
            mathBlock: {
              enable: true,
              engine: 'MathJax', // katex 或 MathJax
              src: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js',
              plugins: true // 默认加载插件
            },
            inlineMath: {
              enable: true,
              engine: 'MathJax', // katex 或 MathJax
              src: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js'
            },
           codeBlock: {
              selfClosing: false
            },
            header: {
              anchorStyle: 'none'
            },
            table: {
              selfClosing: false
            },
            fontEmphasis: {
              selfClosing: false
            },
            link: {
              /** 生成的<a>标签追加target属性的默认值 空：在<a>标签里不会追加target属性， _blank：在<a>标签里追加target="_blank"属性 */
              target: '_blank',
              /** 生成的<a>标签追加rel属性的默认值 空：在<a>标签里不会追加rel属性， nofollow：在<a>标签里追加rel="nofollow：在"属性*/
              rel: ''
            }
          }
        },
        previewer: {
          enablePreviewerBubble: false
        },
        isPreviewOnly: true
      },

**Comment by CNWebArmy** [comment]
我现在只是用于展示，接口返回的公式是展示不了的，但是启用编辑，调用工具的公式插入是可以展示的，好奇怪

**Comment by CNWebArmy** [comment]
$$ \frac{1030 \text{ bits}}{0.103 \text{ seconds}} \approx 10000 \text{ bps} $$ 这种展示不了（怀疑是 \f \t 转译了）
$$ e=mc^2 $$ 这种可以展示
