### ISSUE TITLE
[Bug Report]cherry makdown放在表单里，每次页面初始化后，会滚动到cherry的位置

### ISSUE THREAD

**Issue by linx5867** [Tencent/cherry-markdown#978]
### Prerequisites

- [X] There isn't an existing issue that reports the same bug to avoid duplicates.
- [ ] The provided information offers a [minimal reproducible example](https://github.com/Tencent/cherry-markdown/tree/main/examples) of the bug
([Why create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)).

- [ ] For [Q&A](https://github.com/Tencent/cherry-markdown/discussions/categories/q-a), 
please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Version

latest

### Reproduction Link

https://ceresit.msforyou.ru/article.html

### Describe the Bug

cherry makdown放在表单里(不在表单里貌似也有问题)，每次页面初始化后，会滚动到cherry的位置。目前发现如果“禁用缓存”，是可以回到顶部的，允许缓存就会滚动到编辑器位置

### System Information

```Shell
macbook chrome
```

### Contributing

None

**Comment by WangleJiu** [comment]
我更新了0.8.58版本，但是这个问题还是存在
