### ISSUE TITLE
[Feature Request] 支持@ mention 功能

### ISSUE THREAD

**Issue by liniu** [Tencent/cherry-markdown#984]
### Prerequisites

- [ ] There isn't an existing issue that requests the same feature, to avoid duplicates.

### Clear and concise description of the problem

支持定义@功能，可以参考 [tribute](https://github.com/zurb/tribute)

### Contributing

None

**Comment by sunsonliu** [comment]
有的，可以参考这个哈：https://github.com/Tencent/cherry-markdown/blob/main/examples/suggester.html

**Comment by liniu** [comment]
原来已经有了，谢谢
