### ISSUE TITLE
[Bug report] Customize Toolbar 按照官网示例不生效

### ISSUE THREAD

**Issue by yangrunkang** [Tencent/cherry-markdown#99]
**Describe the bug**
Customize Toolbar 按照官网示例不生效.

**To Reproduce**
见截图

**Expected behavior**
无

**Screenshots**
![image](https://user-images.githubusercontent.com/46257933/148667345-58dbe4f8-9fc9-43e9-9ab9-f9063475484d.png)

**Environment (please complete the following information):**
 - Chrome 版本 97.0.4692.71（正式版本） (x86_64)

**Additional context**

**Comment by lyngai** [comment]
文档中示例存在两处问题： 使用的工厂方法错误；以及遗漏了一项表述。

注册了自定义菜单后还需要配置到工具栏才能生效，我们修改一下文档，也欢迎 PR。

```ts
const addPrefix = Cherry.createMenuHook(...);
new Cherry({
  // ...
  toolbars: {
    toolbar: [..., 'addPrefix'],
    customMenu: {
      addPrefix: AddPrefixTemplate,
    },
  },
});
```

**Comment by yangrunkang** [comment]
谢谢
