### ISSUE TITLE
[Feature Request]代码库块预览时能否允许用于自定义按钮，比如需要根据代码块动态执行

### ISSUE THREAD

**Issue by girlinsouth** [Tencent/cherry-markdown#992]
### Prerequisites

- [ ] There isn't an existing issue that requests the same feature, to avoid duplicates.

### Clear and concise description of the problem

比如需要根据代码块动态执行

### Suggested solution

支持用户自定义按钮

### Contributing

No, I don't plan to at this time.

**Comment by sunsonliu** [comment]
可参考这里：https://github.com/Tencent/cherry-markdown/blob/main/examples/scripts/index-demo.js#L140
