### ISSUE TITLE
[Bug Report]转html的bad case

### ISSUE THREAD

**Issue by caseykshe** [Tencent/cherry-markdown#993]
### Prerequisites

- [X] There isn't an existing issue that reports the same bug to avoid duplicates.
- [X] The provided information offers a [minimal reproducible example](https://github.com/Tencent/cherry-markdown/tree/main/examples) of the bug, ([Why create a Minimal](https://stackoverflow.com/help/minimal-reproducible-example)).

- [X] For [Q&A](https://github.com/Tencent/cherry-markdown/discussions/categories/q-a), please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

### Version

v0.8.35

### Describe the Bug

对以下文本转为html，span标签被错误处理
```
U8拖挂的时候需要什么驾照？

答:U8总质量+后面房车总质量>4500kg,A2驾照;
U8总质量+后面房车总质量<4500kg,C6驾照<span id="ai-qa-ref" data-completion-id="423366aea0d94ed394da8698dbebc9ba" data-ref-doc="1" data-ref-chunks="1">1</span>。
```

转化结果如下图所示
<img width="1854" alt="Clipboard_Screenshot_1733737684" src="https://github.com/user-attachments/assets/491ec799-85ba-4bc3-88d9-60bc9cacf524">

### Contributing

None

**Comment by sunsonliu** [comment]
目测是和前面的小于号冲突了，**临时解决方案**可以先把前面的小于号用行内代码包裹起来，如下图哈：
![image](https://github.com/user-attachments/assets/f462f6fd-abfc-4b9e-ad5c-d565dc14fb70)
